// Words on the patient forms page, in English, Spanish and Arabic. Plain, short sentences:
// many of our patients are older and not used to filling things in online.
import type { IntakeLang } from "@shared/intake";

type S = Record<IntakeLang, string>;
const s = (en: string, es: string, ar: string): S => ({ en, es, ar });

export const T = {
  brand: s("MyPCP Dr", "MyPCP Dr", "MyPCP Dr"),
  yourForms: s("Your forms", "Sus formularios", "النماذج الخاصة بك"),
  chooseLanguage: s("Choose your language", "Elija su idioma", "اختر لغتك"),
  intro: s(
    "Please fill out your forms before your visit. It takes about {m} minutes.",
    "Por favor llene sus formularios antes de su cita. Toma unos {m} minutos.",
    "يرجى تعبئة النماذج قبل موعدك. يستغرق ذلك حوالي {m} دقائق.",
  ),
  saveNote: s(
    "Your answers save as you go. You can stop and come back later with the same link.",
    "Sus respuestas se guardan solas. Puede parar y regresar después con el mismo enlace.",
    "تُحفظ إجاباتك تلقائيًا. يمكنك التوقف والعودة لاحقًا باستخدام نفس الرابط.",
  ),
  helpNote: s(
    "A family member or caregiver can help you fill this out.",
    "Un familiar o cuidador puede ayudarle a llenarlo.",
    "يمكن لأحد أفراد العائلة أو مقدّم الرعاية مساعدتك في تعبئته.",
  ),
  privacy: s("Private and secure. Only our clinic sees your answers.", "Privado y seguro. Solo nuestra clínica ve sus respuestas.", "خاص وآمن. عيادتنا فقط تطّلع على إجاباتك."),
  start: s("Start", "Comenzar", "ابدأ"),
  dobTitle: s("First, please enter your date of birth", "Primero, escriba su fecha de nacimiento", "أولاً، يرجى إدخال تاريخ ميلادك"),
  dobWhy: s("This keeps your information private.", "Esto mantiene su información privada.", "هذا يحافظ على خصوصية معلوماتك."),
  dobHelper: s(
    "If you're helping someone, enter THEIR date of birth.",
    "Si está ayudando a alguien, escriba la fecha de nacimiento de ESA persona.",
    "إذا كنت تساعد شخصًا آخر، أدخل تاريخ ميلاده هو.",
  ),
  month: s("Month", "Mes", "الشهر"),
  day: s("Day", "Día", "اليوم"),
  year: s("Year", "Año", "السنة"),
  continue: s("Continue", "Continuar", "متابعة"),
  dobInvalid: s("Please enter a real date, like 03 / 15 / 1950.", "Escriba una fecha válida, por ejemplo 03 / 15 / 1950.", "يرجى إدخال تاريخ صحيح، مثل 03 / 15 / 1950."),
  dobWrong: s(
    "That date doesn't match our records. Please check it and try again. ({n} tries left)",
    "Esa fecha no coincide con nuestros registros. Revísela e inténtelo de nuevo. (Le quedan {n} intentos)",
    "هذا التاريخ لا يطابق سجلاتنا. يرجى التحقق منه والمحاولة مرة أخرى. (تبقّى {n} محاولات)",
  ),
  hello: s("Hello, {name}!", "¡Hola, {name}!", "مرحبًا {name}!"),
  helloNoName: s("Hello!", "¡Hola!", "مرحبًا!"),
  homeBody: s("Please complete each form below. Tap a form to begin.", "Complete cada formulario. Toque uno para comenzar.", "يرجى إكمال كل نموذج أدناه. اضغط على النموذج للبدء."),
  formDone: s("Done", "Listo", "تم"),
  begin: s("Begin", "Comenzar", "ابدأ"),
  keepGoing: s("Continue", "Continuar", "متابعة"),
  readSign: s("Read and sign", "Leer y firmar", "اقرأ ووقّع"),
  aboutMinutes: s("About {m} minutes", "Unos {m} minutos", "حوالي {m} دقائق"),
  step: s("Step {i} of {n}", "Paso {i} de {n}", "الخطوة {i} من {n}"),
  back: s("Back", "Atrás", "رجوع"),
  next: s("Next", "Siguiente", "التالي"),
  allForms: s("All forms", "Todos los formularios", "كل النماذج"),
  fixBelow: s("Please answer the questions marked in red.", "Por favor conteste las preguntas marcadas en rojo.", "يرجى الإجابة على الأسئلة المميّزة باللون الأحمر."),
  required: s("Please answer this.", "Por favor conteste esto.", "يرجى الإجابة على هذا."),
  invalidPhone: s("Please enter a 10-digit phone number.", "Escriba un número de teléfono de 10 dígitos.", "يرجى إدخال رقم هاتف مكوّن من 10 أرقام."),
  invalidEmail: s("Please check the email address.", "Revise el correo electrónico.", "يرجى التحقق من البريد الإلكتروني."),
  invalidZip: s("Please enter a 5-digit ZIP code.", "Escriba un código postal de 5 dígitos.", "يرجى إدخال رمز بريدي من 5 أرقام."),
  needRow: s("Please add at least one.", "Agregue al menos uno.", "يرجى إضافة واحد على الأقل."),
  addRow: s("+ Add another", "+ Agregar otro", "+ إضافة آخر"),
  removeRow: s("Remove", "Quitar", "حذف"),
  takePhoto: s("Take or choose a photo", "Tomar o elegir una foto", "التقط صورة أو اخترها"),
  retakePhoto: s("Use a different photo", "Usar otra foto", "استخدم صورة أخرى"),
  removePhoto: s("Remove", "Quitar", "حذف"),
  photoSaved: s("Photo saved", "Foto guardada", "تم حفظ الصورة"),
  photoSaving: s("Saving photo…", "Guardando foto…", "جارٍ حفظ الصورة…"),
  photoFailed: s("The photo didn't save. Please try again.", "La foto no se guardó. Inténtelo de nuevo.", "لم يتم حفظ الصورة. يرجى المحاولة مرة أخرى."),
  photoSkip: s("You can skip this and bring your card to your visit.", "Puede omitir esto y traer su tarjeta a su cita.", "يمكنك تخطي هذا وإحضار بطاقتك إلى الموعد."),
  saving: s("Saving…", "Guardando…", "جارٍ الحفظ…"),
  saved: s("Saved", "Guardado", "تم الحفظ"),
  reviewTitle: s("Check your answers", "Revise sus respuestas", "راجع إجاباتك"),
  reviewBody: s("Tap Change to fix anything. Then sign at the bottom.", "Toque Cambiar para corregir algo. Luego firme abajo.", "اضغط على \"تغيير\" لتصحيح أي شيء، ثم وقّع في الأسفل."),
  change: s("Change", "Cambiar", "تغيير"),
  noAnswer: s("(no answer)", "(sin respuesta)", "(بدون إجابة)"),
  photoOnFile: s("Photo added", "Foto agregada", "تمت إضافة صورة"),
  signTitle: s("Sign here", "Firme aquí", "وقّع هنا"),
  whoSigning: s("Who is signing?", "¿Quién firma?", "من يوقّع؟"),
  signMe: s("I am the patient", "Yo soy el paciente", "أنا المريض"),
  signHelper: s("I'm signing for the patient", "Firmo por el paciente", "أوقّع نيابةً عن المريض"),
  helperRelation: s("Your relationship to the patient", "Su relación con el paciente", "صلتك بالمريض"),
  typeName: s("Type your full name", "Escriba su nombre completo", "اكتب اسمك الكامل"),
  typeNameHelper: s("Type YOUR full name (the person signing)", "Escriba SU nombre completo (quien firma)", "اكتب اسمك أنت الكامل (الشخص الذي يوقّع)"),
  drawInstead: s("Draw my signature instead", "Prefiero dibujar mi firma", "أفضّل رسم توقيعي"),
  typeInstead: s("Type my name instead", "Prefiero escribir mi nombre", "أفضّل كتابة اسمي"),
  drawHere: s("Sign in the box with your finger or mouse", "Firme en el cuadro con el dedo o el ratón", "وقّع داخل المربع بإصبعك أو بالفأرة"),
  clear: s("Clear", "Borrar", "مسح"),
  sign: s("Sign", "Firmar", "توقيع"),
  signing: s("Signing…", "Firmando…", "جارٍ التوقيع…"),
  agreeRead: s("I have read and agree to this form.", "He leído y acepto este formulario.", "لقد قرأت هذا النموذج وأوافق عليه."),
  needConsent: s("Please tap the box to agree.", "Toque la casilla para aceptar.", "يرجى الضغط على المربع للموافقة."),
  needName: s("Please type your full name.", "Escriba su nombre completo.", "يرجى كتابة اسمك الكامل."),
  needRelation: s("Please choose your relationship to the patient.", "Elija su relación con el paciente.", "يرجى اختيار صلتك بالمريض."),
  needDrawing: s("Please sign in the box.", "Firme dentro del cuadro.", "يرجى التوقيع داخل المربع."),
  readAloud: s("Read it to me", "Léamelo en voz alta", "اقرأه لي"),
  stopReading: s("Stop reading", "Dejar de leer", "إيقاف القراءة"),
  englishOnly: s(
    "This form is only in English right now. Call us if you'd like help with it.",
    "Este formulario solo está en inglés por ahora. Llámenos si necesita ayuda.",
    "هذا النموذج متوفر باللغة الإنجليزية فقط حاليًا. اتصل بنا إذا كنت بحاجة إلى مساعدة.",
  ),
  changedNote: s("This form was just updated. Please read it again, then sign.", "Este formulario se acaba de actualizar. Léalo de nuevo y luego firme.", "تم تحديث هذا النموذج للتو. يرجى قراءته مرة أخرى ثم التوقيع."),
  incompleteNote: s("A few questions still need answers.", "Todavía faltan algunas respuestas.", "لا تزال بعض الأسئلة بحاجة إلى إجابة."),
  doneTitle: s("All done. Thank you!", "¡Listo! Muchas gracias.", "تم كل شيء. شكرًا لك!"),
  doneBody: s("We received your forms. We'll see you at your visit.", "Recibimos sus formularios. Le esperamos en su cita.", "لقد استلمنا نماذجك. نراك في موعدك."),
  doneClose: s("You can close this page now.", "Ya puede cerrar esta página.", "يمكنك الآن إغلاق هذه الصفحة."),
  callUs: s("Call us", "Llámenos", "اتصل بنا"),
  textSize: s("Text size", "Tamaño de letra", "حجم الخط"),
  tryAgain: s("Something went wrong. Please try again.", "Algo salió mal. Inténtelo de nuevo.", "حدث خطأ ما. يرجى المحاولة مرة أخرى."),
  slowDown: s("Please wait a few minutes and try again.", "Espere unos minutos e inténtelo de nuevo.", "يرجى الانتظار بضع دقائق ثم المحاولة مرة أخرى."),
  sessionEnded: s("For your privacy, please enter your date of birth again.", "Por su privacidad, escriba de nuevo su fecha de nacimiento.", "حفاظًا على خصوصيتك، يرجى إدخال تاريخ ميلادك مرة أخرى."),
  loading: s("Loading…", "Cargando…", "جارٍ التحميل…"),
  blocked: {
    not_found: [s("This link doesn't work", "Este enlace no funciona", "هذا الرابط لا يعمل"), s("Please check the link, or call us and we'll send you a new one.", "Revise el enlace, o llámenos y le enviaremos uno nuevo.", "يرجى التحقق من الرابط، أو اتصل بنا وسنرسل لك رابطًا جديدًا.")],
    expired: [s("This link has expired", "Este enlace ya venció", "انتهت صلاحية هذا الرابط"), s("Call us and we'll send you a new one.", "Llámenos y le enviaremos uno nuevo.", "اتصل بنا وسنرسل لك رابطًا جديدًا.")],
    cancelled: [s("These forms are no longer needed", "Ya no necesita estos formularios", "لم تعد هذه النماذج مطلوبة"), s("If you have questions, please call us.", "Si tiene preguntas, llámenos.", "إذا كانت لديك أسئلة، يرجى الاتصال بنا.")],
    done: [s("You already finished these forms", "Ya terminó estos formularios", "لقد أكملت هذه النماذج بالفعل"), s("Thank you! There's nothing else to do.", "¡Gracias! No tiene que hacer nada más.", "شكرًا لك! لا يوجد شيء آخر عليك فعله.")],
    locked: [s("Too many tries", "Demasiados intentos", "محاولات كثيرة جدًا"), s("For your safety, this link is paused for 30 minutes. Please try again later, or call us.", "Por su seguridad, este enlace está en pausa por 30 minutos. Inténtelo más tarde o llámenos.", "حفاظًا على أمانك، تم إيقاف هذا الرابط مؤقتًا لمدة 30 دقيقة. يرجى المحاولة لاحقًا أو الاتصال بنا.")],
  } as Record<string, [S, S]>,
};

export function t(v: S, lang: IntakeLang, vars: Record<string, string | number> = {}) {
  return Object.entries(vars).reduce((acc, [k, x]) => acc.replaceAll(`{${k}}`, String(x)), v[lang] || v.en);
}
