// Words on the patient forms page, in English, Spanish and Arabic. Plain, short sentences:
// many of our patients are older and not used to filling things in online.
import type { IntakeLang } from "@shared/intake";

type S = Record<IntakeLang, string>;
const s = (en: string, es: string, ar: string): S => ({ en, es, ar });

export const T = {
  brand: s("MyPCP Dr", "MyPCP Dr", "MyPCP Dr"),
  yourForms: s("Your forms", "Sus formularios", "النماذج الخاصة بك"),
  chooseLanguage: s("Choose your language", "Elija su idioma", "اختر لغتك"),
  intro: s(
    "Please fill out your forms before your visit. It takes about {m} minutes.",
    "Por favor llene sus formularios antes de su cita. Toma unos {m} minutos.",
    "يرجى تعبئة النماذج قبل موعدك. يستغرق ذلك حوالي {m} دقائق.",
  ),
  saveNote: s(
    "Your answers save as you go. You can stop and come back later with the same link.",
    "Sus respuestas se guardan solas. Puede parar y regresar después con el mismo enlace.",
    "تُحفظ إجاباتك تلقائيًا. يمكنك التوقف والعودة لاحقًا باستخدام نفس الرابط.",
  ),
  helpNote: s(
    "A family member or caregiver can help you fill this out.",
    "Un familiar o cuidador puede ayudarle a llenarlo.",
    "يمكن لأحد أفراد العائلة أو مقدّم الرعاية مساعدتك في تعبئته.",
  ),
  privacy: s("Private and secure. Only our clinic sees your answers.", "Privado y seguro. Solo nuestra clínica ve sus respuestas.", "خاص وآمن. عيادتنا فقط تطّلع على إجاباتك."),
  start: s("Start", "Comenzar", "ابدأ"),
  dobTitle: s("First, please enter your date of birth", "Primero, escriba su fecha de nacimiento", "أولاً، يرجى إدخال تاريخ ميلادك"),
  dobWhy: s("This keeps your information private.", "Esto mantiene su información privada.", "هذا يحافظ على خصوصية معلوماتك."),
  dobHelper: s(
    "If you're helping someone, enter THEIR date of birth.",
    "Si está ayudando a alguien, escriba la fecha de nacimiento de ESA persona.",
    "إذا كنت تساعد شخصًا آخر، أدخل تاريخ ميلاده هو.",
  ),
  month: s("Month", "Mes", "الشهر"),
  day: s("Day", "Día", "اليوم"),
  year: s("Year", "Año", "السنة"),
  continue: s("Continue", "Continuar", "متابعة"),
  dobInvalid: s("Please enter a real date, like 03 / 15 / 1950.", "Escriba una fecha válida, por ejemplo 03 / 15 / 1950.", "يرجى إدخال تاريخ صحيح، مثل 03 / 15 / 1950."),
  dobWrong: s(
    "That date doesn't match our records. Please check it and try again. ({n} tries left)",
    "Esa fecha no coincide con nuestros registros. Revísela e inténtelo de nuevo. (Le quedan {n} intentos)",
    "هذا التاريخ لا يطابق سجلاتنا. يرجى التحقق منه والمحاولة مرة أخرى. (تبقّى {n} محاولات)",
  ),
  hello: s("Hello, {name}!", "¡Hola, {name}!", "مرحبًا {name}!"),
  helloNoName: s("Hello!", "¡Hola!", "مرحبًا!"),
  homeBody: s("Please complete each form below. Tap a form to begin.", "Complete cada formulario. Toque uno para comenzar.", "يرجى إكمال كل نموذج أدناه. اضغط على النموذج للبدء."),
  formDone: s("Done", "Listo", "تم"),
  begin: s("Begin", "Comenzar", "ابدأ"),
  keepGoing: s("Continue", "Continuar", "متابعة"),
  readSign: s("Read and sign", "Leer y firmar", "اقرأ ووقّع"),
  aboutMinutes: s("About {m} minutes", "Unos {m} minutos", "حوالي {m} دقائق"),
  step: s("Step {i} of {n}", "Paso {i} de {n}", "الخطوة {i} من {n}"),
  back: s("Back", "Atrás", "رجوع"),
  next: s("Next", "Siguiente", "التالي"),
  allForms: s("All forms", "Todos los formularios", "كل النماذج"),
  fixBelow: s("Please answer the questions marked in red.", "Por favor conteste las preguntas marcadas en rojo.", "يرجى الإجابة على الأسئلة المميّزة باللون الأحمر."),
  required: s("Please answer this.", "Por favor conteste esto.", "يرجى الإجابة على هذا."),
  invalidPhone: s("Please enter a 10-digit phone number.", "Escriba un número de teléfono de 10 dígitos.", "يرجى إدخال رقم هاتف مكوّن من 10 أرقام."),
  invalidEmail: s("Please check the email address.", "Revise el correo electrónico.", "يرجى التحقق من البريد الإلكتروني."),
  invalidZip: s("Please enter a 5-digit ZIP code.", "Escriba un código postal de 5 dígitos.", "يرجى إدخال رمز بريدي من 5 أرقام."),
  needRow: s("Please add at least one.", "Agregue al menos uno.", "يرجى إضافة واحد على الأقل."),
  addRow: s("+ Add another", "+ Agregar otro", "+ إضافة آخر"),
  removeRow: s("Remove", "Quitar", "حذف"),
  takePhoto: s("Take or choose a photo", "Tomar o elegir una foto", "التقط صورة أو اخترها"),
  retakePhoto: s("Use a different photo", "Usar otra foto", "استخدم صورة أخرى"),
  removePhoto: s("Remove", "Quitar", "حذف"),
  photoSaved: s("Photo saved", "Foto guardada", "تم حفظ الصورة"),
  photoSaving: s("Saving photo…", "Guardando foto…", "جارٍ حفظ الصورة…"),
  photoFailed: s("The photo didn't save. Please try again.", "La foto no se guardó. Inténtelo de nuevo.", "لم يتم حفظ الصورة. يرجى المحاولة مرة أخرى."),
  photoSkip: s("You can skip this and bring your card to your visit.", "Puede omitir esto y traer su tarjeta a su cita.", "يمكنك تخطي هذا وإحضار بطاقتك إلى الموعد."),
  saving: s("Saving…", "Guardando…", "جارٍ الحفظ…"),
  saved: s("Saved", "Guardado", "تم الحفظ"),
  reviewTitle: s("Check your answers", "Revise sus respuestas", "راجع إجاباتك"),
  reviewBody: s("Tap Change to fix anything. Then sign at the bottom.", "Toque Cambiar para corregir algo. Luego firme abajo.", "اضغط على \"تغيير\" لتصحيح أي شيء، ثم وقّع في الأسفل."),
  change: s("Change", "Cambiar", "تغيير"),
  noAnswer: s("(no answer)", "(sin respuesta)", "(بدون إجابة)"),
  photoOnFile: s("Photo added", "Foto agregada", "تمت إضافة صورة"),
  signTitle: s("Sign here", "Firme aquí", "وقّع هنا"),
  whoSigning: s("Who is signing?", "¿Quién firma?", "من يوقّع؟"),
  signMe: s("I am the patient", "Yo soy el paciente", "أنا المريض"),
  signHelper: s("I'm signing for the patient", "Firmo por el paciente", "أوقّع نيابةً عن المريض"),
  helperRelation: s("Your relationship to the patient", "Su relación con el paciente", "صلتك بالمريض"),
  typeName: s("Type your full name", "Escriba su nombre completo", "اكتب اسمك الكامل"),
  typeNameHelper: s("Type YOUR full name (the person signing)", "Escriba SU nombre completo (quien firma)", "اكتب اسمك أنت الكامل (الشخص الذي يوقّع)"),
  drawInstead: s("Draw my signature instead", "Prefiero dibujar mi firma", "أفضّل رسم توقيعي"),
  typeInstead: s("Type my name instead", "Prefiero escribir mi nombre", "أفضّل كتابة اسمي"),
  drawHere: s("Sign in the box with your finger or mouse", "Firme en el cuadro con el dedo o el ratón", "وقّع داخل المربع بإصبعك أو بالفأرة"),
  clear: s("Clear", "Borrar", "مسح"),
  sign: s("Sign", "Firmar", "توقيع"),
  signing: s("Signing…", "Firmando…", "جارٍ التوقيع…"),
  agreeRead: s("I have read and agree to this form.", "He leído y acepto este formulario.", "لقد قرأت هذا النموذج وأوافق عليه."),
  needConsent: s("Please tap the box to agree.", "Toque la casilla para aceptar.", "يرجى الضغط على المربع للموافقة."),
  needName: s("Please type your full name.", "Escriba su nombre completo.", "يرجى كتابة اسمك الكامل."),
  needRelation: s("Please choose your relationship to the patient.", "Elija su relación con el paciente.", "يرجى اختيار صلتك بالمريض."),
  needDrawing: s("Please sign in the box.", "Firme dentro del cuadro.", "يرجى التوقيع داخل المربع."),
  readAloud: s("Read it to me", "Léamelo en voz alta", "اقرأه لي"),
  stopReading: s("Stop reading", "Dejar de leer", "إيقاف القراءة"),
  englishOnly: s(
    "This form is only in English right now. Call us if you'd like help with it.",
    "Este formulario solo está en inglés por ahora. Llámenos si necesita ayuda.",
    "هذا النموذج متوفر باللغة الإنجليزية فقط حاليًا. اتصل بنا إذا كنت بحاجة إلى مساعدة.",
  ),
  changedNote: s("This form was just updated. Please read it again, then sign.", "Este formulario se acaba de actualizar. Léalo de nuevo y luego firme.", "تم تحديث هذا النموذج للتو. يرجى قراءته مرة أخرى ثم التوقيع."),
  incompleteNote: s("A few questions still need answers.", "Todavía faltan algunas respuestas.", "لا تزال بعض الأسئلة بحاجة إلى إجابة."),
  doneTitle: s("All done. Thank you!", "¡Listo! Muchas gracias.", "تم كل شيء. شكرًا لك!"),
  doneBody: s("We received your forms. We'll see you at your visit.", "Recibimos sus formularios. Le esperamos en su cita.", "لقد استلمنا نماذجك. نراك في موعدك."),
  doneClose: s("You can close this page now.", "Ya puede cerrar esta página.", "يمكنك الآن إغلاق هذه الصفحة."),
  callUs: s("Call us", "Llámenos", "اتصل بنا"),
  textSize: s("Text size", "Tamaño de letra", "حجم الخط"),
  tryAgain: s("Something went wrong. Please try again.", "Algo salió mal. Inténtelo de nuevo.", "حدث خطأ ما. يرجى المحاولة مرة أخرى."),
  slowDown: s("Please wait a few minutes and try again.", "Espere unos minutos e inténtelo de nuevo.", "يرجى الانتظار بضع دقائق ثم المحاولة مرة أخرى."),
  sessionEnded: s("For your privacy, please enter your date of birth again.", "Por su privacidad, escriba de nuevo su fecha de nacimiento.", "حفاظًا على خصوصيتك، يرجى إدخال تاريخ ميلادك مرة أخرى."),
  loading: s("Loading…", "Cargando…", "جارٍ التحميل…"),

  // The patient's copy
  seeCopy: s("See or save my copy", "Ver o guardar mi copia", "عرض نسختي أو حفظها"),
  copyTitle: s("Your copy", "Su copia", "نسختك"),
  copyIntro: s("This is what you signed. Keep it for your records.", "Esto es lo que firmó. Guárdelo para su archivo.", "هذا ما وقّعت عليه. احتفظ به في سجلاتك."),
  savePrint: s("Save or print", "Guardar o imprimir", "حفظ أو طباعة"),
  savePrintHow: s(
    "On a phone: tap Save or print, then choose Save as PDF (or Share).",
    "En el teléfono: toque Guardar o imprimir y elija Guardar como PDF (o Compartir).",
    "على الهاتف: اضغط \"حفظ أو طباعة\" ثم اختر الحفظ كملف PDF (أو المشاركة).",
  ),
  copyDobTitle: s("To see your copy, enter your date of birth", "Para ver su copia, escriba su fecha de nacimiento", "لعرض نسختك، أدخل تاريخ ميلادك"),
  copyFailed: s("We couldn't open your copy. Please call us and we'll send it to you.", "No pudimos abrir su copia. Llámenos y se la enviaremos.", "تعذّر فتح نسختك. يرجى الاتصال بنا وسنرسلها إليك."),
  signedBy: s("Signed by {name}", "Firmado por {name}", "وقّع: {name}"),
  answeredBy: s("Answered by {name}", "Contestado por {name}", "أجاب: {name}"),
  forThePatient: s("for the patient", "por el paciente", "نيابةً عن المريض"),
  signedOn: s("Date: {date}", "Fecha: {date}", "التاريخ: {date}"),
  yourAnswerNo: s("Your answer: No, I do not agree.", "Su respuesta: No, no acepto.", "إجابتك: لا، لا أوافق."),
  docCode: s("Document code", "Código del documento", "رمز المستند"),
  photoAdded: s("Photo added", "Foto agregada", "تمت إضافة صورة"),

  // Saying no to a consent
  declineButton: s("No, I do not agree", "No, no acepto", "لا، لا أوافق"),
  declineAsk: s("Don't want to agree?", "¿No desea aceptar?", "لا ترغب في الموافقة؟"),
  declineTitle: s("You're choosing not to agree", "Está eligiendo no aceptar", "أنت تختار عدم الموافقة"),
  declineBody: s(
    "That's okay. Your regular care won't change. You can change your mind any time by calling us.",
    "Está bien. Su atención médica regular no cambia. Puede cambiar de opinión cuando quiera llamándonos.",
    "لا بأس. لن تتغيّر رعايتك المعتادة. يمكنك تغيير رأيك في أي وقت بالاتصال بنا.",
  ),
  declineConfirm: s("Save my answer: No", "Guardar mi respuesta: No", "احفظ إجابتي: لا"),
  changeMind: s("Go back, I want to sign", "Regresar, quiero firmar", "رجوع، أريد التوقيع"),
  youSaidNo: s("You said no", "Usted dijo que no", "اخترت: لا"),

  // Yes/No program questions inside a form
  yourChoices: s("Your choices", "Sus decisiones", "اختياراتك"),
  yourChoicesHelp: s(
    "Please answer Yes or No for each one. Saying No does not change your regular care.",
    "Conteste Sí o No para cada uno. Decir que No no cambia su atención médica regular.",
    "يرجى الإجابة بنعم أو لا لكل واحد. الإجابة بلا لا تغيّر رعايتك المعتادة.",
  ),
  choiceYes: s("Yes, I agree", "Sí, acepto", "نعم، أوافق"),
  choiceNo: s("No, thank you", "No, gracias", "لا، شكرًا"),
  needChoices: s("Please answer Yes or No for each question above.", "Conteste Sí o No en cada pregunta de arriba.", "يرجى الإجابة بنعم أو لا على كل سؤال أعلاه."),
  answerYes: s("Yes", "Sí", "نعم"),
  answerNo: s("No", "No", "لا"),
  moreInfo: s("What this means", "Qué significa", "ماذا يعني هذا"),

  // Someone answering for the patient
  authorityQ: s("Do you have the legal right to sign for the patient?", "¿Tiene el derecho legal de firmar por el paciente?", "هل لديك الحق القانوني في التوقيع نيابةً عن المريض؟"),
  authorityNone: s("No", "No", "لا"),
  authorityNoneNote: s(
    "Only the patient or someone with legal authority can sign this form. Please have the patient sign it. You can still help them read it and tap the buttons.",
    "Solo el paciente o alguien con autoridad legal puede firmar este formulario. Pida al paciente que lo firme. Usted puede ayudarle a leerlo y a tocar los botones.",
    "لا يمكن توقيع هذا النموذج إلا من المريض نفسه أو من شخص لديه صلاحية قانونية. يرجى أن يوقّعه المريض، ويمكنك مساعدته في القراءة والضغط على الأزرار.",
  ),
  authorityExplain: s("Please explain", "Explique por favor", "يرجى التوضيح"),
  needAuthority: s("Please answer: do you have the legal right to sign?", "Conteste: ¿tiene el derecho legal de firmar?", "يرجى الإجابة: هل لديك الحق القانوني في التوقيع؟"),
  needAuthorityNote: s("Please explain your legal authority.", "Explique su autoridad legal.", "يرجى توضيح صلاحيتك القانونية."),

  // Open website link
  publicIntro: s("Please tell us who the patient is. Then read the form and sign.", "Díganos quién es el paciente. Luego lea el formulario y firme.", "يرجى إخبارنا بمن هو المريض، ثم اقرأ النموذج ووقّع."),
  aboutPatient: s("About the patient", "Sobre el paciente", "معلومات عن المريض"),
  aboutPatientHelp: s("If you're helping someone, enter THEIR information.", "Si está ayudando a alguien, escriba la información de ESA persona.", "إذا كنت تساعد شخصًا آخر، أدخل معلوماته هو."),
  firstName: s("First name", "Nombre", "الاسم الأول"),
  lastName: s("Last name", "Apellido", "اسم العائلة"),
  dobLabel: s("Date of birth", "Fecha de nacimiento", "تاريخ الميلاد"),
  phoneLabel: s("Phone number", "Número de teléfono", "رقم الهاتف"),
  emailLabel: s("Email (optional)", "Correo electrónico (opcional)", "البريد الإلكتروني (اختياري)"),
  officeLabel: s("Which office do you go to?", "¿A qué clínica va?", "أي عيادة تزورها؟"),
  officeNotSure: s("Not sure / new patient", "No sé / paciente nuevo", "لست متأكدًا / مريض جديد"),
  needFirstLast: s("Please enter the first and last name.", "Escriba el nombre y el apellido.", "يرجى إدخال الاسم الأول واسم العائلة."),
  publicDoneBody: s("We received your form.", "Recibimos su formulario.", "لقد استلمنا النموذج."),
  startOver: s("This page timed out. Please start again.", "Esta página se venció. Empiece de nuevo.", "انتهت مهلة هذه الصفحة. يرجى البدء من جديد."),
  blocked: {
    not_found: [s("This link doesn't work", "Este enlace no funciona", "هذا الرابط لا يعمل"), s("Please check the link, or call us and we'll send you a new one.", "Revise el enlace, o llámenos y le enviaremos uno nuevo.", "يرجى التحقق من الرابط، أو اتصل بنا وسنرسل لك رابطًا جديدًا.")],
    expired: [s("This link has expired", "Este enlace ya venció", "انتهت صلاحية هذا الرابط"), s("Call us and we'll send you a new one.", "Llámenos y le enviaremos uno nuevo.", "اتصل بنا وسنرسل لك رابطًا جديدًا.")],
    cancelled: [s("These forms are no longer needed", "Ya no necesita estos formularios", "لم تعد هذه النماذج مطلوبة"), s("If you have questions, please call us.", "Si tiene preguntas, llámenos.", "إذا كانت لديك أسئلة، يرجى الاتصال بنا.")],
    done: [s("You already finished these forms", "Ya terminó estos formularios", "لقد أكملت هذه النماذج بالفعل"), s("Thank you! There's nothing else to do.", "¡Gracias! No tiene que hacer nada más.", "شكرًا لك! لا يوجد شيء آخر عليك فعله.")],
    locked: [s("Too many tries", "Demasiados intentos", "محاولات كثيرة جدًا"), s("For your safety, this link is paused for 30 minutes. Please try again later, or call us.", "Por su seguridad, este enlace está en pausa por 30 minutos. Inténtelo más tarde o llámenos.", "حفاظًا على أمانك، تم إيقاف هذا الرابط مؤقتًا لمدة 30 دقيقة. يرجى المحاولة لاحقًا أو الاتصال بنا.")],
  } as Record<string, [S, S]>,
};

export function t(v: S, lang: IntakeLang, vars: Record<string, string | number> = {}) {
  return Object.entries(vars).reduce((acc, [k, x]) => acc.replaceAll(`{${k}}`, String(x)), v[lang] || v.en);
}
