// Condition library, group D: behavioral health (depression, anxiety, PTSD, bipolar/psychotic, substance use),
// cancer and HIV. DRAFT content: a provider reviews and approves each entry in MyPCP before patients see it.
import type { ConditionLibraryEntry } from "./types";

export const GROUP_D: ConditionLibraryEntry[] = [
  // ---------------------------------------------------------------------------------------------------------
  {
    key: "depression",
    education: {
      en: {
        title: "Living with depression",
        whatItIs: "Depression is a common health condition that affects your mood, your thoughts and your body. It is more than a few sad days. It can leave you feeling down, tired or hopeless for weeks, and make it hard to enjoy things you used to like.",
        whyItMatters: "Without treatment, depression can make it harder to sleep, eat well, take your medicines and manage other conditions like diabetes or heart disease. The good news is that depression is treatable, and most people feel better with the right care.",
        whatYouCanDo: [
          "Do one small thing you enjoy, or that matters to you, each day, even if you don't feel like it at first.",
          "Move your body every day. A short walk counts.",
          "Go to bed and get up at about the same time each day.",
          "Stay in touch with people you trust. Call, text or visit someone this week.",
          "Avoid alcohol and drugs. They can make depression worse and get in the way of your medicines.",
          "Break big tasks into small steps, and give yourself credit for each one.",
          "Keep your appointments and check-in calls, even on hard days. That is when they help the most.",
        ],
        numbers: [
          "Mood check-in (PHQ-9): each month we ask you a few short questions about the last 2 weeks. Your score goes from 0 to 27, and lower is better. The goal is a score under 5, or the goal your provider sets for you.",
          "Progress: in the first 2 to 3 months of treatment, we hope to see your score drop by about half, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicine every day, just as prescribed.",
          "It can take 4 to 8 weeks to feel the full effect. Keep taking it, even if you don't feel better right away.",
          "Don't stop your medicine on your own, even when you feel better. Stopping too soon can bring depression back. Talk with us first.",
          "Don't drink alcohol with these medicines. If side effects bother you, tell us. There are often other choices.",
        ],
        callUs: [
          "Your mood is getting worse, or you don't feel better after several weeks of treatment.",
          "You feel very restless, agitated or not like yourself after starting or changing a medicine.",
          "Side effects are bothering you, or you are thinking about stopping your medicine.",
          "You can't sleep, eat or take care of daily tasks most days.",
          "You can't get or pay for your medicine, or you need a ride to your appointments.",
        ],
        call911: [
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
          "If you have a plan to hurt yourself, have already done something to hurt yourself, or someone is in danger right now, call 911 or go to the nearest emergency room.",
          "If you are worried about a loved one, you can call 988 too. They will help you know what to do.",
        ],
      },
      es: {
        title: "Cómo vivir con depresión",
        whatItIs: "La depresión es una condición de salud común que afecta su estado de ánimo, sus pensamientos y su cuerpo. Es mucho más que estar triste unos días. Puede quitarle las ganas y la energía durante semanas, hacerle sentir sin esperanza y hacer que ya no disfrute lo que antes le gustaba.",
        whyItMatters: "Sin tratamiento, la depresión puede hacer más difícil dormir, comer bien, tomar sus medicinas y controlar otras condiciones como la diabetes o las enfermedades del corazón. La buena noticia es que la depresión tiene tratamiento, y la mayoría de las personas se sienten mejor con la atención adecuada.",
        whatYouCanDo: [
          "Haga cada día algo pequeño que disfrute o que sea importante para usted, aunque al principio no tenga ganas.",
          "Mueva el cuerpo todos los días. Una caminata corta cuenta.",
          "Acuéstese y levántese más o menos a la misma hora todos los días.",
          "Manténgase en contacto con personas de confianza. Llame, escriba o visite a alguien esta semana.",
          "Evite el alcohol y las drogas. Pueden empeorar la depresión e interferir con sus medicinas.",
          "Divida las tareas grandes en pasos pequeños y reconozca cada logro, por pequeño que sea.",
          "No falte a sus citas ni a las llamadas de seguimiento, aun en los días difíciles. Es justo cuando más ayudan.",
        ],
        numbers: [
          "Chequeo del estado de ánimo (PHQ-9): cada mes le hacemos unas preguntas cortas sobre las últimas 2 semanas. El puntaje va de 0 a 27 y, mientras más bajo, mejor. La meta es un puntaje menor de 5, o la meta que su proveedor le indique.",
          "Avance: en los primeros 2 a 3 meses de tratamiento, esperamos que su puntaje baje más o menos a la mitad, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome su medicina todos los días, tal como se la recetaron.",
          "El efecto completo puede tardar de 4 a 8 semanas. Siga tomándola aunque no se sienta mejor enseguida.",
          "No deje la medicina por su cuenta, aunque ya se sienta bien. Si la deja antes de tiempo, la depresión puede regresar. Hable con nosotros primero.",
          "No tome alcohol con estas medicinas. Si tiene efectos secundarios que le molestan, díganos. Casi siempre hay otras opciones.",
        ],
        callUs: [
          "Su ánimo empeora o no mejora después de varias semanas de tratamiento.",
          "Siente mucha inquietud o agitación, o no se siente como siempre, después de empezar o cambiar una medicina.",
          "Los efectos secundarios le molestan o está pensando en dejar la medicina.",
          "La mayoría de los días no puede dormir, comer ni hacer sus tareas diarias.",
          "No puede conseguir o pagar su medicina, o necesita transporte para llegar a sus citas.",
        ],
        call911: [
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
          "Si tiene un plan para hacerse daño, ya hizo algo para lastimarse o alguien corre peligro en este momento, llame al 911 o vaya a la sala de emergencias más cercana.",
          "Si le preocupa un ser querido, también puede llamar al 988. Ahí le ayudarán a saber qué hacer.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Depression is a common, treatable medical condition, not a weakness or a character flaw; most people improve with steady care.",
        "Medicines can take 4–8 weeks to work fully; encourage taking them daily and not stopping without talking to the provider.",
        "Small daily actions help: one enjoyable or meaningful activity, a short walk, a regular sleep schedule and contact with someone they trust.",
        "Explain the monthly PHQ-9 check-in: it shows whether treatment is working so the team can adjust it; a lower score is better.",
        "Alcohol and drugs worsen depression and can interact with medicines; encourage avoiding them.",
        "If the patient mentions thoughts of self-harm, follow the practice's safety protocol and alert the provider right away.",
      ],
      ask: [
        "How has your mood been over the past two weeks compared with last month?",
        "How are you sleeping and eating these days?",
        "How is it going with your medicine? Have you missed any doses or noticed side effects?",
        "Who do you talk to or spend time with when you're having a hard day?",
        "Is anything making it hard to keep your appointments or get your medicine?",
      ],
    },
    carePlan: {
      problem: "Major depressive disorder (specify single episode or recurrent, and current severity)",
      expectedOutcome: "With measurement-based collaborative care, the patient is expected to reach treatment response within 10–12 weeks and remission within about 6 months, followed by relapse prevention.",
      goals: [
        "PHQ-9 response: at least a 50% reduction from baseline within 10–12 weeks of starting or changing treatment (or as individualized by the provider)",
        "PHQ-9 remission: score below 5, sustained across consecutive monthly contacts (or as individualized by the provider)",
        "Patient-chosen functional goal (e.g., resume a valued activity, social contact or work) met within 3 months (or as individualized by the provider)",
        "Engagement: at least monthly BHI contact during active treatment with no unplanned gaps in medication or therapy (or as individualized by the provider)",
      ],
      monitoring: [
        "PHQ-9 at each monthly contact (more often after treatment changes), tracked in the BHI registry",
        "Suicide risk: PHQ-9 item 9 reviewed at every administration; any positive response triggers the practice safety protocol and same-day provider review",
        "Medication adherence and side effects at each monthly contact",
        "GAD-7 and AUDIT-C at intake and at least every 6 months for co-occurring anxiety and alcohol use",
        "Screen for a history of mania/hypomania at intake and if activation symptoms appear after a treatment change",
      ],
      interventions: [
        "Measurement-based care with registry tracking; treat to target, with the provider adjusting treatment when PHQ-9 has not improved by at least 50% at 10–12 weeks",
        "Systematic caseload review and psychiatric consultation for patients not improving as expected",
        "Brief evidence-based interventions by the BHI care manager (behavioral activation, problem-solving, motivational interviewing)",
        "Collaborative safety planning and lethal-means counseling for any patient reporting suicidal thoughts",
        "Referral to psychotherapy (e.g., CBT) when indicated or preferred by the patient",
        "Relapse prevention plan once remission is reached (early warning signs, continuation of treatment, follow-up schedule)",
      ],
      selfManagement: [
        "Take medicines daily as prescribed and report side effects instead of stopping",
        "Schedule at least one pleasant or meaningful activity and some physical activity each day",
        "Keep a regular sleep–wake schedule",
        "Avoid alcohol and recreational drugs",
        "Keep 988 and the care team's number handy and use the safety plan if needed",
      ],
      symptomManagement: [
        "Worsening mood or a PHQ-9 rise of 5 or more points: same-week provider review and treatment adjustment",
        "Suicidal thoughts: follow the practice safety protocol with same-day assessment; 988 or 911 as appropriate",
        "New agitation, restlessness or worsening after starting or changing an antidepressant: prompt provider contact",
        "Decreased need for sleep, racing thoughts or unusually elevated mood: urgent provider review for possible bipolar spectrum illness",
      ],
      coordination: [
        "Psychiatric consultant (collaborative care) for treatment recommendations and caseload review",
        "Psychotherapy/counseling services and, for older adults, community programs such as senior centers and support groups",
        "Social services for barriers such as isolation, transportation, housing or cost of care",
      ],
    },
    basis: [
      "APA Practice Guideline for the Treatment of Patients With Major Depressive Disorder",
      "AIMS Center Collaborative Care",
      "VA/DoD Clinical Practice Guideline for the Management of Major Depressive Disorder",
    ],
  },

  // ---------------------------------------------------------------------------------------------------------
  {
    key: "anxiety",
    education: {
      en: {
        title: "Living with anxiety",
        whatItIs: "Everyone feels worried or nervous at times. With an anxiety disorder, the worry or fear is strong, lasts a long time and gets in the way of daily life. It can also cause body feelings like a racing heart, tight muscles, an upset stomach or trouble sleeping.",
        whyItMatters: "Anxiety that is not treated can wear you down, lead to depression and make other health problems harder to manage. The good news is that anxiety is very treatable with talk therapy, skills you can learn and sometimes medicine.",
        whatYouCanDo: [
          "Practice slow breathing: breathe in through your nose while you count to 4, then out through your mouth while you count to 6. Repeat for a few minutes.",
          "Move your body every day. Walking, stretching or dancing all help calm your body.",
          "Cut back on coffee, energy drinks and other caffeine. Avoid alcohol and nicotine, which can make anxiety worse.",
          "Face the things you fear in small steps instead of avoiding them. Each small step builds confidence.",
          "Set aside a short worry time each day. Write your worries down, then put them away until the next day.",
          "Keep a regular sleep schedule and a calm bedtime routine.",
          "Talk with someone you trust about how you feel.",
        ],
        numbers: [
          "Worry check-in (GAD-7): each month we ask you a few short questions about the last 2 weeks. Your score goes from 0 to 21, and lower is better. The goal is a score under 5, or the goal your provider sets for you.",
          "Progress: in the first 2 to 3 months of treatment, we hope to see your score drop by about half, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicine just as prescribed. Daily medicines for anxiety can take several weeks to work fully.",
          "Some medicines for anxiety or sleep can make you drowsy, raise your risk of falling and become habit-forming. Never mix them with alcohol or other medicines that make you sleepy.",
          "Don't stop any medicine suddenly, even if you feel better. Some can cause problems if stopped all at once. Talk with us first.",
          "If side effects bother you, tell us. There are often other choices.",
        ],
        callUs: [
          "Your worry or panic is getting worse, or is not better after several weeks of treatment.",
          "You are avoiding more places, people or activities because of fear.",
          "You feel too sleepy, dizzy or unsteady on your feet, or side effects bother you.",
          "You are using alcohol, drugs or extra medicine to calm your nerves.",
          "You can't sleep most nights, or you are feeling down or hopeless.",
        ],
        call911: [
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
          "Call 911 for chest pain or pressure, trouble breathing, fainting or sudden weakness. Don't assume it is anxiety. These can be signs of a heart attack or another emergency.",
          "Call 911 if you or someone else is in danger right now.",
        ],
      },
      es: {
        title: "Cómo vivir con ansiedad",
        whatItIs: "Todos nos sentimos preocupados o nerviosos a veces. Cuando hay un trastorno de ansiedad, la preocupación o el miedo son fuertes, duran mucho tiempo y no le dejan llevar su vida diaria con normalidad. También puede causar molestias en el cuerpo, como el corazón acelerado, músculos tensos, malestar de estómago o problemas para dormir.",
        whyItMatters: "Si no se trata, la ansiedad puede agotarle, llevar a la depresión y hacer más difícil controlar otros problemas de salud. La buena noticia es que la ansiedad responde muy bien a la terapia, a técnicas que usted puede aprender y, a veces, a la medicina.",
        whatYouCanDo: [
          "Practique la respiración lenta: tome aire por la nariz mientras cuenta hasta 4 y luego suéltelo por la boca mientras cuenta hasta 6. Repita por unos minutos.",
          "Mueva el cuerpo todos los días. Caminar, estirarse o bailar ayudan a calmar el cuerpo.",
          "Tome menos café, bebidas energéticas y otras bebidas con cafeína. Evite el alcohol y la nicotina, que pueden empeorar la ansiedad.",
          "Enfrente poco a poco lo que le da miedo en lugar de evitarlo. Cada pequeño paso le da más confianza.",
          "Dedique un rato corto cada día a sus preocupaciones. Escríbalas y luego déjelas a un lado hasta el día siguiente.",
          "Mantenga un horario fijo para dormir y una rutina tranquila antes de acostarse.",
          "Hable con alguien de confianza sobre cómo se siente.",
        ],
        numbers: [
          "Chequeo de la preocupación (GAD-7): cada mes le hacemos unas preguntas cortas sobre las últimas 2 semanas. El puntaje va de 0 a 21 y, mientras más bajo, mejor. La meta es un puntaje menor de 5, o la meta que su proveedor le indique.",
          "Avance: en los primeros 2 a 3 meses de tratamiento, esperamos que su puntaje baje más o menos a la mitad, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome su medicina tal como se la recetaron. Las medicinas diarias para la ansiedad pueden tardar varias semanas en hacer su efecto completo.",
          "Algunas medicinas para la ansiedad o para dormir pueden dar sueño, aumentar el riesgo de caídas y crear dependencia. Nunca las mezcle con alcohol ni con otras medicinas que den sueño.",
          "No deje ninguna medicina de golpe, aunque se sienta mejor. Algunas pueden causar problemas si se suspenden de repente. Hable con nosotros primero.",
          "Si tiene efectos secundarios que le molestan, díganos. Casi siempre hay otras opciones.",
        ],
        callUs: [
          "Su preocupación o sus ataques de pánico empeoran, o no mejoran después de varias semanas de tratamiento.",
          "Por miedo, está evitando cada vez más lugares, personas o actividades.",
          "Siente demasiado sueño, mareo o inestabilidad al caminar, o los efectos secundarios le molestan.",
          "Está usando alcohol, drogas o más medicina de la indicada para calmar los nervios.",
          "No puede dormir la mayoría de las noches, o se siente sin ánimo o sin esperanza.",
        ],
        call911: [
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
          "Llame al 911 si tiene dolor o presión en el pecho, dificultad para respirar, un desmayo o debilidad repentina. No dé por hecho que es ansiedad: pueden ser señales de un ataque al corazón u otra emergencia.",
          "Llame al 911 si usted u otra persona corre peligro en este momento.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Anxiety disorders are common and very treatable; skills, therapy and sometimes medicine all help.",
        "Reinforce one simple calming skill (slow breathing with a longer breath out) and daily physical activity.",
        "Avoidance keeps fear going; encourage facing feared situations in small, planned steps.",
        "Daily anxiety medicines can take weeks to work; sedating medicines raise fall risk in older adults and should never be mixed with alcohol.",
        "Explain the monthly GAD-7 check-in: it tracks progress so the team can adjust treatment; a lower score is better.",
        "If the patient mentions thoughts of self-harm, follow the practice's safety protocol and alert the provider right away.",
      ],
      ask: [
        "How much has worry or nervousness gotten in the way of your days since we last talked?",
        "How are you sleeping?",
        "How is the breathing exercise or another calming skill working for you?",
        "Are you taking your medicine as prescribed? Any side effects, dizziness or falls?",
        "Is there anything you've been avoiding, or anything that makes it hard to get to your appointments?",
      ],
    },
    carePlan: {
      problem: "Generalized anxiety disorder (or specify: panic disorder, social anxiety disorder, other specified anxiety disorder)",
      expectedOutcome: "With measurement-based collaborative care, the patient is expected to reach a clinically meaningful reduction in anxiety within 8–12 weeks and remission within about 6 months, with improved daily function.",
      goals: [
        "GAD-7 response: at least a 50% reduction from baseline within 8–12 weeks of starting or changing treatment (or as individualized by the provider)",
        "GAD-7 remission: score below 5 (or as individualized by the provider)",
        "Patient-chosen functional goal (e.g., resume an avoided activity, or panic episodes reduced by half from the baseline log) met within 3 months (or as individualized by the provider)",
      ],
      monitoring: [
        "GAD-7 at each monthly contact, tracked in the BHI registry",
        "PHQ-9 at intake and at least every 3 months for co-occurring depression, with item 9 reviewed for suicide risk",
        "Medication adherence, side effects, sedation and falls at each monthly contact (especially age 65 and older)",
        "AUDIT-C at intake and at least annually; review of caffeine, alcohol and sedative use",
        "Review of medical and medication contributors to anxiety (e.g., thyroid disease, stimulants) by the provider at intake and with symptom changes",
      ],
      interventions: [
        "Measurement-based care with registry tracking; the provider adjusts treatment when GAD-7 is not improving by 8–12 weeks",
        "Brief CBT-based interventions by the BHI care manager (psychoeducation, breathing/relaxation, graded exposure, problem-solving)",
        "Psychiatric consultation and caseload review for patients not reaching targets",
        "Referral to CBT or other psychotherapy when indicated or preferred",
        "Medication review for sedating medicines and fall risk in older adults, in coordination with the prescriber",
        "Collaborative safety planning when suicidal thoughts are reported",
      ],
      selfManagement: [
        "Practice a calming skill (slow breathing or relaxation) daily, not only during anxious moments",
        "Limit caffeine and avoid alcohol and nicotine",
        "Approach avoided situations in planned, small steps",
        "Take medicines as prescribed and do not stop or increase them without talking to the provider",
        "Keep a regular sleep schedule and daily physical activity",
      ],
      symptomManagement: [
        "New or changed chest pain, shortness of breath or palpitations: evaluate for medical causes before attributing symptoms to anxiety; 911 if severe",
        "Rising GAD-7 or new avoidance: same-week review, reinforce skills, provider considers a treatment change",
        "Excess sedation, dizziness or a fall: same-day provider contact for medication review",
        "Suicidal thoughts: follow the practice safety protocol; 988 or 911 as appropriate",
      ],
      coordination: [
        "Psychiatric consultant (collaborative care) for treatment recommendations",
        "Psychotherapy/CBT services, including telehealth options",
        "Community resources and social services (support groups, senior programs) for isolation and life stressors",
      ],
    },
    basis: [
      "AIMS Center Collaborative Care",
      "NICE Guideline CG113: Generalised Anxiety Disorder and Panic Disorder in Adults",
      "AGS Beers Criteria (sedating medicines in older adults)",
    ],
  },

  // ---------------------------------------------------------------------------------------------------------
  {
    key: "ptsd",
    education: {
      en: {
        title: "Living with PTSD",
        whatItIs: "PTSD (post-traumatic stress disorder) can happen after you live through or see something very frightening or dangerous, like combat, an assault, a serious accident or a disaster. Your mind and body stay on high alert, even when you are safe. You may have upsetting memories or bad dreams, stay away from reminders, or feel on edge or numb.",
        whyItMatters: "PTSD can affect your sleep, relationships, work and physical health, and it raises the risk of depression and alcohol or drug use. PTSD is not a sign of weakness, and it can get better with treatment, even many years after the event.",
        whatYouCanDo: [
          "When a memory hits, bring yourself back to the present: name 5 things you can see and 4 things you can hear, and feel your feet on the floor.",
          "Practice slow breathing a few times a day, letting each breath out be longer than the breath in.",
          "Learn what sets off your symptoms, and make a plan with your care team for how to handle those moments.",
          "Keep a regular sleep routine. Tell us about nightmares; there is help for them.",
          "Stay connected with people you trust, or join a support group.",
          "Avoid using alcohol or drugs to numb your feelings. Over time, they make PTSD worse.",
          "Keep your therapy appointments. Therapy that focuses on the trauma is one of the best treatments for PTSD.",
        ],
        numbers: [
          "Stress check-in (PCL-5): 20 short questions about how much PTSD has bothered you in the past month. Your score goes from 0 to 80, and lower is better. The goal is for your score to keep going down; a drop of 10 points or more is real progress, or the goal your provider sets for you.",
          "Mood check-in (PHQ-9), if we also check your mood: lower is better, with a goal under 5, or the goal your provider sets for you.",
        ],
        medicines: [
          "Medicine can help with some PTSD symptoms, like worry, low mood or poor sleep. Take it just as prescribed; it can take several weeks to work.",
          "Don't stop your medicine on your own. Talk with us first.",
          "Don't drink alcohol or use drugs with your medicines. Tell us about side effects; there are often other choices.",
        ],
        callUs: [
          "You are having more bad dreams, upsetting memories or moments when it feels like the event is happening again.",
          "You are using alcohol or drugs to cope, or using more than before.",
          "You can't sleep most nights, or you feel down, numb or cut off from others.",
          "You don't feel safe at home, or someone is hurting or threatening you.",
          "Side effects bother you, or you are having trouble getting to therapy.",
        ],
        call911: [
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
          "If you served in the military, you can call 988 and press 1 to reach the Veterans Crisis Line.",
          "Call 911 if you or someone else is in danger right now.",
        ],
      },
      es: {
        title: "Cómo vivir con el trastorno de estrés postraumático (TEPT)",
        whatItIs: "El trastorno de estrés postraumático (TEPT, o PTSD por sus siglas en inglés) puede aparecer después de vivir o presenciar algo muy aterrador o peligroso, como una guerra, una agresión, un accidente grave o un desastre. Su mente y su cuerpo se quedan en estado de alerta, aun cuando usted ya está a salvo. Puede tener recuerdos que le perturban o pesadillas, evitar todo lo que le recuerde lo que pasó, o sentir tensión constante o como si no sintiera nada.",
        whyItMatters: "El TEPT puede afectar el sueño, las relaciones, el trabajo y la salud física, y aumenta el riesgo de depresión y de consumo de alcohol o drogas. No es una señal de debilidad, y puede mejorar con tratamiento, incluso muchos años después de lo ocurrido.",
        whatYouCanDo: [
          "Cuando le llegue un recuerdo, vuelva al presente: nombre 5 cosas que ve y 4 cosas que oye, y sienta sus pies en el piso.",
          "Practique la respiración lenta varias veces al día, soltando el aire más despacio de lo que lo toma.",
          "Identifique qué le provoca los síntomas y haga un plan con su equipo de atención para manejar esos momentos.",
          "Mantenga una rutina fija para dormir. Cuéntenos si tiene pesadillas; hay ayuda para eso.",
          "Manténgase en contacto con personas de confianza o únase a un grupo de apoyo.",
          "No use el alcohol ni las drogas para adormecer lo que siente. Con el tiempo, empeoran el TEPT.",
          "No falte a sus citas de terapia. La terapia enfocada en el trauma es uno de los mejores tratamientos para el TEPT.",
        ],
        numbers: [
          "Chequeo del estrés (PCL-5): 20 preguntas cortas sobre cuánto le ha molestado el TEPT en el último mes. El puntaje va de 0 a 80 y, mientras más bajo, mejor. La meta es que el puntaje siga bajando; una baja de 10 puntos o más es un avance real, o la meta que su proveedor le indique.",
          "Chequeo del estado de ánimo (PHQ-9), si también revisamos su ánimo: mientras más bajo, mejor, con una meta menor de 5, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "La medicina puede ayudar con algunos síntomas del TEPT, como la preocupación, el ánimo bajo o el mal dormir. Tómela tal como se la recetaron; puede tardar varias semanas en hacer efecto.",
          "No deje la medicina por su cuenta. Hable con nosotros primero.",
          "No tome alcohol ni use drogas con sus medicinas. Cuéntenos si tiene efectos secundarios; casi siempre hay otras opciones.",
        ],
        callUs: [
          "Tiene más pesadillas, más recuerdos que le perturban o momentos en que siente que lo ocurrido está pasando otra vez.",
          "Está usando alcohol o drogas para sobrellevarlo, o los está usando más que antes.",
          "No puede dormir la mayoría de las noches, o siente que no tiene ánimo, que no siente nada o que está lejos de los demás.",
          "No se siente a salvo en su casa, o alguien le hace daño o le amenaza.",
          "Los efectos secundarios le molestan, o tiene problemas para ir a terapia.",
        ],
        call911: [
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
          "Si usted sirvió en las fuerzas armadas, puede llamar al 988 y marcar 1 para hablar con la Línea de Crisis para Veteranos.",
          "Llame al 911 si usted u otra persona corre peligro en este momento.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "PTSD is a common response to trauma, not a weakness, and it can improve with treatment even years later.",
        "Trauma-focused therapy is a first-line treatment; encourage the patient to start and stay with it.",
        "Reinforce grounding and slow-breathing skills for distressing memories, plus a regular sleep routine.",
        "Using alcohol or drugs to cope makes PTSD worse over time; gently encourage healthier coping and support.",
        "Use a trauma-informed approach: let the patient set the pace, never ask for details of the trauma, and offer choices.",
        "If the patient mentions thoughts of self-harm, follow the practice's safety protocol and alert the provider right away.",
      ],
      ask: [
        "How have you been sleeping, and how often are bad dreams or upsetting memories coming up?",
        "What has helped you get through tough moments since we last talked?",
        "How are therapy and your medicines going? Is anything getting in the way?",
        "Who do you feel comfortable leaning on for support?",
        "Do you feel safe where you live right now?",
      ],
    },
    carePlan: {
      problem: "Posttraumatic stress disorder, chronic",
      expectedOutcome: "With trauma-focused treatment and collaborative care, the patient is expected to show a clinically meaningful reduction in PTSD symptoms within 3–6 months, with better sleep and daily functioning.",
      goals: [
        "PCL-5 decrease of at least 10 points from baseline within 3–6 months, with a continued downward trend (or as individualized by the provider)",
        "PCL-5 below the probable-PTSD threshold (about 31–33) (or as individualized by the provider)",
        "Engagement in trauma-focused psychotherapy, attending at least 80% of scheduled sessions (or as individualized by the provider)",
        "PHQ-9 below 5 when co-occurring depression is present (or as individualized by the provider)",
      ],
      monitoring: [
        "PCL-5 at intake and at each monthly contact during active treatment, tracked in the BHI registry",
        "PHQ-9 at each monthly contact, with item 9 reviewed for suicide risk",
        "AUDIT-C and DAST at intake and every 6 months (substance use commonly co-occurs)",
        "Sleep quality, nightmare frequency, medication adherence and side effects at each monthly contact",
        "Therapy attendance and engagement reviewed monthly",
      ],
      interventions: [
        "Referral to evidence-based trauma-focused psychotherapy (e.g., prolonged exposure, cognitive processing therapy, EMDR)",
        "Measurement-based care with registry tracking, plus psychiatric consultation and caseload review for patients not improving",
        "Psychoeducation and brief skills support by the BHI care manager (grounding, breathing, sleep routine)",
        "Trauma-informed approach in all contacts; screen for current safety, including intimate partner violence",
        "Collaborative safety planning and lethal-means counseling when suicidal thoughts are reported",
      ],
      selfManagement: [
        "Attend trauma-focused therapy sessions and practice assigned skills between sessions",
        "Use grounding and slow breathing when distressed",
        "Keep a regular sleep routine and report nightmares",
        "Avoid alcohol and drugs as coping tools",
        "Take medicines as prescribed and report side effects",
      ],
      symptomManagement: [
        "More flashbacks, nightmares or avoidance (rising PCL-5): same-week review; provider considers a treatment change",
        "Escalating alcohol or drug use: brief intervention and referral per the substance use plan",
        "Suicidal thoughts or safety concerns: follow the practice safety protocol; 988 (veterans press 1) or 911 as appropriate",
      ],
      coordination: [
        "Trauma-focused psychotherapy providers and the psychiatric consultant",
        "VA health care and Veterans Crisis Line resources for veterans",
        "Community victim services, domestic violence resources and peer support groups",
      ],
    },
    basis: [
      "VA/DoD Clinical Practice Guideline for the Management of Posttraumatic Stress Disorder and Acute Stress Disorder",
      "APA Clinical Practice Guideline for the Treatment of PTSD",
      "AIMS Center Collaborative Care",
    ],
  },

  // ---------------------------------------------------------------------------------------------------------
  {
    key: "bipolar",
    education: {
      en: {
        title: "Living with bipolar disorder and related conditions",
        whatItIs: "Bipolar disorder is a health condition of the brain that causes big changes in mood, energy and sleep. You may have times of feeling very low, and times of feeling very up, wired or irritable, which is called mania. Some related conditions can change how a person thinks or senses the world, such as hearing voices or having strong beliefs that others don't share.",
        whyItMatters: "Without steady treatment, symptoms can come back more often and affect your health, relationships and safety. With treatment and support, many people live full, steady lives.",
        whatYouCanDo: [
          "Keep a steady routine: go to bed, wake up and eat at about the same times every day.",
          "Take your medicine every day, even when you feel well. Feeling well often means the medicine is working.",
          "Learn your early warning signs, like sleeping less, racing thoughts or pulling away from people. Write a plan with your care team for what to do.",
          "Choose a trusted person who knows your plan and can help if they notice warning signs.",
          "Avoid alcohol and drugs. They can bring on symptoms and get in the way of your medicines.",
          "Track your mood and sleep each day on a calendar or a phone app.",
          "Care for your heart: eat healthy foods, move every day and don't smoke. Ask us for help quitting.",
        ],
        numbers: [
          "Sleep: about 7 to 9 hours a night, at regular times, or the goal your provider sets for you. Sleeping much less without feeling tired can be an early warning sign.",
          "Weight, blood sugar and cholesterol: some medicines for these conditions can raise them, so we check them regularly. Keep them in a healthy range, or the goal your provider sets for you.",
          "Mood check-in (PHQ-9) during low times: lower is better, with a goal under 5, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicines every day as prescribed. Don't stop them on your own, even when you feel well. Stopping suddenly can bring symptoms back fast.",
          "Some medicines need regular blood tests to check the level in your blood and how your kidneys, thyroid or liver are doing. Keep those lab appointments.",
          "Don't drink alcohol or use drugs with these medicines.",
          "Tell us about side effects like shaking, stiff muscles, restlessness, feeling slowed down or weight gain. There are often ways to help.",
        ],
        callUs: [
          "You notice early warning signs: sleeping much less, racing thoughts, spending a lot of money, or feeling low for more than a week.",
          "You hear or see things others don't, or you have new or stronger fears or beliefs that worry you or your family.",
          "You are very thirsty, urinating a lot or gaining weight quickly.",
          "You have vomiting, diarrhea, bad shaking, unsteady walking or confusion while taking a medicine that needs blood level checks. Call right away.",
          "Side effects bother you, or you have trouble getting or paying for your medicine.",
        ],
        call911: [
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
          "Call 911 if you or someone else is in danger, or if you are so confused or upset that you can't stay safe.",
          "Call 911 for a high fever with very stiff muscles and confusion, a seizure, or fainting while taking medicine for these conditions.",
        ],
      },
      es: {
        title: "Cómo vivir con el trastorno bipolar y condiciones parecidas",
        whatItIs: "El trastorno bipolar es una condición de salud del cerebro que causa cambios fuertes en el estado de ánimo, la energía y el sueño. Puede haber temporadas de mucha tristeza o desánimo y otras de mucha energía, euforia o irritabilidad; a estas últimas se les llama manía. Algunas condiciones parecidas pueden cambiar la forma en que una persona piensa o percibe el mundo, por ejemplo, oír voces o tener creencias muy firmes que otras personas no comparten.",
        whyItMatters: "Sin un tratamiento constante, los síntomas pueden regresar con más frecuencia y afectar su salud, sus relaciones y su seguridad. Con tratamiento y apoyo, muchas personas llevan una vida plena y estable.",
        whatYouCanDo: [
          "Lleve una rutina fija: acuéstese, levántese y coma más o menos a las mismas horas todos los días.",
          "Tome su medicina todos los días, aun cuando se sienta bien. Sentirse bien muchas veces quiere decir que la medicina está funcionando.",
          "Aprenda a reconocer sus señales de alerta, como dormir menos, tener pensamientos acelerados o alejarse de la gente. Haga por escrito, con su equipo de atención, un plan de qué hacer.",
          "Escoja a una persona de confianza que conozca su plan y pueda ayudarle si nota señales de alerta.",
          "Evite el alcohol y las drogas. Pueden desatar síntomas e interferir con sus medicinas.",
          "Anote cada día su estado de ánimo y cuánto durmió, en un calendario o en una aplicación del teléfono.",
          "Cuide su corazón: coma alimentos saludables, muévase todos los días y no fume. Pídanos ayuda para dejar de fumar.",
        ],
        numbers: [
          "Sueño: de 7 a 9 horas por noche, en horarios regulares, o la meta que su proveedor le indique. Dormir mucho menos sin sentir cansancio puede ser una señal de alerta temprana.",
          "Peso, azúcar en la sangre y colesterol: algunas medicinas para estas condiciones pueden subirlos, por eso los revisamos con regularidad. Manténgalos en un rango saludable, o la meta que su proveedor le indique.",
          "Chequeo del estado de ánimo (PHQ-9) en las temporadas de desánimo: mientras más bajo, mejor, con una meta menor de 5, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas todos los días como se las recetaron. No las deje por su cuenta, aunque se sienta bien. Dejarlas de repente puede hacer que los síntomas regresen rápido.",
          "Algunas medicinas necesitan análisis de sangre regulares para revisar su nivel en la sangre y cómo están sus riñones, su tiroides o su hígado. No falte a esas citas de laboratorio.",
          "No tome alcohol ni use drogas con estas medicinas.",
          "Cuéntenos si tiene efectos secundarios como temblores, músculos rígidos, inquietud, sensación de lentitud o aumento de peso. Muchas veces hay formas de ayudar.",
        ],
        callUs: [
          "Nota señales de alerta: duerme mucho menos, tiene pensamientos acelerados, gasta mucho dinero o se siente sin ánimo por más de una semana.",
          "Oye o ve cosas que otras personas no perciben, o tiene miedos o creencias nuevas o más fuertes que le preocupan a usted o a su familia.",
          "Tiene mucha sed, orina mucho o sube de peso rápidamente.",
          "Tiene vómitos, diarrea, temblores fuertes, pierde el equilibrio al caminar o siente confusión mientras toma una medicina que necesita revisión de niveles en la sangre. Llame de inmediato.",
          "Los efectos secundarios le molestan, o tiene problemas para conseguir o pagar su medicina.",
        ],
        call911: [
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
          "Llame al 911 si usted u otra persona corre peligro, o si siente tanta confusión o angustia que no puede mantenerse a salvo.",
          "Llame al 911 si tiene fiebre alta con músculos muy rígidos y confusión, una convulsión o un desmayo mientras toma medicina para estas condiciones.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "These are treatable medical conditions; with steady treatment and support many people stay well for long periods. Use respectful, people-first language.",
        "Daily medicine matters even when the patient feels well; stopping suddenly can trigger a relapse, so encourage talking to the prescriber before any change.",
        "A regular sleep and daily routine helps keep mood stable; sleeping much less without feeling tired can be an early warning sign.",
        "Encourage a written relapse plan with early warning signs and a trusted support person (shared only with the patient's permission).",
        "Some of these medicines need regular blood tests plus weight, blood sugar and cholesterol checks; help the patient keep those lab appointments.",
        "If the patient mentions thoughts of self-harm, follow the practice's safety protocol and alert the provider right away.",
      ],
      ask: [
        "How have your mood, energy and sleep been since we last talked?",
        "Have you noticed any of your early warning signs lately?",
        "How is it going taking your medicine every day? Any side effects or trouble getting refills?",
        "Are your lab and psychiatry appointments scheduled? Is anything making them hard to get to?",
        "Who is in your corner right now, and do they know your plan?",
      ],
    },
    carePlan: {
      problem: "Bipolar I or II disorder (specify current or most recent episode) or schizophrenia-spectrum/other psychotic disorder (specify)",
      expectedOutcome: "With coordinated psychiatric and primary care, the patient is expected to maintain symptom stability with fewer relapses and hospitalizations while cardiometabolic risk is monitored and managed.",
      goals: [
        "No psychiatric hospitalizations or emergency visits for mood or psychotic symptoms over the next 6 months (or as individualized by the provider)",
        "Medication adherence on at least 80% of days by refill data or self-report (or as individualized by the provider)",
        "Depressive symptoms improving toward PHQ-9 below 5, with no manic/hypomanic or psychotic relapse at monthly contacts (or as individualized by the provider)",
        "Metabolic and medication lab monitoring completed on schedule, with weight, A1c, lipids and blood pressure at the targets set for the patient (or as individualized by the provider)",
      ],
      monitoring: [
        "Mood and symptom check at each monthly contact: PHQ-9 for depressive symptoms plus screening questions for mania/hypomania (sleep, energy, racing thoughts) and psychosis warning signs",
        "Metabolic monitoring for antipsychotics per guideline (weight, glucose/A1c, lipids): weight/BMI at baseline, monthly for the first 3 months, then quarterly; blood pressure, glucose/A1c and lipids at baseline, at about 3–4 months, then at least annually",
        "Mood-stabilizer lab monitoring as directed by the prescriber (e.g., serum levels, kidney, thyroid and liver function, blood counts as applicable)",
        "Abnormal involuntary movement screening per psychiatry (every 6–12 months for patients on antipsychotics)",
        "Suicide risk at each contact; AUDIT-C/DAST at intake and every 6 months",
        "Medication adherence, refill gaps and side effects at each monthly contact",
      ],
      interventions: [
        "Coordinate with the treating psychiatrist: shared medication list, lab results and visit notes; communicate changes promptly",
        "Written relapse prevention plan with the patient (and a support person, with consent) listing early warning signs and action steps",
        "Psychiatric consultation for patients managed in primary care; urgent referral when symptoms escalate",
        "Cardiometabolic risk management in primary care (tobacco cessation, weight, blood pressure, diabetes and lipid management)",
        "Adherence support (pill organizers, refill synchronization, reminders) and psychoeducation for patient and family",
        "Collaborative safety planning when suicidal thoughts are reported",
      ],
      selfManagement: [
        "Take medicines daily and keep lab and psychiatry appointments",
        "Keep a regular sleep–wake and meal schedule; track mood and sleep daily",
        "Follow the relapse plan when early warning signs appear",
        "Avoid alcohol and drugs and work toward stopping tobacco",
        "Eat healthily and stay physically active",
      ],
      symptomManagement: [
        "Early signs of mania/hypomania or depression: same-day contact with the prescriber per the relapse plan",
        "New or worsening psychotic symptoms or inability to stay safe: urgent psychiatric evaluation; 911 or 988 if there is danger",
        "Signs of mood-stabilizer toxicity (vomiting, diarrhea, coarse tremor, unsteady gait, confusion) or neuroleptic malignant syndrome (fever, rigidity, confusion): urgent same-day or emergency evaluation",
        "Suicidal thoughts: follow the practice safety protocol; 988 or 911 as appropriate",
      ],
      coordination: [
        "Psychiatry (leads mood-stabilizer and antipsychotic management) and psychotherapy",
        "Community mental health center and case management services",
        "Peer support and family education programs (e.g., NAMI, DBSA)",
        "Social services for housing, benefits and transportation",
      ],
    },
    basis: [
      "APA Practice Guideline for the Treatment of Patients With Schizophrenia",
      "CANMAT/ISBD Guidelines for the Management of Patients With Bipolar Disorder",
      "ADA/APA Consensus Statement on Antipsychotic Drugs, Obesity and Diabetes (metabolic monitoring)",
    ],
  },

  // ---------------------------------------------------------------------------------------------------------
  {
    key: "substance",
    education: {
      en: {
        title: "Recovery from alcohol and drug use",
        whatItIs: "A substance use disorder is a health condition where alcohol or drugs become hard to control, even when they cause problems. It changes how the brain works, so it is not a weakness or a moral failing. Like other long-term health conditions, it can be treated, and many people recover.",
        whyItMatters: "Alcohol and drugs can harm your heart, liver, brain, mood and relationships, and they raise the risk of falls, accidents and overdose. Getting help early, and reaching out again after a slip, protects your health and your life.",
        whatYouCanDo: [
          "Set a goal with us, like stopping or cutting back, and write down your reasons for wanting to change.",
          "If you drink heavily every day, or take sleeping or nerve pills every day, don't stop all at once on your own. Stopping suddenly can be dangerous. Talk with us first so we can help you stop safely.",
          "Have a plan for cravings: wait 15 minutes, call someone, take a walk or leave the place. Cravings pass.",
          "When you can, stay away from the people, places and things that make you want to use.",
          "Join a recovery or support group, in person or online. You don't have to do this alone.",
          "If you use opioids, or live with someone who does, keep naloxone at home. Never use alone.",
          "A slip does not mean you failed. Call us, and we will help you get back on track.",
        ],
        numbers: [
          "Days without drinking or using: mark each one on a calendar. The goal is no use, or less use as a first step, or the goal your provider sets for you.",
          "If you are cutting back on alcohol, count every drink. One drink is 12 ounces of beer, 5 ounces of wine or 1.5 ounces of liquor. Aim for fewer drinks each week, or the goal your provider sets for you.",
        ],
        medicines: [
          "There are safe, proven medicines that help with alcohol or opioid use disorder. They ease cravings and help prevent a return to use. Ask us if one is right for you.",
          "Take recovery medicines as prescribed, and don't stop without talking with us. After a break from opioids, your body can't handle the amount it used to, so the risk of overdose is much higher.",
          "Naloxone is a medicine that can reverse an opioid overdose. You can get it at a pharmacy without a prescription. Keep it where family or friends can find it, and show them how to use it.",
          "Mixing alcohol, drugs, or pills for pain, sleep or nerves can slow or stop your breathing. Tell us everything you take.",
        ],
        callUs: [
          "You have strong cravings, have had a slip, or want help to stop or cut back.",
          "You have withdrawal symptoms (signs your body is reacting to stopping), like shaking, sweating, nausea, a racing heart or feeling very anxious.",
          "Your mood is low, or you feel hopeless.",
          "You need help finding treatment, a recovery group or naloxone.",
          "For treatment and support at any hour, you can also call the SAMHSA National Helpline at 1-800-662-4357. It is free, confidential and open 24/7, in English and Spanish.",
        ],
        call911: [
          "Call 911 for signs of an overdose: the person won't wake up, breathing is very slow or has stopped, lips or fingertips turn blue or gray, or they make choking or snoring sounds. If you have naloxone, give it right away, and stay with them until help arrives.",
          "Call 911 for a seizure, severe confusion, or seeing or hearing things that aren't there while stopping alcohol or other drugs.",
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
        ],
      },
      es: {
        title: "Recuperarse del consumo de alcohol y drogas",
        whatItIs: "Un trastorno por consumo de sustancias es una condición de salud en la que se vuelve difícil controlar el alcohol o las drogas, aun cuando causan problemas. Cambia la forma en que funciona el cerebro; por eso no es una debilidad ni una falta moral. Como otras condiciones de salud de largo plazo, tiene tratamiento y muchas personas se recuperan.",
        whyItMatters: "El alcohol y las drogas pueden dañar el corazón, el hígado, el cerebro, el ánimo y las relaciones, y aumentan el riesgo de caídas, accidentes y sobredosis. Buscar ayuda a tiempo, y volver a pedirla después de una recaída, protege su salud y su vida.",
        whatYouCanDo: [
          "Póngase una meta con nosotros, como dejar de consumir o consumir menos, y escriba sus razones para querer cambiar.",
          "Si toma mucho alcohol todos los días, o toma pastillas para dormir o para los nervios a diario, no lo deje de golpe por su cuenta. Dejarlo de repente puede ser peligroso. Hable con nosotros primero para ayudarle a dejarlo sin riesgos.",
          "Tenga un plan para cuando le den ganas de consumir: espere 15 minutos, llame a alguien, salga a caminar o váyase del lugar. Las ganas pasan.",
          "Cuando pueda, aléjese de las personas, los lugares y las cosas que le dan ganas de consumir.",
          "Únase a un grupo de apoyo o de recuperación, en persona o en línea. No tiene que pasar por esto sin ayuda.",
          "Si usa opioides, o vive con alguien que los usa, tenga naloxona en casa. Nunca consuma a solas.",
          "Una recaída no significa que fracasó. Llámenos y le ayudaremos a retomar el camino.",
        ],
        numbers: [
          "Días sin tomar alcohol ni consumir drogas: márquelos en un calendario. La meta es no consumir, o consumir menos como primer paso, o la meta que su proveedor le indique.",
          "Si está reduciendo el alcohol, cuente cada bebida. Una bebida equivale a 12 onzas de cerveza, 5 onzas de vino o 1.5 onzas de licor. Trate de tomar menos bebidas cada semana, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Existen medicinas seguras y comprobadas que ayudan con el trastorno por consumo de alcohol o de opioides. Calman las ganas de consumir y ayudan a evitar una recaída. Pregúntenos si alguna es adecuada para usted.",
          "Tome las medicinas para su recuperación como se las recetaron y no las deje sin hablar con nosotros. Después de un tiempo sin opioides, su cuerpo ya no tolera la cantidad que usaba antes, y el riesgo de sobredosis es mucho mayor.",
          "La naloxona es una medicina que puede revertir una sobredosis de opioides. Se consigue en la farmacia sin receta. Guárdela donde su familia o sus amigos la puedan encontrar, y enséñeles a usarla.",
          "Mezclar alcohol, drogas o pastillas para el dolor, para dormir o para los nervios puede hacer que la respiración se vuelva muy lenta o se detenga. Díganos todo lo que toma.",
        ],
        callUs: [
          "Tiene muchas ganas de consumir, tuvo una recaída o quiere ayuda para dejar o reducir el consumo.",
          "Tiene síntomas de abstinencia (señales de que su cuerpo reacciona al dejar la sustancia), como temblores, sudor, náuseas, el corazón acelerado o mucha ansiedad.",
          "Se siente sin ánimo o sin esperanza.",
          "Necesita ayuda para encontrar tratamiento, un grupo de recuperación o naloxona.",
          "Para información sobre tratamiento y apoyo a cualquier hora, también puede llamar a la Línea Nacional de Ayuda de SAMHSA al 1-800-662-4357. Es gratis y confidencial, y atiende las 24 horas, los 7 días de la semana, en inglés y en español.",
        ],
        call911: [
          "Llame al 911 si ve señales de sobredosis: la persona no despierta, respira muy despacio o no respira, tiene los labios o las puntas de los dedos azules o grises, o hace ruidos como de ahogo o ronquido. Si tiene naloxona, désela de inmediato y quédese con la persona hasta que llegue la ayuda.",
          "Llame al 911 si hay una convulsión, confusión grave o si la persona ve u oye cosas que no están ahí al dejar el alcohol u otras drogas.",
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Substance use disorder is a treatable health condition, not a moral failing; use people-first, nonjudgmental language (for example, a person with a substance use disorder).",
        "Recovery often includes slips; treat a return to use as a reason to reconnect, not a failure, and let the provider know.",
        "A person who drinks heavily every day (or takes sedative pills daily) should not stop suddenly on their own; withdrawal can be dangerous, so connect them with the provider first.",
        "Effective medicines exist for alcohol and opioid use disorder; encourage the patient to ask the provider whether one fits them.",
        "If opioids are involved: naloxone at home, never use alone, and call 911 for an overdose. The SAMHSA National Helpline (1-800-662-4357) is free, confidential and open 24/7 in English and Spanish.",
        "If the patient mentions thoughts of self-harm, follow the practice's safety protocol and alert the provider right away.",
      ],
      ask: [
        "Since we last talked, on how many days have you had a drink or used? How does that compare with before?",
        "What has helped you on the days you didn't drink or use?",
        "What tends to get in the way: cravings, stress, certain people, pain or sleep?",
        "Who supports you, like a group, a sponsor, family or a counselor? Would you like help finding more support?",
        "If opioids are involved: do you have naloxone at home, and does someone near you know how to use it?",
      ],
    },
    carePlan: {
      problem: "Substance use disorder (specify substance(s) and severity, e.g., alcohol use disorder, moderate; opioid use disorder, severe; note early or sustained remission if applicable)",
      expectedOutcome: "With recovery-oriented collaborative care, the patient is expected to stop or reduce substance use, engage in treatment and recovery supports, and lower the risk of overdose and medical complications.",
      goals: [
        "Days abstinent: increase from baseline to at least 80% of days in each 30-day period by 3 months (or as individualized by the provider)",
        "Reduced use: heavy drinking or use days cut by at least 50% from baseline by 3 months, with AUDIT-C/DAST scores below baseline at 6 months (or as individualized by the provider)",
        "Treatment engagement: attends planned treatment (counseling, medication treatment and/or peer recovery support) for at least 90 days (or as individualized by the provider)",
        "Overdose prevention when opioids or sedatives are involved: naloxone in the home and an overdose response plan reviewed within 30 days (or as individualized by the provider)",
      ],
      monitoring: [
        "Self-reported days of use and heavy-use days at each monthly contact",
        "AUDIT-C / DAST-10 at intake and every 3–6 months",
        "PHQ-9 and GAD-7 at intake and every 3 months, with suicide risk reviewed at each contact",
        "Prescription drug monitoring program (PDMP) check and urine drug testing per the prescriber's protocol when controlled medicines or medication treatment are prescribed",
        "Liver tests, hepatitis B/C and HIV screening, blood pressure and weight per guideline (at least annually)",
      ],
      interventions: [
        "Brief intervention using motivational interviewing at each contact, with collaborative goal setting (abstinence or reduced use)",
        "Evaluation for medications for opioid or alcohol use disorder (MOUD/MAUD) and referral to an addiction specialist or opioid treatment program where appropriate",
        "Withdrawal risk assessment before any planned cessation (especially alcohol or sedatives), with referral for medically supervised withdrawal when indicated",
        "Overdose education and naloxone for the patient and household when opioids or sedatives are involved",
        "Relapse prevention planning and nonjudgmental re-engagement after a return to use; follow-up contact within 72 hours after any overdose",
        "Psychiatric consultation for co-occurring mental health conditions",
      ],
      selfManagement: [
        "Track days of use and cravings on a calendar or app",
        "Use a written plan for cravings and high-risk situations",
        "Attend recovery support or mutual-help meetings as planned",
        "Keep naloxone accessible and never use alone (when opioids are involved)",
        "Take prescribed recovery medicines as directed and keep appointments",
      ],
      symptomManagement: [
        "Cravings or return to use: same-week contact, motivational interviewing and plan revision; return to use is not a reason for discharge",
        "Withdrawal symptoms (tremor, sweating, tachycardia, anxiety): same-day provider assessment; seizures, hallucinations or delirium: 911",
        "Overdose: 911 and naloxone; follow-up contact within 24–72 hours and reassessment of the treatment plan",
        "Suicidal thoughts: follow the practice safety protocol; 988 or 911 as appropriate",
      ],
      coordination: [
        "Addiction medicine, opioid treatment programs and outpatient or intensive outpatient treatment",
        "Counseling and peer recovery support (e.g., AA, NA, SMART Recovery, certified peer specialists)",
        "SAMHSA National Helpline (1-800-662-4357) for treatment referral",
        "Social services for housing, employment, transportation and legal needs",
      ],
    },
    basis: [
      "SAMHSA TIP 63: Medications for Opioid Use Disorder",
      "ASAM National Practice Guideline for the Treatment of Opioid Use Disorder",
      "APA Practice Guideline for the Pharmacological Treatment of Patients With Alcohol Use Disorder",
    ],
  },

  // ---------------------------------------------------------------------------------------------------------
  {
    key: "cancer",
    education: {
      en: {
        title: "Living with cancer: during and after treatment",
        whatItIs: "Cancer happens when cells in the body grow out of control. There are many kinds of cancer, and each one is treated in its own way. Your cancer doctor (oncologist) leads your cancer treatment, and our team helps with everything else: your other health conditions, medicines, symptoms and support.",
        whyItMatters: "Cancer and its treatment can affect your whole body, your energy, your mood and your other health conditions. Staying in close touch with both teams helps you get through treatment safely and stay as healthy as you can afterward.",
        whatYouCanDo: [
          "Keep all your appointments with your cancer team and with us. Bring a list of questions and all your medicines.",
          "During treatment, wash your hands often and stay away from people who are sick.",
          "Eat what you can and drink plenty of fluids. Ask us for help if eating is hard or you are losing weight.",
          "Move your body when you can. Even short walks can help with tiredness and mood.",
          "Ask your cancer team which vaccines are safe for you, and keep up with your other checkups and screenings.",
          "If you smoke, quitting helps your treatment work better. Ask us for help.",
          "When treatment ends, ask your cancer team for a written summary of your treatment and a follow-up plan, and share it with us.",
        ],
        numbers: [
          "Weight: weigh yourself once a week. Try to keep your weight steady, or the goal your provider sets for you. Tell us if you lose weight without trying.",
          "Activity: when you feel able, work up to about 150 minutes of movement a week, like a 30-minute walk 5 days a week, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your cancer medicines, including any pills you take at home, exactly as your cancer team tells you. Don't stop or skip doses without asking them.",
          "Before starting any new medicine, vitamin, herb or supplement, check with your cancer team. Some can change how cancer treatment works.",
          "Tell us about side effects like nausea, pain, tiredness or trouble sleeping. There are medicines and other ways to help.",
          "Don't drink alcohol with pain or nausea medicines, and keep pain medicines in a safe place.",
        ],
        callUs: [
          "If you are getting chemotherapy and your temperature is 100.4°F (38°C) or higher, or you have shaking chills, call your cancer team right away, day or night. This can be a sign of a serious infection. If you can't reach anyone, go to the emergency room.",
          "You can't keep food or fluids down, or you have diarrhea that won't stop.",
          "You have new or worse pain, or mouth sores that make it hard to eat or drink.",
          "You have new swelling, redness or pain in one arm or leg. This can be a sign of a blood clot.",
          "You feel very down, anxious or overwhelmed, or you need help with rides, costs or care at home.",
        ],
        call911: [
          "Call 911 for trouble breathing, chest pain or coughing up blood.",
          "Call 911 for sudden weakness or numbness on one side of the body, trouble speaking or a sudden, severe headache.",
          "Call 911 for fainting, new confusion or bleeding that won't stop.",
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
        ],
      },
      es: {
        title: "Cómo vivir con cáncer: durante y después del tratamiento",
        whatItIs: "El cáncer ocurre cuando algunas células del cuerpo crecen sin control. Hay muchos tipos de cáncer, y cada uno se trata de forma distinta. Su especialista en cáncer (oncólogo) dirige el tratamiento del cáncer, y nuestro equipo le ayuda con todo lo demás: sus otras condiciones de salud, sus medicinas, sus síntomas y el apoyo que necesite.",
        whyItMatters: "El cáncer y su tratamiento pueden afectar todo el cuerpo, su energía, su ánimo y sus otras condiciones de salud. Mantenerse en contacto con los dos equipos le ayuda a pasar el tratamiento con seguridad y a cuidar su salud lo mejor posible después.",
        whatYouCanDo: [
          "No falte a sus citas con su equipo de cáncer ni con nosotros. Traiga una lista de preguntas y todas sus medicinas.",
          "Durante el tratamiento, lávese las manos con frecuencia y aléjese de las personas enfermas.",
          "Coma lo que pueda y tome bastantes líquidos. Pídanos ayuda si le cuesta comer o está bajando de peso.",
          "Mueva el cuerpo cuando pueda. Hasta las caminatas cortas ayudan con el cansancio y el ánimo.",
          "Pregunte a su equipo de cáncer qué vacunas son seguras para usted, y siga con sus otros chequeos y pruebas de detección.",
          "Si fuma, dejar de fumar ayuda a que el tratamiento funcione mejor. Pídanos ayuda.",
          "Cuando termine el tratamiento, pida a su equipo de cáncer un resumen por escrito de su tratamiento y un plan de seguimiento, y compártalo con nosotros.",
        ],
        numbers: [
          "Peso: pésese una vez por semana. Trate de mantener su peso estable, o la meta que su proveedor le indique. Avísenos si baja de peso sin proponérselo.",
          "Actividad: cuando se sienta con fuerzas, aumente poco a poco hasta unos 150 minutos de movimiento por semana, como caminar 30 minutos 5 días a la semana, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas contra el cáncer, incluidas las pastillas que toma en casa, exactamente como le indique su equipo de cáncer. No las deje ni se salte dosis sin preguntarles.",
          "Antes de empezar cualquier medicina, vitamina, hierba o suplemento nuevo, consulte con su equipo de cáncer. Algunos pueden cambiar cómo funciona el tratamiento.",
          "Cuéntenos si tiene efectos secundarios como náuseas, dolor, cansancio o problemas para dormir. Hay medicinas y otras formas de ayudar.",
          "No tome alcohol con las medicinas para el dolor o las náuseas, y guarde las medicinas para el dolor en un lugar seguro.",
        ],
        callUs: [
          "Si está recibiendo quimioterapia y tiene una temperatura de 100.4 °F (38 °C) o más, o escalofríos fuertes, llame de inmediato a su equipo de cáncer, de día o de noche. Puede ser señal de una infección grave. Si no logra comunicarse con nadie, vaya a la sala de emergencias.",
          "No puede retener la comida ni los líquidos, o tiene diarrea que no se le quita.",
          "Tiene dolor nuevo o más fuerte, o llagas en la boca que no le dejan comer ni beber.",
          "Tiene hinchazón, enrojecimiento o dolor nuevo en un brazo o una pierna. Puede ser señal de un coágulo de sangre.",
          "Siente mucha tristeza, ansiedad o agobio, o necesita ayuda con transporte, gastos o cuidado en casa.",
        ],
        call911: [
          "Llame al 911 si tiene dificultad para respirar, dolor en el pecho o tos con sangre.",
          "Llame al 911 si tiene debilidad o adormecimiento repentino de un lado del cuerpo, dificultad para hablar o un dolor de cabeza repentino y muy fuerte.",
          "Llame al 911 si se desmaya, tiene confusión nueva o un sangrado que no se detiene.",
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "The oncology team leads cancer treatment; our role is to coordinate everything else (other conditions, medicines, symptoms, support). Route questions about cancer treatment to the oncology team.",
        "During chemotherapy, a temperature of 100.4°F (38°C) or higher is urgent: the patient should call the cancer team right away, day or night, or go to the emergency room.",
        "Encourage handwashing, eating and drinking what they can, gentle activity, and checking with the cancer team before any new medicine or supplement.",
        "Emotional distress is common and expected; normalize it and offer behavioral health support or community resources.",
        "After treatment, encourage the patient to get a treatment summary and survivorship plan and to keep up with other screenings and vaccines.",
      ],
      ask: [
        "When is your next cancer treatment or appointment, and do you have a ride?",
        "How are you feeling: any pain, nausea, tiredness, fever or trouble eating?",
        "Have you started any new medicines, vitamins or supplements?",
        "How are you coping, and who is helping you at home?",
        "Is anything like cost, transportation or paperwork getting in the way of your care?",
      ],
    },
    carePlan: {
      problem: "Malignant neoplasm (specify primary site, histology and stage), in active treatment or survivorship",
      expectedOutcome: "With oncology-directed treatment and coordinated primary care, the patient is expected to complete planned treatment or surveillance with symptoms controlled, other chronic conditions managed and preventive care maintained; prognosis per the treating oncologist.",
      goals: [
        "No missed oncology appointments or treatments due to preventable barriers (transportation, cost, communication) over the next 3 months (or as individualized by the provider)",
        "Symptom burden (pain, fatigue, nausea) rated 3 or lower on a 0–10 scale and distress below 4 on the NCCN Distress Thermometer at monthly contacts (or as individualized by the provider)",
        "Weight stable within 5% of baseline over 3 months (or as individualized by the provider)",
        "For survivors: treatment summary and survivorship care plan on file within 3 months of completing active treatment, with age-appropriate screenings and vaccines up to date (or as individualized by the provider)",
      ],
      monitoring: [
        "Symptom and distress check (pain, fatigue, nausea, appetite, mood) at each monthly contact",
        "Weight and functional status at each visit, with self-reported weight on monthly calls",
        "Oncology-directed labs, imaging and surveillance per the oncology plan; results obtained and filed in the chart",
        "Medication reconciliation (including oral anticancer agents and supplements) after every oncology visit and at least monthly",
        "PHQ-9/GAD-7 at intake, at least every 6 months and with changes in treatment status",
        "Late and long-term effects (e.g., cardiac, bone, endocrine, neuropathy, second cancers) per the treatment summary and survivorship guidance",
      ],
      interventions: [
        "Coordinate with oncology: obtain the treatment plan, visit notes and treatment summary; track upcoming appointments and results",
        "Medication reconciliation and interaction review with oncology and pharmacy",
        "Distress screening with referral to BHI, psycho-oncology or social work as indicated",
        "Address barriers (transportation, financial toxicity, caregiver strain) through social services and financial navigation",
        "Advance care planning and goals-of-care discussion; palliative care referral for high symptom burden or advanced disease",
        "Survivorship and preventive care coordination: age-appropriate screenings, inactivated vaccines timed with oncology, cardiovascular risk management, tobacco cessation",
      ],
      selfManagement: [
        "During chemotherapy, check temperature when unwell and call the oncology team right away for 100.4°F (38°C) or higher",
        "Keep a symptom and medication list and bring it to every visit",
        "Stay as physically active as able and maintain nutrition and fluids",
        "Check with oncology before starting any new medicine or supplement",
        "Keep survivorship follow-up, screening and vaccine appointments",
      ],
      symptomManagement: [
        "Fever of 100.4°F (38°C) or higher during chemotherapy: immediate contact with oncology or emergency evaluation for possible neutropenic fever",
        "Uncontrolled pain, nausea, vomiting or diarrhea: same-day contact with oncology; primary care supports symptom control as directed",
        "Unilateral limb swelling, chest pain or shortness of breath: urgent evaluation for venous thromboembolism; 911 if severe",
        "New depression, anxiety or distress: BHI referral; follow the practice safety protocol for any suicidal thoughts",
      ],
      coordination: [
        "Oncology (medical, radiation and surgical) for cancer treatment and surveillance",
        "Palliative care and, when appropriate, hospice",
        "Social work, financial navigation and community cancer support organizations",
        "Home health, nutrition and rehabilitation services as needed",
      ],
    },
    basis: [
      "ASCO/NCCN survivorship guidance",
      "NCCN Guidelines for Distress Management",
      "ASCO/IDSA Guideline on Outpatient Management of Fever and Neutropenia",
    ],
  },

  // ---------------------------------------------------------------------------------------------------------
  {
    key: "hiv",
    education: {
      en: {
        title: "Living with HIV",
        whatItIs: "HIV is a virus that attacks the immune system, which is your body's defense against germs. Today, HIV is a long-term condition that can be well controlled. With medicine taken every day, people with HIV can live long, healthy lives.",
        whyItMatters: "Without treatment, HIV slowly weakens the immune system, which can lead to serious infections and AIDS, the most advanced stage of HIV. Taking HIV medicine every day keeps the virus under control and protects both your health and your partners.",
        whatYouCanDo: [
          "Take your HIV medicine at the same time every day. A pill box or a phone alarm can help you remember.",
          "Keep all your lab tests and visits, even when you feel fine.",
          "Stay up to date on your vaccines. Ask us which ones you need.",
          "Use condoms to protect against other infections spread through sex. Partners who don't have HIV can ask about a medicine that prevents HIV, called PrEP.",
          "Don't smoke, and avoid alcohol and drugs. They harm your health and make it harder to take your medicine every day.",
          "Eat healthy foods, stay active and get good sleep to help your body stay strong.",
          "You don't have to face this alone. Support groups and counselors can help, and what you share with us is kept private.",
        ],
        numbers: [
          "Viral load: how much HIV is in your blood. The goal is to keep it so low that the test can't find it, which is called undetectable, or the goal your provider sets for you.",
          "CD4 count: CD4 cells are part of your immune system. Higher is better; a count above 500 is in the usual healthy range, or the goal your provider sets for you.",
        ],
        medicines: [
          "Never stop your HIV medicine or skip doses, even when you feel well. If you have side effects or trouble taking it, call us first.",
          "Missing doses lets the virus change so the medicine may stop working. If you miss a dose, ask us what to do, and tell us if it is hard to take your medicine every day.",
          "When HIV medicine keeps your viral load undetectable, you will not pass HIV to a partner through sex. This is called U=U: Undetectable = Untransmittable. Most people get there within 6 months of starting treatment, and your lab tests will show when you do. Keep taking your medicine and getting tested to stay there.",
          "Before starting any new medicine, vitamin, herb or supplement, ask us. Some can keep HIV medicine from working well.",
        ],
        callUs: [
          "You missed doses, are running low on medicine or can't pay for it. Programs can help.",
          "You have side effects that bother you.",
          "You have a fever, cough, diarrhea, night sweats or weight loss that lasts more than a few days.",
          "You have white patches or sores in your mouth, trouble swallowing or a new rash.",
          "You feel down, anxious or alone, or you are drinking or using drugs more.",
        ],
        call911: [
          "Call 911 for sudden, severe symptoms: trouble breathing, chest pain, a seizure, fainting or new confusion.",
          "Call 911 for a very bad headache with fever, a stiff neck or confusion.",
          "Call 911 for a rash with fever, blisters, peeling skin or sores in your mouth or eyes, especially after starting a new medicine.",
          "If you are thinking about hurting yourself or ending your life, call or text 988 (Suicide & Crisis Lifeline) or call 911.",
        ],
      },
      es: {
        title: "Cómo vivir con el VIH",
        whatItIs: "El VIH es un virus que ataca el sistema inmunitario, que es la defensa de su cuerpo contra los gérmenes. Hoy en día, el VIH es una condición de largo plazo que se puede controlar bien. Con medicina todos los días, las personas con VIH pueden vivir muchos años y con buena salud.",
        whyItMatters: "Sin tratamiento, el VIH debilita poco a poco el sistema inmunitario, lo que puede causar infecciones graves y el SIDA, la etapa más avanzada del VIH. Tomar la medicina para el VIH todos los días mantiene el virus bajo control y protege tanto su salud como a sus parejas.",
        whatYouCanDo: [
          "Tome su medicina para el VIH a la misma hora todos los días. Un pastillero o una alarma en el teléfono le pueden ayudar a recordar.",
          "No falte a sus análisis de laboratorio ni a sus citas, aunque se sienta bien.",
          "Mantenga sus vacunas al día. Pregúntenos cuáles necesita.",
          "Use condón para protegerse de otras infecciones que se transmiten por vía sexual. Las parejas que no tienen VIH pueden preguntar por una medicina que previene el VIH, llamada PrEP.",
          "No fume y evite el alcohol y las drogas. Dañan su salud y hacen más difícil tomar la medicina todos los días.",
          "Coma alimentos saludables, haga actividad física y duerma bien para que su cuerpo se mantenga fuerte.",
          "No tiene que pasar por esto sin apoyo. Los grupos de apoyo y los consejeros pueden ayudarle, y lo que nos cuente se mantiene en privado.",
        ],
        numbers: [
          "Carga viral: la cantidad de VIH en la sangre. La meta es mantenerla tan baja que la prueba no la pueda encontrar, lo que se llama indetectable, o la meta que su proveedor le indique.",
          "Conteo de CD4: las células CD4 son parte de su sistema inmunitario. Mientras más alto, mejor; un conteo de más de 500 está en el rango saludable común, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Nunca deje su medicina para el VIH ni se salte dosis, aunque se sienta bien. Si tiene efectos secundarios o problemas para tomarla, llámenos primero.",
          "Si se salta dosis, el virus puede cambiar y la medicina podría dejar de funcionar. Si olvida una dosis, pregúntenos qué hacer, y díganos si se le hace difícil tomarla todos los días.",
          "Cuando la medicina mantiene su carga viral indetectable, usted no le transmite el VIH a su pareja por vía sexual. Esto se conoce como I=I: Indetectable = Intransmisible. La mayoría de las personas lo logra dentro de los primeros 6 meses de tratamiento, y sus análisis le mostrarán cuándo lo logró. Siga tomando su medicina y haciéndose los análisis para mantenerse así.",
          "Antes de empezar cualquier medicina, vitamina, hierba o suplemento nuevo, pregúntenos. Algunos pueden impedir que la medicina para el VIH funcione bien.",
        ],
        callUs: [
          "Se saltó dosis, se le está acabando la medicina o no puede pagarla. Hay programas que pueden ayudarle.",
          "Tiene efectos secundarios que le molestan.",
          "Tiene fiebre, tos, diarrea, sudores por la noche o pérdida de peso que dura más de unos días.",
          "Tiene manchas blancas o llagas en la boca, dificultad para tragar o un sarpullido nuevo.",
          "Siente tristeza, ansiedad o soledad, o está tomando alcohol o usando drogas más que antes.",
        ],
        call911: [
          "Llame al 911 si tiene síntomas repentinos y graves: dificultad para respirar, dolor en el pecho, una convulsión, un desmayo o confusión nueva.",
          "Llame al 911 si tiene un dolor de cabeza muy fuerte con fiebre, cuello rígido o confusión.",
          "Llame al 911 si tiene un sarpullido con fiebre, ampollas, piel que se pela o llagas en la boca o los ojos, sobre todo después de empezar una medicina nueva.",
          "Si está pensando en hacerse daño o en quitarse la vida, llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis) o llame al 911. El 988 ofrece ayuda en español.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "HIV is a manageable chronic condition; with daily medicine, people with HIV live long, healthy lives. Protect privacy: confirm identity first, and never leave HIV details on voicemail or with family unless the patient has given permission.",
        "HIV medicine must be taken every day and never stopped or skipped without talking to the provider; missed doses can lead to drug resistance.",
        "U=U: when the viral load is undetectable and stays that way, HIV is not passed to partners through sex; it does not protect against other sexually transmitted infections.",
        "The patient should check with the care team before any new medicine, vitamin or supplement because of interactions.",
        "Programs such as the Ryan White HIV/AIDS Program can help with medicine costs, case management and rides; offer a referral when cost or access is a barrier.",
        "Encourage regular lab work (viral load and CD4) and vaccines, and pass any mood or substance use concerns to the provider.",
      ],
      ask: [
        "In the past week, how many doses of your HIV medicine did you miss, if any?",
        "What, if anything, makes it hard to take your medicine every day?",
        "When is your next lab test or HIV specialist visit, and do you have a way to get there?",
        "Do you have enough medicine until your next refill, and any trouble paying for it?",
        "How are you feeling overall, including your mood and stress?",
      ],
    },
    carePlan: {
      problem: "Human immunodeficiency virus (HIV) infection, on antiretroviral therapy",
      expectedOutcome: "With consistent antiretroviral therapy and coordinated care, the patient is expected to maintain durable viral suppression and immune health with a near-normal life expectancy.",
      goals: [
        "HIV viral load suppressed (< 200 copies/mL, ideally undetectable) within 6 months of starting or changing ART and sustained thereafter (or as individualized by the provider)",
        "ART adherence of at least 95% of doses with no gaps in refills (or as individualized by the provider)",
        "Retention in care: at least 2 HIV care visits or viral load tests at least 90 days apart in each 12-month period (or as individualized by the provider)",
        "Recommended vaccinations, cancer screenings and cardiovascular risk assessment up to date within 12 months (or as individualized by the provider)",
      ],
      monitoring: [
        "HIV viral load every 3–6 months when stable (more often after starting or changing ART, per the HIV specialist)",
        "CD4 count every 3–6 months during the first 2 years of ART or if viremic; then every 12 months, or optional when consistently above 500, per DHHS guidance",
        "Adherence, refill gaps and side effects at each monthly contact",
        "Safety and comorbidity labs per guideline (kidney and liver function, lipids, glucose/A1c, hepatitis B/C; STI screening at least annually based on risk)",
        "PHQ-9 and substance use screening at least annually and when concerns arise",
        "Drug–drug interaction review at every medication change",
      ],
      interventions: [
        "Adherence support: pill organizers, reminders, refill synchronization and problem-solving of barriers",
        "Coordinate with the HIV specialist: share labs, medication lists and visit notes; track upcoming visits",
        "Re-engagement outreach within 1 week after a missed visit, missed refill or detectable viral load",
        "Connect to Ryan White HIV/AIDS Program services (AIDS Drug Assistance Program, medical case management, transportation)",
        "Preventive care: age-appropriate vaccines, cervical and anal cancer screening per HIV guidance, cardiovascular risk management, tobacco cessation",
        "Prevention counseling (U=U, condoms, PrEP referral for partners) and partner services as appropriate",
      ],
      selfManagement: [
        "Take ART every day at the same time, using reminders",
        "Keep lab and specialist appointments",
        "Check with the care team before starting new medicines or supplements",
        "Practice safer sex and avoid tobacco, alcohol misuse and drugs",
        "Report side effects instead of stopping medicine",
      ],
      symptomManagement: [
        "Missed doses or detectable viral load: adherence counseling, repeat viral load and HIV specialist review (possible resistance testing)",
        "Fever, persistent cough, shortness of breath, headache, diarrhea or weight loss: prompt evaluation for opportunistic infection, especially when CD4 is low",
        "Rash with fever or mucosal involvement, or other hypersensitivity signs: urgent same-day evaluation with the HIV specialist; 911 if severe",
        "Depression, anxiety or substance use: BHI referral; follow the practice safety protocol for any suicidal thoughts",
      ],
      coordination: [
        "HIV specialist / infectious disease clinic",
        "Ryan White HIV/AIDS Program providers, including ADAP and medical case management",
        "Behavioral health and substance use treatment services",
        "Social services for housing (e.g., HOPWA), food and transportation",
      ],
    },
    basis: [
      "DHHS Antiretroviral Guidelines for Adults and Adolescents With HIV",
      "HIVMA/IDSA Primary Care Guidance for Persons With HIV",
    ],
  },
];
