import type { ConditionLibraryEntry } from "./types";

// Condition library, group B: lung, kidney, thyroid, weight, sleep and liver conditions.
// DRAFT content: a provider reviews and approves each entry in MyPCP before patients see it.

export const GROUP_B: ConditionLibraryEntry[] = [
  // ---------------------------------------------------------------------------------------------
  {
    key: "copd",
    education: {
      en: {
        title: "Living with COPD",
        whatItIs: "COPD (chronic obstructive pulmonary disease) is a long-term lung disease. It makes it harder to move air in and out of your lungs. It is most often caused by years of smoking or breathing in smoke, dust, or fumes.",
        whyItMatters: "COPD can slowly get worse, and flare-ups can land you in the hospital. Caring for your lungs every day helps you breathe easier, stay active, and stay out of the hospital.",
        whatYouCanDo: [
          "If you smoke, quitting is the best thing you can do for your lungs. It is never too late, and we can help.",
          "Stay away from smoke, strong fumes, and dust. On days when the air is bad, stay indoors.",
          "Keep moving. Walk a little every day, and ask us about pulmonary rehab, a program of exercise and breathing training for people with lung disease.",
          "Practice pursed-lip breathing: breathe in through your nose, then breathe out slowly through your lips, like you are blowing out a candle.",
          "Get a flu shot every year. Ask us which other shots you need, like the pneumonia, RSV (a virus that can cause serious lung infections), and COVID-19 shots.",
          "Wash your hands often, and stay away from people who are sick.",
          "Make a COPD action plan with us, so you know what to do when your breathing gets worse.",
        ],
        numbers: [
          "Oxygen level from a pulse oximeter (a small clip that goes on your finger), if we asked you to use one: usually 88% or higher at rest, or the goal your provider sets for you.",
          "Flare-ups: no flare-ups that need extra medicine, an ER visit, or a hospital stay, or the goal your provider sets for you.",
          "Activity: work up to about 30 minutes of walking or other movement on most days, or the goal your provider sets for you.",
        ],
        medicines: [
          "Use your inhalers and take your medicines just as prescribed, even on days you feel well.",
          "Know your inhalers. Your daily inhaler keeps your airways open over time. Your rescue (quick-relief) inhaler works fast when you are short of breath. Keep your rescue inhaler with you at all times.",
          "If you use oxygen at home, use it the way it was prescribed. Never smoke near it, and keep it away from flames, candles, and gas stoves.",
          "Don't stop any medicine without talking to us. Bring all your inhalers and pill bottles to every visit, and ask us about side effects.",
        ],
        callUs: [
          "You are more short of breath than usual, or you need your rescue inhaler more often.",
          "Your mucus (phlegm) turns yellow, green, or brown, gets thicker, or there is more of it.",
          "You have a fever, chills, or a cough that keeps getting worse.",
          "Your ankles or legs are more swollen than usual.",
          "Your oxygen level is lower than your goal.",
        ],
        call911: [
          "Call 911 if you are so short of breath that you can't talk, walk, or lie down, and your rescue inhaler doesn't help.",
          "Call 911 if your lips or fingertips look blue or gray.",
          "Call 911 if you are confused, very drowsy, or very hard to wake up.",
          "Call 911 if you have chest pain or pressure.",
        ],
      },
      es: {
        title: "Cómo vivir con EPOC",
        whatItIs: "La EPOC (enfermedad pulmonar obstructiva crónica) es una enfermedad de los pulmones que dura mucho tiempo. Hace que le cueste más trabajo que el aire entre y salga de los pulmones. Casi siempre se debe a muchos años de fumar o de respirar humo, polvo o vapores químicos.",
        whyItMatters: "La EPOC puede empeorar poco a poco, y las crisis pueden mandarlo al hospital. Cuidar sus pulmones todos los días le ayuda a respirar mejor, seguir activo y mantenerse fuera del hospital.",
        whatYouCanDo: [
          "Si fuma, dejar de fumar es lo mejor que puede hacer por sus pulmones. Nunca es tarde, y nosotros le podemos ayudar.",
          "Aléjese del humo, los olores fuertes y el polvo. Los días en que el aire esté contaminado, quédese adentro.",
          "Muévase todos los días. Camine un poco cada día y pregúntenos por la rehabilitación pulmonar, un programa de ejercicio y respiración para personas con enfermedades de los pulmones.",
          "Practique la respiración con los labios fruncidos: tome aire por la nariz y sáquelo despacio por la boca, como si fuera a apagar una vela.",
          "Vacúnese contra la gripe cada año. Pregúntenos qué otras vacunas le tocan, como las de la neumonía, el VRS (un virus que puede causar infecciones fuertes en los pulmones) y el COVID-19.",
          "Lávese las manos seguido y aléjese de las personas que estén enfermas.",
          "Haga con nosotros un plan de acción para la EPOC, para que sepa qué hacer si su respiración empeora.",
        ],
        numbers: [
          "Nivel de oxígeno con un oxímetro de pulso (un aparatito que se pone en el dedo), si le pedimos que lo use: por lo general 88% o más en reposo, o la meta que su proveedor le indique.",
          "Crisis: ninguna crisis que necesite medicina extra, una visita a la sala de emergencias o una hospitalización, o la meta que su proveedor le indique.",
          "Actividad: llegar poco a poco a unos 30 minutos de caminar u otro ejercicio la mayoría de los días, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Use sus inhaladores y tome sus medicinas tal como se los recetaron, aun los días en que se sienta bien.",
          "Conozca sus inhaladores. El inhalador diario mantiene abiertas las vías respiratorias con el tiempo. El inhalador de rescate (de alivio rápido) actúa enseguida cuando le falta el aire. Lleve siempre consigo su inhalador de rescate.",
          "Si usa oxígeno en casa, úselo como se lo recetaron. Nunca fume cerca del oxígeno y manténgalo lejos de llamas, velas y estufas de gas.",
          "No deje ninguna medicina sin hablar antes con nosotros. Traiga todos sus inhaladores y frascos de pastillas a cada cita, y pregúntenos por los efectos secundarios.",
        ],
        callUs: [
          "Le falta el aire más de lo normal o necesita el inhalador de rescate más seguido.",
          "La flema se pone amarilla, verde o café, se vuelve más espesa o tiene más que de costumbre.",
          "Tiene fiebre, escalofríos o una tos que sigue empeorando.",
          "Tiene los tobillos o las piernas más hinchados que de costumbre.",
          "Su nivel de oxígeno está más bajo que su meta.",
        ],
        call911: [
          "Llame al 911 si le falta tanto el aire que no puede hablar, caminar ni acostarse, y el inhalador de rescate no le ayuda.",
          "Llame al 911 si tiene los labios o las puntas de los dedos de color azul o gris.",
          "Llame al 911 si tiene confusión, mucho sueño o es muy difícil hacer que se despierte.",
          "Llame al 911 si tiene dolor o presión en el pecho.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Review inhaler technique with teach-back (ask the patient to show or describe each step); flag poor technique to the nurse or provider.",
        "Reinforce the difference between the daily maintenance inhaler and the rescue inhaler, and that the rescue inhaler should be carried at all times.",
        "Encourage quitting smoking at every call and offer the practice's quit resources or the national quitline (1-800-QUIT-NOW).",
        "Review the COPD action plan: early warning signs of a flare-up and who to call.",
        "Remind about vaccines (flu, pneumonia, RSV, COVID-19) and upcoming breathing tests or pulmonary rehab visits.",
        "For patients on home oxygen, reinforce fire safety: no smoking, flames, candles, or gas stoves nearby.",
      ],
      ask: [
        "How has your breathing been this month compared with last month?",
        "Can you walk me through how you use each of your inhalers?",
        "How often have you needed your rescue inhaler in the past week?",
        "Have you had any flare-ups, urgent care or ER visits, or hospital stays since we last talked?",
        "Is anything making it hard to get or afford your inhalers, or to get to your appointments?",
      ],
    },
    carePlan: {
      problem: "Chronic obstructive pulmonary disease (COPD)",
      expectedOutcome: "With guideline-directed therapy, risk-factor reduction, and self-management support, symptoms are controlled, exacerbations and hospitalizations are reduced, and functional status is preserved, recognizing that airflow limitation is chronic and may progress.",
      goals: [
        "No moderate or severe exacerbations (requiring systemic corticosteroids or antibiotics, an ED visit, or hospitalization) over the next 12 months (or as individualized by the provider).",
        "Symptom burden stable or improved, with CAT score below 10 or mMRC grade 0–1 at each review (or as individualized by the provider).",
        "Resting SpO2 at or above 88% on room air or on prescribed oxygen, with long-term oxygen titrated per provider (or as individualized by the provider).",
        "Complete tobacco abstinence, with a documented quit plan within 3 months for patients who currently smoke (or as individualized by the provider).",
      ],
      monitoring: [
        "Post-bronchodilator spirometry to confirm the diagnosis, then at least annually and with significant clinical change.",
        "Symptom scores (CAT or mMRC), exacerbation history, and rescue-inhaler use at every visit and monthly CCM contact.",
        "Inhaler technique and adherence at every visit and whenever a device is changed.",
        "Resting SpO2 at every visit; reassess oxygen need 60–90 days after starting long-term oxygen and as clinically indicated.",
        "Smoking status at every contact; annual low-dose CT lung cancer screening if eligible (age 50–80, 20 or more pack-years, currently smoking or quit within the past 15 years).",
        "Blood eosinophil count when adjusting maintenance therapy, and one-time alpha-1 antitrypsin deficiency screening.",
      ],
      interventions: [
        "Guideline-directed maintenance and rescue inhaled therapy per provider, escalated or de-escalated by symptom burden and exacerbation history.",
        "Provide and review a written COPD action plan for early recognition and treatment of exacerbations.",
        "Inhaler technique education with teach-back at each visit; device change or spacer per provider if technique is inadequate.",
        "Tobacco cessation counseling at every contact, with cessation pharmacotherapy per provider and quitline referral.",
        "Vaccinations per the current CDC/ACIP schedule: annual influenza, COVID-19, pneumococcal, RSV (COPD is a qualifying risk condition for older adults), Tdap, and zoster.",
        "Transitional-care contact within 2 business days and provider follow-up within 7–14 days after any ED visit or hospitalization for an exacerbation.",
      ],
      selfManagement: [
        "Use maintenance therapy daily as prescribed and carry the rescue inhaler at all times.",
        "Follow the written action plan at the first sign of a flare-up and call the care team early.",
        "Avoid tobacco smoke, vaping, occupational dusts and fumes, and outdoor exposure on poor air-quality days.",
        "Stay physically active daily and use pursed-lip breathing and energy-conservation techniques.",
        "Use home oxygen as prescribed with fire-safety precautions, and log SpO2 if a pulse oximeter is prescribed.",
      ],
      symptomManagement: [
        "Increased dyspnea, sputum volume, or sputum purulence: start action-plan steps and contact the care team the same day.",
        "Dyspnea not relieved by the rescue inhaler, cyanosis, new confusion or drowsiness, or chest pain: call 911.",
        "New or worsening ankle edema: notify the provider to evaluate for cor pulmonale or heart failure.",
        "Breathlessness-related anxiety or low mood: teach breathing and relaxation techniques, screen with GAD-7 and PHQ-9, and refer to behavioral health as needed.",
      ],
      coordination: [
        "Pulmonary rehabilitation for symptomatic patients and after hospitalization for an exacerbation (ideally starting within 4 weeks of discharge).",
        "Pulmonology for diagnostic uncertainty, rapid decline, frequent exacerbations despite therapy, suspected alpha-1 antitrypsin deficiency, or evaluation for oxygen, home ventilatory support, or lung volume reduction.",
        "DME supplier for home oxygen, nebulizer, and pulse oximeter, including required recertification.",
        "Tobacco quitline (1-800-QUIT-NOW), community lung-health support groups, and palliative care for advanced disease with high symptom burden.",
      ],
    },
    basis: [
      "GOLD 2025 Report (Global Strategy for the Diagnosis, Management, and Prevention of COPD)",
      "CDC/ACIP Adult Immunization Schedule",
      "USPSTF Lung Cancer Screening Recommendation (2021)",
    ],
  },

  // ---------------------------------------------------------------------------------------------
  {
    key: "asthma",
    education: {
      en: {
        title: "Living with asthma",
        whatItIs: "Asthma is a long-term condition of your airways, the tubes that carry air in and out of your lungs. During an asthma attack, the airways swell, get tight, and fill with mucus, which makes it hard to breathe. Asthma can't be cured, but it can be well controlled.",
        whyItMatters: "Asthma that is not controlled can lead to serious attacks that send you to the ER or the hospital. When asthma is under control, most people sleep well and can do the things they enjoy.",
        whatYouCanDo: [
          "Learn your triggers, the things that set off your asthma, like smoke, dust, pollen, pets, mold, strong smells, cold air, or colds. Avoid them when you can.",
          "Don't smoke or vape, and keep your home and car smoke-free.",
          "Use your inhalers the right way. Bring them to your visits so we can watch you use them.",
          "Follow your written asthma action plan. Keep a copy where you can see it, like on the fridge.",
          "If we gave you a peak flow meter, use it the way we showed you and write down your numbers.",
          "Get a flu shot every year, and ask us which other shots you need.",
          "Stay active. If exercise makes you short of breath, tell us so we can help.",
        ],
        numbers: [
          "Peak flow, if you use a peak flow meter (a small tube you blow into that shows how open your airways are): green zone is 80% to 100% of your personal best, yellow zone is 50% to 79% (follow your action plan and call us), and red zone is below 50% (get help now). Aim to stay in the green zone, or the goal your provider sets for you.",
          "Rescue inhaler: needed 2 days a week or less, not counting use before exercise, or the goal your provider sets for you.",
          "Nights: asthma does not wake you up, or the goal your provider sets for you.",
        ],
        medicines: [
          "Your controller inhaler calms the swelling inside your airways. Use it as prescribed, even when you feel well. Some people use one inhaler for both daily control and quick relief, so follow the plan we made for you.",
          "Your rescue (quick-relief) inhaler opens your airways fast when you have symptoms. Keep it with you at all times.",
          "If you need your rescue inhaler more often than usual, your asthma is not under control. Tell us so we can check your plan.",
          "Don't stop any medicine without talking to us. Bring all your inhalers and medicines to every visit, and ask us about side effects.",
        ],
        callUs: [
          "You need your rescue inhaler more than 2 days a week, or it doesn't help as much or for as long as before.",
          "Asthma wakes you up at night.",
          "Your peak flow is in the yellow zone (50% to 79% of your best).",
          "You have a cold, the flu, or a fever that makes your asthma worse.",
          "You can't get or afford your inhalers.",
        ],
        call911: [
          "Call 911 if you are very short of breath and your rescue inhaler isn't helping, or your symptoms come right back.",
          "Call 911 if it is hard to talk or walk because you can't catch your breath.",
          "Call 911 if your lips or fingernails look blue or gray.",
          "Call 911 if your peak flow stays in the red zone (below 50% of your best) after you use your rescue inhaler the way your action plan says.",
        ],
      },
      es: {
        title: "Cómo vivir con asma",
        whatItIs: "El asma es una enfermedad de larga duración que afecta las vías respiratorias, los tubos que llevan el aire a los pulmones. Durante un ataque de asma, las vías respiratorias se hinchan, se cierran y se llenan de moco, y cuesta respirar. El asma no tiene cura, pero sí se puede controlar bien.",
        whyItMatters: "Si el asma no está controlada, puede causar ataques fuertes que terminen en la sala de emergencias o en el hospital. Cuando el asma está bajo control, la mayoría de las personas duermen bien y pueden hacer lo que les gusta.",
        whatYouCanDo: [
          "Conozca lo que le desencadena el asma, como el humo, el polvo, el polen, las mascotas, el moho, los olores fuertes, el aire frío o los resfriados. Evítelos cuando pueda.",
          "No fume ni use cigarrillos electrónicos, y no permita que se fume en su casa ni en su carro.",
          "Use sus inhaladores de la manera correcta. Tráigalos a sus citas para que veamos cómo los usa.",
          "Siga su plan de acción para el asma por escrito. Téngalo a la vista, por ejemplo en el refrigerador.",
          "Si le dimos un medidor de flujo máximo, úselo como le enseñamos y anote sus números.",
          "Vacúnese contra la gripe cada año y pregúntenos qué otras vacunas necesita.",
          "Manténgase en movimiento. Si al hacer ejercicio le falta el aire, avísenos para poder ayudarle.",
        ],
        numbers: [
          "Flujo máximo, si usa un medidor de flujo máximo (un tubito en el que usted sopla para ver qué tan abiertas están sus vías respiratorias): la zona verde es del 80% al 100% de su mejor marca personal, la zona amarilla es del 50% al 79% (siga su plan de acción y llámenos) y la zona roja es menos del 50% (busque ayuda de inmediato). Trate de mantenerse en la zona verde, o la meta que su proveedor le indique.",
          "Inhalador de rescate: usarlo 2 días a la semana o menos, sin contar cuando lo usa antes de hacer ejercicio, o la meta que su proveedor le indique.",
          "Noches: que el asma no le interrumpa el sueño, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "El inhalador controlador calma la hinchazón dentro de las vías respiratorias. Úselo como se lo recetaron, aunque se sienta bien. Algunas personas usan un solo inhalador para el control diario y para el alivio rápido, así que siga el plan que hicimos para usted.",
          "El inhalador de rescate (de alivio rápido) abre las vías respiratorias enseguida cuando tiene síntomas. Llévelo siempre consigo.",
          "Si necesita el inhalador de rescate más seguido que de costumbre, su asma no está bajo control. Avísenos para revisar su plan.",
          "No deje ninguna medicina sin hablar antes con nosotros. Traiga todos sus inhaladores y medicinas a cada cita, y pregúntenos por los efectos secundarios.",
        ],
        callUs: [
          "Necesita el inhalador de rescate más de 2 días a la semana, o ya no le alivia tanto ni por tanto tiempo como antes.",
          "El asma le interrumpe el sueño por la noche.",
          "Su flujo máximo está en la zona amarilla (del 50% al 79% de su mejor marca).",
          "Tiene un resfriado, gripe o fiebre que le empeora el asma.",
          "No puede conseguir o pagar sus inhaladores.",
        ],
        call911: [
          "Llame al 911 si le falta mucho el aire y el inhalador de rescate no le ayuda, o si los síntomas regresan enseguida.",
          "Llame al 911 si le cuesta hablar o caminar porque no puede recuperar el aliento.",
          "Llame al 911 si tiene los labios o las uñas de color azul o gris.",
          "Llame al 911 si su flujo máximo sigue en la zona roja (menos del 50% de su mejor marca) después de usar el inhalador de rescate como dice su plan de acción.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Review inhaler technique with teach-back (and spacer use if prescribed); flag poor technique to the nurse or provider.",
        "Reinforce the role of each inhaler exactly as written in the patient's action plan: some patients use a daily controller plus a rescue inhaler, others use one inhaler for both. Do not change the regimen; confirm what the provider prescribed.",
        "Review the written asthma action plan and peak flow zones, if the patient uses a meter.",
        "Discuss trigger avoidance at home and work (smoke, vaping, dust, mold, pets, fumes) and a smoke-free home and car.",
        "Remind about the yearly flu shot, other recommended vaccines, and upcoming asthma review visits.",
      ],
      ask: [
        "In the past 4 weeks, how many days a week have you had asthma symptoms or used your rescue inhaler?",
        "Has asthma woken you up at night or kept you from doing things you want to do?",
        "Can you show me or tell me how you use your inhaler, step by step?",
        "Have you had any attacks, urgent care or ER visits, or extra courses of medicine since we last talked?",
        "Is anything getting in the way of refilling or affording your inhalers?",
      ],
    },
    carePlan: {
      problem: "Asthma, with symptom control and future exacerbation risk assessed per GINA",
      expectedOutcome: "With guideline-directed therapy, correct inhaler technique, and trigger reduction, asthma is well controlled with minimal symptoms, normal activity, and no severe exacerbations.",
      goals: [
        "Well-controlled asthma at each review: daytime symptoms and reliever use 2 or fewer days per week, no night waking, and no activity limitation, or an ACT score of 20 or higher (or as individualized by the provider).",
        "No exacerbations requiring oral corticosteroids, an ED visit, or hospitalization over the next 12 months (or as individualized by the provider).",
        "Peak flow consistently at or above 80% of personal best for patients who monitor peak flow (or as individualized by the provider).",
        "Correct inhaler technique demonstrated by teach-back at every review (or as individualized by the provider).",
      ],
      monitoring: [
        "Symptom control (GINA assessment or ACT) and reliever use at every visit and monthly CCM contact.",
        "Exacerbations, urgent care or ED visits, and oral corticosteroid courses at every visit.",
        "Spirometry at diagnosis, 3–6 months after starting controller treatment, and then periodically (at least every 1–2 years in most adults).",
        "Inhaler technique and adherence at every visit; written action plan reviewed at least yearly.",
        "Modifiable risk factors and comorbidities at least annually: smoking or vaping, rhinosinusitis, GERD, obesity, sleep apnea, anxiety, and depression.",
      ],
      interventions: [
        "Guideline-directed therapy per provider, including inhaled anti-inflammatory treatment per GINA (no short-acting reliever-only treatment in adults), stepped up or down based on control and risk.",
        "Provide and review a written, individualized asthma action plan.",
        "Inhaler technique education with teach-back; spacer with metered-dose inhalers per provider.",
        "Trigger and environmental exposure counseling, including tobacco cessation and review of occupational exposures.",
        "Vaccinations per CDC/ACIP: annual influenza, COVID-19, and pneumococcal per age and risk criteria.",
        "Follow-up within 2–7 days after an ED visit or hospitalization for asthma.",
      ],
      selfManagement: [
        "Use controller or anti-inflammatory reliever therapy exactly as prescribed and carry the reliever inhaler at all times.",
        "Follow the written action plan and monitor peak flow if prescribed.",
        "Identify and limit exposure to personal triggers, including tobacco smoke.",
        "Attend scheduled asthma reviews and bring all inhalers to each visit.",
      ],
      symptomManagement: [
        "Increased symptoms or reliever use, or peak flow 50–79% of personal best: follow yellow-zone action-plan steps and contact the care team within 24 hours.",
        "Severe breathlessness, difficulty speaking, peak flow below 50% not improving after the reliever, cyanosis, or drowsiness or confusion: call 911.",
        "Night waking or activity limitation from asthma: report for provider review of adherence, technique, triggers, and treatment step.",
      ],
      coordination: [
        "Pulmonology or allergy/immunology for difficult-to-treat or severe asthma, uncertain diagnosis, frequent exacerbations needing oral corticosteroids, or evaluation for biologic therapy.",
        "Clinical pharmacist for inhaler technique, adherence support, and medication reconciliation.",
        "Occupational health when work-related asthma is suspected; community home-environment programs (mold, pests, allergens) where available.",
      ],
    },
    basis: [
      "GINA 2024 Global Strategy for Asthma Management and Prevention",
      "CDC/ACIP Adult Immunization Schedule",
    ],
  },

  // ---------------------------------------------------------------------------------------------
  {
    key: "ckd",
    education: {
      en: {
        title: "Living with chronic kidney disease",
        whatItIs: "Your kidneys clean waste and extra water out of your blood and help control your blood pressure. Chronic kidney disease (CKD) means your kidneys are damaged and don't filter as well as they should. CKD usually has no symptoms at first, so blood and urine tests are the best way to keep track of it.",
        whyItMatters: "CKD can slowly get worse, and it raises your risk of heart attack and stroke. Good care can slow it down and protect both your kidneys and your heart.",
        whatYouCanDo: [
          "Keep your blood pressure in your goal range, and your blood sugar too if you have diabetes.",
          "Eat less salt. Choose fresh foods more often than canned, boxed, frozen, or fast foods.",
          "Ask us or a dietitian (a food and nutrition expert) which foods are best for you. Some people with kidney disease need to limit certain foods.",
          "Don't smoke. Stay active, and aim for a healthy weight.",
          "Keep all your lab appointments. Blood and urine tests show how your kidneys are doing.",
          "Tell every doctor, dentist, and pharmacist that you have kidney disease. Ask before any scan that uses contrast dye (a special dye that helps the pictures show up).",
          "If you are sick with vomiting or diarrhea, or you can't eat or drink, call us. Some medicines may need to be paused for a short time.",
        ],
        numbers: [
          "eGFR (a blood test that shows how well your kidneys filter): we watch it over time, and the aim is to keep it as steady as possible, or the goal your provider sets for you.",
          "Urine protein (UACR, a urine test that checks for a protein called albumin): under 30, or the goal your provider sets for you.",
          "Blood pressure: under 130/80 for most people, or the goal your provider sets for you.",
          "A1C (your average blood sugar over 3 months), if you have diabetes: usually under 7% to 8%, depending on your health, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicines just as prescribed. Some blood pressure and diabetes medicines also help protect your kidneys.",
          "Avoid pain relievers like ibuprofen or naproxen. They can harm your kidneys. Ask us which pain reliever is safe for you.",
          "Check with us before you start any new medicine, vitamin, herbal product, or supplement. Some doses need to change when the kidneys don't work as well.",
          "Don't stop any medicine without talking to us. Bring all your pill bottles to every visit, and ask us about side effects.",
        ],
        callUs: [
          "You have new or worse swelling in your legs, feet, ankles, or face.",
          "You are peeing much less than usual, or your urine looks foamy, very dark, or bloody.",
          "You have vomiting or diarrhea, or you can't eat or drink for more than a day.",
          "Your blood pressure is above your goal on 2 or more checks.",
          "You feel more tired, itchy, or sick to your stomach than usual, or you lose your appetite.",
        ],
        call911: [
          "Call 911 if you have chest pain or pressure, or bad trouble breathing.",
          "Call 911 if you are confused, very sleepy, or have a seizure.",
          "Call 911 if your heart is beating very fast, very slow, or unevenly and you feel weak or faint.",
        ],
      },
      es: {
        title: "Cómo vivir con enfermedad renal crónica",
        whatItIs: "Los riñones limpian la sangre de desechos y del exceso de agua, y ayudan a controlar la presión arterial. La enfermedad renal crónica (ERC) significa que sus riñones están dañados y ya no filtran tan bien como deberían. Al principio casi nunca da síntomas, por eso los análisis de sangre y de orina son la mejor manera de vigilarla.",
        whyItMatters: "La enfermedad renal crónica puede empeorar poco a poco y aumenta el riesgo de ataque al corazón y de derrame cerebral. Con un buen cuidado se puede frenar, y así protege tanto sus riñones como su corazón.",
        whatYouCanDo: [
          "Mantenga su presión arterial dentro de su meta, y también su azúcar en la sangre si tiene diabetes.",
          "Coma con menos sal. Prefiera los alimentos frescos en lugar de los enlatados, empaquetados, congelados o de comida rápida.",
          "Pregúntenos a nosotros o a un dietista (un experto en alimentación y nutrición) qué alimentos le convienen más. Algunas personas con enfermedad de los riñones tienen que limitar ciertos alimentos.",
          "No fume. Manténgase en movimiento y procure llegar a un peso saludable.",
          "No falte a sus citas de laboratorio. Los análisis de sangre y de orina muestran cómo están sus riñones.",
          "Dígale a todo médico, dentista y farmacéutico que tiene enfermedad de los riñones. Pregunte antes de cualquier estudio que use medio de contraste (un tinte especial que ayuda a que se vean las imágenes).",
          "Si se enferma con vómito o diarrea, o si no puede comer ni beber, llámenos. Puede que haya que suspender algunas medicinas por poco tiempo.",
        ],
        numbers: [
          "TFGe (un análisis de sangre que muestra qué tan bien filtran sus riñones): lo vigilamos con el tiempo y lo ideal es que se mantenga lo más estable posible, o la meta que su proveedor le indique.",
          "Proteína en la orina (UACR, un análisis de orina que busca una proteína llamada albúmina): menos de 30, o la meta que su proveedor le indique.",
          "Presión arterial: menos de 130/80 para la mayoría de las personas, o la meta que su proveedor le indique.",
          "A1C (su promedio de azúcar en la sangre de los últimos 3 meses), si tiene diabetes: por lo general menos de 7% a 8%, según su salud, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas tal como se las recetaron. Algunas medicinas para la presión y para la diabetes también ayudan a proteger los riñones.",
          "Evite los analgésicos como el ibuprofeno o el naproxeno, porque pueden dañar los riñones. Pregúntenos qué medicina para el dolor es segura para usted.",
          "Consúltenos antes de empezar cualquier medicina, vitamina, producto de hierbas o suplemento nuevo. Algunas dosis tienen que cambiar cuando los riñones no funcionan tan bien.",
          "No deje ninguna medicina sin hablar antes con nosotros. Traiga todos sus frascos de pastillas a cada cita, y pregúntenos por los efectos secundarios.",
        ],
        callUs: [
          "Tiene hinchazón nueva o peor en las piernas, los pies, los tobillos o la cara.",
          "Está orinando mucho menos que de costumbre, o la orina se ve espumosa, muy oscura o con sangre.",
          "Tiene vómito o diarrea, o no puede comer ni beber por más de un día.",
          "Su presión arterial sale más alta que su meta en 2 o más mediciones.",
          "Siente más cansancio, comezón o náuseas que de costumbre, o pierde el apetito.",
        ],
        call911: [
          "Llame al 911 si tiene dolor o presión en el pecho, o mucha dificultad para respirar.",
          "Llame al 911 si tiene confusión, mucho sueño o una convulsión.",
          "Llame al 911 si el corazón le late muy rápido, muy lento o de forma irregular, y se siente débil o a punto de desmayarse.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Explain that CKD is usually silent, so regular blood (eGFR) and urine (UACR) tests matter even when the patient feels well.",
        "Reinforce avoiding NSAID pain relievers (ibuprofen, naproxen) and checking with the care team before any new medicine, vitamin, or supplement.",
        "Reinforce the patient's blood pressure (and blood sugar, if diabetic) goals and home blood pressure checks if prescribed.",
        "Encourage a lower-salt diet and offer a dietitian referral; do not give individual potassium, protein, or fluid limits unless the provider has set them.",
        "Remind the patient to tell every clinician and pharmacist about their kidney disease, and to call us when sick with vomiting, diarrhea, or poor eating or drinking.",
      ],
      ask: [
        "When was your last blood and urine test, and is the next one scheduled?",
        "What over-the-counter pain relievers, vitamins, or supplements do you take?",
        "What have your blood pressure readings been at home?",
        "Have you noticed any swelling, changes in how much you pee, or feeling more tired than usual?",
        "Is anything making it hard to get your medicines, get to the lab, or follow your eating plan?",
      ],
    },
    carePlan: {
      problem: "Chronic kidney disease (CKD), staged by GFR category (G1–G5) and albuminuria category (A1–A3)",
      expectedOutcome: "With guideline-directed kidney-protective therapy and risk-factor control, CKD progression is slowed, cardiovascular risk is reduced, and complications are identified and managed early.",
      goals: [
        "Blood pressure below 130/80 mmHg, with systolic below 120 mmHg by standardized office measurement when tolerated per KDIGO (or as individualized by the provider).",
        "Albuminuria reduced by at least 30% from baseline UACR, or maintained below 30 mg/g, on repeat testing (or as individualized by the provider).",
        "eGFR decline kept below 5 mL/min/1.73 m² per year, avoiding rapid progression (or as individualized by the provider).",
        "For patients with diabetes, A1C target individualized within the range of below 6.5% to below 8.0% (or as individualized by the provider).",
      ],
      monitoring: [
        "eGFR (creatinine-based, adding cystatin C when more accuracy is needed) and UACR by KDIGO risk category: at least yearly for low-to-moderate risk, 2 times a year for high risk, 3 times a year for very high risk, and 4 or more times a year for G4 A3 and G5.",
        "Kidney failure risk (KFRE) at least annually for CKD G3–G5 to guide referral and planning.",
        "Blood pressure at every visit, with home readings reviewed at monthly CCM contact if monitoring at home.",
        "Serum creatinine and potassium within 2–4 weeks after starting or changing RAAS-blocking or other kidney-protective therapy, per provider.",
        "CKD complications by stage per KDIGO: potassium, bicarbonate, and hemoglobin; calcium, phosphate, PTH, and vitamin D from G3a onward.",
        "Medication review at every visit for renal dosing and nephrotoxins (NSAIDs, contrast, certain supplements); lipid panel and A1C per guideline schedule.",
      ],
      interventions: [
        "Guideline-directed kidney- and cardio-protective therapy per provider (KDIGO 2024), with dosing reviewed against current eGFR.",
        "Blood pressure, glycemic, and lipid management per provider toward individualized targets.",
        "Medication reconciliation at every visit: avoid NSAIDs and other nephrotoxins, adjust renal dosing, and flag planned iodinated contrast exposure.",
        "Written sick-day guidance on which medicines to hold temporarily during vomiting, diarrhea, or poor oral intake, per provider.",
        "Lifestyle counseling: sodium below 2 g per day, protein about 0.8 g/kg/day in CKD G3–G5 (avoiding high protein intake), plant-forward eating as appropriate, physical activity, tobacco cessation, and healthy weight.",
        "Vaccinations per CDC/ACIP: annual influenza, pneumococcal, COVID-19, and hepatitis B for patients approaching dialysis.",
      ],
      selfManagement: [
        "Take medications as prescribed and avoid NSAID pain relievers and unapproved supplements.",
        "Follow a lower-sodium diet and any individualized plan from the provider or dietitian.",
        "Monitor home blood pressure if prescribed and bring readings to visits.",
        "Keep scheduled lab appointments and inform every clinician and pharmacist of CKD.",
        "Follow sick-day instructions and call the care team during vomiting, diarrhea, or poor intake.",
      ],
      symptomManagement: [
        "New edema, reduced urine output, or rapid weight gain: same-day contact with the care team for volume and kidney-function assessment.",
        "Vomiting, diarrhea, or poor intake: follow the sick-day plan and contact the care team; labs per provider to evaluate for acute kidney injury.",
        "Fatigue, pruritus, nausea, or poor appetite: report to the provider to evaluate for anemia, acidosis, or CKD progression.",
        "Chest pain, severe dyspnea, confusion, or palpitations with weakness (possible hyperkalemia): call 911.",
      ],
      coordination: [
        "Nephrology referral per KDIGO: eGFR below 30, UACR 300 mg/g or higher, 5-year kidney failure risk of 3–5% or higher by KFRE, rapid eGFR decline, unexplained hematuria, resistant hypertension, persistent hyperkalemia, or hereditary kidney disease.",
        "With nephrology, multidisciplinary CKD care when 2-year KFRE risk exceeds 10%, and kidney replacement therapy preparation (modality education, access, transplant referral, conservative care) when it exceeds 40%; Medicare kidney disease education sessions for CKD G4.",
        "Registered dietitian for medical nutrition therapy (a Medicare Part B benefit for CKD not on dialysis).",
        "Clinical pharmacist for renal dosing; endocrinology or cardiology as needed for diabetes or cardiovascular disease.",
      ],
    },
    basis: [
      "KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of CKD",
      "KDIGO 2021 Clinical Practice Guideline for the Management of Blood Pressure in CKD",
      "KDIGO 2022 Clinical Practice Guideline for Diabetes Management in CKD",
    ],
  },

  // ---------------------------------------------------------------------------------------------
  {
    key: "thyroid",
    education: {
      en: {
        title: "Living with thyroid disease",
        whatItIs: "Your thyroid is a small gland in the front of your neck. It makes a hormone that controls how fast your body uses energy. Most often the thyroid makes too little hormone (an underactive thyroid, or hypothyroidism), but sometimes it makes too much (an overactive thyroid, or hyperthyroidism).",
        whyItMatters: "An underactive thyroid that isn't treated can leave you tired, cold, and slowed down, while an overactive thyroid can make your heart race and weaken your bones. With the right treatment and regular blood tests, most people feel well.",
        whatYouCanDo: [
          "Take your thyroid pill at the same time every day.",
          "Take it on an empty stomach with a full glass of water, usually 30 to 60 minutes before breakfast, or the way we told you.",
          "Take calcium, iron, antacids, and multivitamins at least 4 hours before or after your thyroid pill. They can keep it from working well.",
          "Get your thyroid blood test (TSH) about 6 to 8 weeks after any dose change, and every 6 to 12 months once your level is steady.",
          "If your pills look different after a refill, tell us or your pharmacist.",
          "Tell us if you take biotin (a vitamin often sold for hair and nails). It can throw off thyroid test results, so you may need to stop it for a few days before your blood test. Ask us first.",
          "Eat well, stay active, and ask us before trying any supplement sold for thyroid, energy, or weight loss. Some contain thyroid hormone or iodine.",
        ],
        numbers: [
          "TSH (thyroid blood test): most people aim for the normal range, about 0.4 to 4.5 (a little higher can be fine for some people over 70), or the goal your provider sets for you.",
          "Resting heart rate, if you have an overactive thyroid: under 100 beats a minute, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your thyroid medicine every day as prescribed. Most people with an underactive thyroid need it for life.",
          "Don't stop it or change how you take it without talking to us, even if you feel fine.",
          "Bring all your pill bottles, vitamins, and supplements to every visit. Some of them can change how well your thyroid pill works.",
          "Ask us about side effects. Too much thyroid medicine can cause a racing heart, shakiness, or trouble sleeping. Too little can leave you tired and cold.",
        ],
        callUs: [
          "You feel very tired, cold, or constipated, or you gain weight without trying.",
          "Your heart races or pounds, or you feel shaky, nervous, or sweaty.",
          "You lose weight without trying, or you have trouble sleeping.",
          "You notice a lump or swelling in your neck, or it is hard to swallow.",
          "You take medicine for an overactive thyroid and get a sore throat, fever, or mouth sores. Call us right away.",
        ],
        call911: [
          "Call 911 if you have chest pain, a very fast or uneven heartbeat, or you faint.",
          "Call 911 if you are very confused, very sleepy, or very hard to wake up.",
          "Call 911 if you have a high fever with a racing heart, confusion, or great restlessness.",
          "Call 911 if swelling in your neck makes it hard to breathe.",
        ],
      },
      es: {
        title: "Cómo vivir con una enfermedad de la tiroides",
        whatItIs: "La tiroides es una glándula pequeña que está en la parte de adelante del cuello. Produce una hormona que controla la rapidez con la que su cuerpo usa la energía. Lo más común es que la tiroides produzca muy poca hormona (tiroides poco activa o hipotiroidismo), pero a veces produce demasiada (tiroides demasiado activa o hipertiroidismo).",
        whyItMatters: "Si no se trata, la tiroides poco activa puede causar cansancio, frío y lentitud, y la tiroides demasiado activa puede acelerar el corazón y debilitar los huesos. Con el tratamiento correcto y análisis de sangre regulares, la mayoría de las personas se sienten bien.",
        whatYouCanDo: [
          "Tome su pastilla para la tiroides a la misma hora todos los días.",
          "Tómela en ayunas con un vaso lleno de agua, por lo general de 30 a 60 minutos antes del desayuno, o como se lo indicamos.",
          "Tome el calcio, el hierro, los antiácidos y los multivitamínicos por lo menos 4 horas antes o después de su pastilla para la tiroides, porque pueden impedir que funcione bien.",
          "Hágase el análisis de sangre de la tiroides (TSH) unas 6 a 8 semanas después de cualquier cambio de dosis, y cada 6 a 12 meses cuando su nivel ya esté estable.",
          "Si sus pastillas se ven diferentes cuando surte la receta, avísenos a nosotros o a su farmacéutico.",
          "Díganos si toma biotina (una vitamina que se vende para el cabello y las uñas). Puede alterar los resultados del análisis de la tiroides, y quizás tenga que dejarla unos días antes de la prueba. Pregúntenos primero.",
          "Coma bien, manténgase en movimiento y pregúntenos antes de probar cualquier suplemento para la tiroides, la energía o para bajar de peso. Algunos contienen hormona tiroidea o yodo.",
        ],
        numbers: [
          "TSH (análisis de sangre de la tiroides): para la mayoría de las personas, dentro del rango normal, alrededor de 0.4 a 4.5 (un poco más alto puede estar bien en algunas personas mayores de 70 años), o la meta que su proveedor le indique.",
          "Pulso en reposo, si tiene la tiroides demasiado activa: menos de 100 latidos por minuto, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome su medicina para la tiroides todos los días como se la recetaron. La mayoría de las personas con la tiroides poco activa la necesitan de por vida.",
          "No la deje ni cambie la forma de tomarla sin hablar antes con nosotros, aunque se sienta bien.",
          "Traiga todos sus frascos de pastillas, vitaminas y suplementos a cada cita. Algunos pueden cambiar qué tan bien le funciona la pastilla para la tiroides.",
          "Pregúntenos por los efectos secundarios. Demasiada medicina para la tiroides puede acelerarle el corazón, causarle temblores o quitarle el sueño. Muy poca puede causarle cansancio y frío.",
        ],
        callUs: [
          "Siente mucho cansancio, frío o estreñimiento, o sube de peso sin razón.",
          "El corazón le late muy rápido o muy fuerte, o tiene temblores, nervios o sudor.",
          "Baja de peso sin intentarlo o le cuesta dormir.",
          "Nota una bolita o hinchazón en el cuello, o le cuesta tragar.",
          "Toma medicina para la tiroides demasiado activa y le da dolor de garganta, fiebre o llagas en la boca. Llámenos de inmediato.",
        ],
        call911: [
          "Llame al 911 si tiene dolor en el pecho, el corazón le late muy rápido o de forma irregular, o se desmaya.",
          "Llame al 911 si tiene mucha confusión, mucho sueño o es muy difícil hacer que se despierte.",
          "Llame al 911 si tiene fiebre alta con el corazón muy acelerado, confusión o mucha inquietud.",
          "Llame al 911 si la hinchazón del cuello no le deja respirar bien.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Reinforce taking thyroid replacement every day at the same time, on an empty stomach with water, 30–60 minutes before breakfast (or exactly as the provider instructed).",
        "Remind the patient to take calcium, iron, antacids, and multivitamins at least 4 hours apart from the thyroid pill.",
        "Explain that TSH is checked 6–8 weeks after a dose change and every 6–12 months when stable; help schedule overdue labs.",
        "Ask the patient to report pills that look different after a refill and any biotin use before labs; route both to the nurse or provider.",
        "For patients treated for an overactive thyroid, reinforce calling right away for sore throat, fever, or mouth sores.",
      ],
      ask: [
        "How and when do you take your thyroid pill each day?",
        "Do you take any calcium, iron, antacids, vitamins, or supplements? When do you take them?",
        "Have you noticed changes in your energy, weight, heartbeat, sleep, or bowel habits?",
        "Have you missed any doses, or had trouble getting refills or lab work done?",
      ],
    },
    carePlan: {
      problem: "Thyroid disease: primary hypothyroidism (or hyperthyroidism, as specified by the provider)",
      expectedOutcome: "With appropriate thyroid hormone replacement or treatment of hyperthyroidism and periodic monitoring, the patient remains clinically and biochemically euthyroid without complications of over- or under-treatment.",
      goals: [
        "Primary hypothyroidism: TSH within the laboratory reference range (about 0.4–4.5 mIU/L); a target of about 4–6 mIU/L may be acceptable in adults older than 70–80 (or as individualized by the provider).",
        "Avoid overtreatment: TSH not suppressed below the reference range on thyroid hormone replacement unless suppression is intended, such as for thyroid cancer (or as individualized by the provider).",
        "Hyperthyroidism: free T4 and T3 normalized and resting heart rate below 100 bpm within 3–6 months of starting treatment (or as individualized by the provider).",
        "Prescribed therapy taken correctly on at least 90% of days, by patient report and refill history (or as individualized by the provider).",
      ],
      monitoring: [
        "TSH 6–8 weeks after starting thyroid hormone or any dose change, then every 6–12 months when stable.",
        "Free T4 when TSH is unreliable (central hypothyroidism or pituitary disease); in hyperthyroidism, free T4 and T3 every 4–6 weeks while titrating, then less often per provider.",
        "Baseline CBC with differential and liver tests before starting antithyroid drugs, and promptly with fever, sore throat, or jaundice.",
        "Heart rate, rhythm, weight, and symptoms at each visit; ECG if atrial fibrillation is suspected.",
        "Medication and supplement review at each visit (calcium, iron, acid suppressants, biotin before labs, manufacturer changes on refill).",
        "Bone density per osteoporosis screening guidelines, especially after hyperthyroidism or prolonged TSH suppression.",
      ],
      interventions: [
        "Guideline-directed thyroid hormone replacement or hyperthyroidism therapy per provider, with dose adjusted to TSH, free T4, and symptoms.",
        "Education on correct administration: empty stomach, consistent timing, and 4-hour separation from interfering supplements and medicines.",
        "Lab tracking and outreach for overdue thyroid tests, with results communicated to the patient.",
        "Medication reconciliation at each visit, including supplements and refill manufacturer changes.",
        "Periodic provider review of the indication and dose in older adults, especially those treated for subclinical hypothyroidism, to avoid overtreatment.",
      ],
      selfManagement: [
        "Take thyroid medication daily as instructed, on an empty stomach, at least 4 hours apart from calcium, iron, and antacids.",
        "Keep scheduled thyroid lab appointments and ask whether to pause biotin before labs.",
        "Report symptoms of under- or over-treatment (fatigue, cold intolerance, palpitations, tremor, insomnia, weight change).",
        "Report changes in pill appearance after refills, and do not stop or change therapy without consulting the care team.",
      ],
      symptomManagement: [
        "Fatigue, cold intolerance, constipation, or weight gain: contact the care team; thyroid labs per provider.",
        "Palpitations, tremor, insomnia, heat intolerance, or weight loss: same-day contact to evaluate for overtreatment or hyperthyroidism.",
        "Fever, sore throat, or mouth ulcers while on antithyroid drugs: hold the drug and obtain an urgent CBC with differential per provider (possible agranulocytosis).",
        "Chest pain, syncope, high fever with agitation or confusion, or marked lethargy: call 911 (possible arrhythmia, thyroid storm, or myxedema coma).",
      ],
      coordination: [
        "Endocrinology for hyperthyroidism, thyroid nodules or goiter, inability to reach target TSH despite adherence, pregnancy or planned pregnancy, central hypothyroidism, or thyroid cancer.",
        "Clinical pharmacist for interaction review and refill synchronization.",
        "Radiology for thyroid ultrasound when indicated; cardiology for atrial fibrillation as needed.",
      ],
    },
    basis: [
      "American Thyroid Association Guidelines for the Treatment of Hypothyroidism (2014)",
      "American Thyroid Association Guidelines for Hyperthyroidism and Other Causes of Thyrotoxicosis (2016)",
    ],
  },

  // ---------------------------------------------------------------------------------------------
  {
    key: "obesity",
    education: {
      en: {
        title: "Your weight and your health",
        whatItIs: "Obesity is a long-term health condition in which extra body fat affects your health. It is not caused by a lack of willpower. Your genes, sleep, stress, some medicines, and the world around you all play a part.",
        whyItMatters: "Extra weight can raise your risk of diabetes, high blood pressure, heart disease, sleep apnea, and joint pain. Losing even 5% to 10% of your weight (10 to 20 pounds for a person who weighs 200 pounds) can make a real difference.",
        whatYouCanDo: [
          "Set small goals you can keep, like adding a vegetable to one meal a day or walking 10 more minutes.",
          "Fill half your plate with vegetables, and choose lean protein, beans, and whole grains.",
          "Drink water instead of soda, juice, and sweet tea or coffee drinks.",
          "Move more. Work up to 150 minutes a week of activity like brisk walking, and add exercises that keep your muscles strong.",
          "Try to sleep 7 to 8 hours a night, and find healthy ways to handle stress.",
          "Keep track of what you eat, how much you move, or your weight. Many people find this helps.",
          "Ask us about a dietitian (a food and nutrition expert), weight programs, and other treatments that may be right for you.",
        ],
        numbers: [
          "Weight loss: aim to lose 5% to 10% of your weight over about 6 months, or the goal your provider sets for you.",
          "Waist size: under 40 inches for men and under 35 inches for women, or the goal your provider sets for you.",
          "Activity: at least 150 minutes a week (for example, 30 minutes on 5 days), plus muscle-strengthening on 2 days, or the goal your provider sets for you.",
        ],
        medicines: [
          "Some medicines can cause weight gain. Don't stop any medicine on your own. Ask us to review your list instead.",
          "If we prescribe a medicine to help with weight, take it exactly as prescribed, keep up healthy eating and activity, and ask us about side effects.",
          "Bring all your pill bottles and supplements to every visit. Check with us before using any weight-loss product sold online or in stores.",
        ],
        callUs: [
          "You gain or lose a lot of weight quickly without trying.",
          "You feel down or hopeless, or you feel out of control with eating.",
          "You snore loudly, someone sees you stop breathing in your sleep, or you are very sleepy during the day.",
          "A weight medicine gives you nausea, vomiting, or constipation that doesn't go away.",
        ],
        call911: [
          "Call 911 if you have chest pain or pressure, or trouble breathing.",
          "Call 911 if you have severe belly pain that doesn't go away, especially with vomiting.",
          "Call 911 if you have signs of a stroke: a drooping face, weakness in an arm or leg, or trouble speaking.",
        ],
      },
      es: {
        title: "Su peso y su salud",
        whatItIs: "La obesidad es una condición de salud de larga duración en la que el exceso de grasa en el cuerpo afecta la salud. No se debe a falta de fuerza de voluntad. Influyen los genes, el sueño, el estrés, algunas medicinas y el ambiente en el que uno vive.",
        whyItMatters: "El exceso de peso puede aumentar el riesgo de diabetes, presión alta, enfermedades del corazón, apnea del sueño y dolor en las articulaciones. Bajar aunque sea del 5% al 10% de su peso (de 10 a 20 libras si usted pesa 200 libras) puede hacer una gran diferencia.",
        whatYouCanDo: [
          "Póngase metas pequeñas que pueda cumplir, como agregar una verdura a una comida al día o caminar 10 minutos más.",
          "Llene la mitad del plato con verduras, y escoja proteínas bajas en grasa, frijoles y granos integrales.",
          "Tome agua en lugar de refrescos, jugos, té dulce o bebidas de café con azúcar.",
          "Muévase más. Llegue poco a poco a 150 minutos a la semana de actividad, como caminar a paso rápido, y agregue ejercicios para mantener los músculos fuertes.",
          "Trate de dormir de 7 a 8 horas cada noche y busque formas sanas de manejar el estrés.",
          "Lleve un registro de lo que come, de cuánto se mueve o de su peso. A muchas personas les ayuda.",
          "Pregúntenos por un dietista (un experto en alimentación y nutrición), programas para el control del peso y otros tratamientos que puedan ser adecuados para usted.",
        ],
        numbers: [
          "Bajar de peso: trate de bajar del 5% al 10% de su peso en unos 6 meses, o la meta que su proveedor le indique.",
          "Medida de la cintura: menos de 40 pulgadas en los hombres y menos de 35 pulgadas en las mujeres, o la meta que su proveedor le indique.",
          "Actividad: por lo menos 150 minutos a la semana (por ejemplo, 30 minutos 5 días), más ejercicios de fuerza 2 días, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Algunas medicinas pueden hacer que suba de peso. No deje ninguna medicina por su cuenta; mejor pídanos que revisemos su lista.",
          "Si le recetamos una medicina para ayudarle con el peso, tómela tal como se la recetamos, siga comiendo sano y moviéndose, y pregúntenos por los efectos secundarios.",
          "Traiga todos sus frascos de pastillas y suplementos a cada cita. Consúltenos antes de usar cualquier producto para bajar de peso que se venda por internet o en tiendas.",
        ],
        callUs: [
          "Sube o baja mucho de peso rápidamente sin intentarlo.",
          "Se siente triste o sin esperanza, o siente que no puede controlar lo que come.",
          "Ronca muy fuerte, alguien nota que deja de respirar mientras duerme, o tiene mucho sueño durante el día.",
          "Una medicina para el peso le causa náuseas, vómito o estreñimiento que no se quitan.",
        ],
        call911: [
          "Llame al 911 si tiene dolor o presión en el pecho, o dificultad para respirar.",
          "Llame al 911 si tiene un dolor muy fuerte en el abdomen (la barriga) que no se quita, sobre todo si tiene vómito.",
          "Llame al 911 si tiene señales de derrame cerebral: la cara caída de un lado, debilidad en un brazo o una pierna, o dificultad para hablar.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Use respectful, people-first language (for example, 'weight' and 'healthy weight'), and ask permission before talking about weight.",
        "Reinforce that losing 5–10% of body weight brings real health benefits; celebrate small changes in habits, not only the scale.",
        "Review the patient's own eating and activity goals; encourage strength exercises to protect muscle, especially in older adults.",
        "Share available resources: dietitian, weight-management program, diabetes prevention program, and community exercise options such as senior centers.",
        "Do not give individual diet or medicine advice; route questions about weight-loss medicines or surgery to the provider.",
      ],
      ask: [
        "What changes to eating or activity have you tried this month, and how did they go?",
        "What gets in the way of eating the way you'd like, such as cost, time, or access to healthy food?",
        "How are you sleeping, and how has your mood been?",
        "If you take a medicine for weight, how is it going? Any side effects or trouble getting it?",
        "What kind of help would be most useful to you right now?",
      ],
    },
    carePlan: {
      problem: "Obesity, adult (BMI 30 kg/m² or higher), with class and weight-related complications documented by the provider",
      expectedOutcome: "With sustained lifestyle intervention and guideline-directed treatment as appropriate, the patient achieves and maintains clinically meaningful weight reduction with improvement in weight-related conditions and physical function.",
      goals: [
        "Weight reduction of 5–10% of baseline body weight within 6 months, maintained at 12 months (or as individualized by the provider).",
        "Waist circumference reduced toward below 40 inches (men) or below 35 inches (women) (or as individualized by the provider).",
        "At least 150 minutes per week of moderate-intensity activity plus muscle-strengthening on at least 2 days per week, with balance training for older adults (or as individualized by the provider).",
        "Measurable improvement in weight-related conditions (A1C, blood pressure, lipids, sleep apnea symptoms, joint pain) at 6–12 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Weight and BMI at every visit (at least monthly during intensive behavioral therapy) and waist circumference at least every 6 months.",
        "Blood pressure at every visit; A1C or fasting glucose and lipid panel at least every 1–3 years, or more often if abnormal or on treatment.",
        "Liver enzymes and FIB-4 for steatotic liver disease risk at baseline and periodically, per AASLD.",
        "Sleep apnea symptoms (e.g., STOP-Bang) and depression screening (PHQ-2/PHQ-9) at least annually.",
        "In older adults, strength, physical function, and nutrition during weight loss to protect muscle and bone.",
        "Response, side effects, and adherence for anti-obesity medication, if prescribed, at each visit.",
      ],
      interventions: [
        "Intensive behavioral therapy for obesity in primary care (Medicare: weekly in month 1, every other week in months 2–6, then monthly in months 7–12 if at least 3 kg lost).",
        "Nutrition counseling toward a reduced-calorie, nutrient-dense eating pattern with adequate protein; dietitian referral.",
        "Individualized physical activity plan including resistance and balance training, adapted to mobility and joint limitations.",
        "Medication review to minimize weight-promoting medicines where alternatives exist, per provider.",
        "Evaluation for guideline-directed anti-obesity pharmacotherapy or metabolic and bariatric surgery when criteria are met, per provider.",
        "Screening for and addressing social needs (food insecurity, transportation, safe places to be active).",
      ],
      selfManagement: [
        "Follow an agreed eating plan with portion control and fewer sugary drinks and ultra-processed foods.",
        "Build up to 150 minutes per week of moderate activity plus strength exercises twice weekly, as able.",
        "Self-monitor weight weekly and track food and activity with a log or app.",
        "Aim for 7–8 hours of sleep and use stress-management strategies.",
        "Attend scheduled behavioral counseling and follow-up visits.",
      ],
      symptomManagement: [
        "Joint pain limiting activity: adapt the activity plan (water or chair exercise) and refer to physical therapy as needed.",
        "Snoring, witnessed apneas, or daytime sleepiness: notify the provider for sleep apnea evaluation.",
        "GI side effects of anti-obesity medication (nausea, vomiting, constipation): contact the care team; severe persistent abdominal pain needs urgent evaluation for pancreatitis or gallbladder disease.",
        "Low mood, binge eating, or distress related to weight stigma: screen and refer to behavioral health.",
      ],
      coordination: [
        "Registered dietitian (Medicare medical nutrition therapy coverage applies when diabetes or CKD is present).",
        "Weight-management program or obesity medicine specialist; Medicare Diabetes Prevention Program for eligible patients with prediabetes.",
        "Metabolic and bariatric surgery program when criteria are met; sleep medicine and behavioral health as indicated.",
        "Physical therapy and community resources: senior-center or community fitness programs and food assistance.",
      ],
    },
    basis: [
      "AHA/ACC/TOS 2013 Guideline for the Management of Overweight and Obesity in Adults",
      "USPSTF 2018 Recommendation: Behavioral Weight Loss Interventions to Prevent Obesity-Related Morbidity in Adults",
      "Physical Activity Guidelines for Americans, 2nd edition (2018)",
    ],
  },

  // ---------------------------------------------------------------------------------------------
  {
    key: "sleep_apnea",
    education: {
      en: {
        title: "Living with sleep apnea",
        whatItIs: "Sleep apnea means your breathing stops and starts many times while you sleep. Most often, the muscles in your throat relax and block your airway (obstructive sleep apnea). Each time, your body wakes up a little to breathe, so you don't get deep, restful sleep.",
        whyItMatters: "Untreated sleep apnea can leave you sleepy and foggy during the day, and it raises your risk of high blood pressure, heart problems, stroke, and car crashes. Treatment can help you sleep better and feel more alert.",
        whatYouCanDo: [
          "If you have a CPAP machine (a machine that gently blows air through a mask to keep your airway open), use it every night, all night, and when you nap.",
          "Clean your mask, tubing, and water tank the way the instructions say, and replace supplies on schedule.",
          "If your mask leaks, hurts, or dries out your nose or mouth, call us or your equipment company. A different mask or setting can help.",
          "Try sleeping on your side if sleeping on your back makes it worse.",
          "Avoid alcohol and sleeping pills near bedtime. They relax your throat and make sleep apnea worse.",
          "Aim for a healthy weight. For many people, losing weight makes sleep apnea better.",
          "Don't drive if you feel drowsy. Pull over and rest.",
        ],
        numbers: [
          "CPAP use: all night, every night. At the least, 4 hours or more a night on at least 70% of nights (about 5 nights a week), or the goal your provider sets for you.",
          "Breathing pauses on your CPAP report (called AHI, the number of pauses per hour): usually under 5, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicines as prescribed, and don't stop any medicine without talking to us.",
          "Some medicines, like sleeping pills, strong pain medicines, and some anxiety medicines, can make sleep apnea worse. Ask us before taking anything that makes you sleepy.",
          "If you need surgery or a procedure where you are put to sleep, tell the team you have sleep apnea, and bring your CPAP with you.",
          "Bring all your pill bottles to every visit, and ask us about side effects.",
        ],
        callUs: [
          "You are still very sleepy during the day, even when you use your CPAP.",
          "You have trouble using your CPAP because of mask problems, a dry or stuffy nose, or air in your stomach.",
          "Your machine stops working, or you need new supplies and don't know where to get them.",
          "Your snoring comes back, or someone sees you stop breathing in your sleep again.",
          "You wake up with headaches, or your mood or memory is getting worse.",
        ],
        call911: [
          "Call 911 if you have chest pain, trouble breathing, or a racing or uneven heartbeat.",
          "Call 911 if you are very confused or very hard to wake up. A family member may need to make this call.",
          "Call 911 if you have signs of a stroke: a drooping face, weakness in an arm or leg, or trouble speaking.",
        ],
      },
      es: {
        title: "Cómo vivir con apnea del sueño",
        whatItIs: "La apnea del sueño significa que la respiración se detiene y vuelve a empezar muchas veces mientras usted duerme. Casi siempre pasa porque los músculos de la garganta se aflojan y tapan el paso del aire (apnea obstructiva del sueño). Cada vez, el cuerpo se despierta un poco para respirar, y por eso usted no logra un sueño profundo y reparador.",
        whyItMatters: "Sin tratamiento, la apnea del sueño puede causarle sueño y falta de concentración durante el día, y aumenta el riesgo de presión alta, problemas del corazón, derrame cerebral y accidentes de tránsito. El tratamiento le ayuda a dormir mejor y a sentirse más alerta.",
        whatYouCanDo: [
          "Si tiene una máquina CPAP (una máquina que sopla aire suavemente por una mascarilla para mantener abiertas las vías respiratorias), úsela todas las noches, toda la noche, y también cuando tome siestas.",
          "Limpie la mascarilla, la manguera y el depósito de agua como dicen las instrucciones, y cambie los repuestos cuando les toque.",
          "Si la mascarilla tiene fugas de aire, le lastima o le reseca la nariz o la boca, llámenos o llame a la compañía del equipo. Otra mascarilla u otro ajuste le puede ayudar.",
          "Trate de dormir de lado si dormir boca arriba le empeora la apnea.",
          "Evite el alcohol y las pastillas para dormir cerca de la hora de acostarse. Aflojan la garganta y empeoran la apnea del sueño.",
          "Procure llegar a un peso saludable. En muchas personas, bajar de peso mejora la apnea del sueño.",
          "No maneje si tiene sueño. Oríllese y descanse.",
        ],
        numbers: [
          "Uso del CPAP: toda la noche, todas las noches. Como mínimo, 4 horas o más por noche en al menos el 70% de las noches (unas 5 noches por semana), o la meta que su proveedor le indique.",
          "Pausas en la respiración según el informe de su CPAP (en el informe aparece como AHI, el número de pausas por hora): por lo general menos de 5, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas como se las recetaron y no deje ninguna sin hablar antes con nosotros.",
          "Algunas medicinas, como las pastillas para dormir, los analgésicos fuertes y ciertas medicinas para la ansiedad, pueden empeorar la apnea del sueño. Pregúntenos antes de tomar cualquier cosa que le dé sueño.",
          "Si necesita una cirugía o un procedimiento con anestesia, avísele al equipo que tiene apnea del sueño y lleve su CPAP.",
          "Traiga todos sus frascos de pastillas a cada cita, y pregúntenos por los efectos secundarios.",
        ],
        callUs: [
          "Sigue con mucho sueño durante el día, aunque use su CPAP.",
          "Le cuesta usar el CPAP por problemas con la mascarilla, la nariz seca o tapada, o aire en el estómago.",
          "Su máquina deja de funcionar, o necesita repuestos y no sabe dónde conseguirlos.",
          "Vuelve a roncar, o alguien nota otra vez que deja de respirar mientras duerme.",
          "Se despierta con dolor de cabeza, o siente que su ánimo o su memoria están empeorando.",
        ],
        call911: [
          "Llame al 911 si tiene dolor en el pecho, dificultad para respirar o el corazón le late muy rápido o de forma irregular.",
          "Llame al 911 si tiene mucha confusión o es muy difícil hacer que se despierte. Puede que un familiar tenga que hacer la llamada.",
          "Llame al 911 si tiene señales de derrame cerebral: la cara caída de un lado, debilidad en un brazo o una pierna, o dificultad para hablar.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Reinforce CPAP use all night, every night, including naps; Medicare requires at least 4 hours a night on 70% of nights in a 30-day period during the first 3 months to keep covering the device.",
        "Troubleshoot common barriers (mask fit, leaks, dryness, feeling closed in) and connect the patient with the equipment supplier or sleep clinic for refitting; never change pressure settings.",
        "Remind the patient of cleaning steps and the insurance supply-replacement schedule.",
        "Reinforce avoiding alcohol and sedating medicines near bedtime, and not driving when drowsy.",
        "Encourage weight-management efforts and side sleeping when the provider has recommended it.",
      ],
      ask: [
        "How many nights this week did you use your CPAP, and for about how many hours?",
        "What makes it hard to use your CPAP? Any trouble with the mask, leaks, or dryness?",
        "How sleepy do you feel during the day, especially when driving or sitting quietly?",
        "When did you last get new supplies, and do you know who to call for them?",
      ],
    },
    carePlan: {
      problem: "Obstructive sleep apnea (OSA), adult, with severity per diagnostic sleep study (AHI)",
      expectedOutcome: "With consistent PAP use or alternative guideline-directed therapy, sleep-disordered breathing is controlled, daytime sleepiness and quality of life improve, and related cardiovascular and accident risks are reduced.",
      goals: [
        "PAP use at least 4 hours per night on at least 70% of nights, working toward use during all sleep (or as individualized by the provider).",
        "Residual AHI below 10 events per hour, ideally below 5, on device download (or as individualized by the provider).",
        "Epworth Sleepiness Scale score of 10 or lower within 3 months of starting therapy (or as individualized by the provider).",
        "Blood pressure at the individualized goal in patients with coexisting hypertension (or as individualized by the provider).",
      ],
      monitoring: [
        "PAP adherence, residual AHI, and leak from device download 30–90 days after starting therapy (Medicare requires a face-to-face re-evaluation between days 31 and 91), then at least annually.",
        "Epworth Sleepiness Scale and symptom review at each visit, at least annually.",
        "Blood pressure and weight at every visit.",
        "Drowsy-driving risk, alcohol use, and sedating medicines at each visit.",
        "Repeat sleep testing or PAP re-titration after significant weight change (about 10% or more), with persistent symptoms, or to assess alternative therapy, per provider.",
      ],
      interventions: [
        "Guideline-directed OSA treatment per provider: PAP as first line; oral appliance therapy, positional therapy, or surgical evaluation (including hypoglossal nerve stimulation) for PAP-intolerant patients.",
        "Early PAP education and troubleshooting within the first 1–2 weeks (mask fit, humidification, pressure tolerance), coordinated with the DME supplier.",
        "Weight-management counseling and treatment per provider for patients with overweight or obesity.",
        "Counseling to avoid alcohol and sedating medicines near bedtime and on drowsy-driving risk.",
        "Document OSA and PAP use prominently in the chart for perioperative and procedural sedation planning.",
      ],
      selfManagement: [
        "Use PAP all night, every night, including naps.",
        "Clean equipment and replace supplies on schedule; report mask or comfort problems early.",
        "Avoid alcohol and sedating medicines before bed, and do not drive when drowsy.",
        "Work toward a healthy weight, and sleep on the side if the provider has advised positional therapy.",
      ],
      symptomManagement: [
        "Persistent daytime sleepiness despite adherence: review the device download and refer to sleep medicine.",
        "Mask discomfort, leaks, nasal dryness or congestion, or aerophagia: contact the DME supplier or sleep clinic for refitting and settings review by the prescriber.",
        "Chest pain, new palpitations, severe confusion, or stroke signs: call 911.",
      ],
      coordination: [
        "Sleep medicine for diagnosis (in-lab or home sleep apnea testing), PAP titration, and management of PAP intolerance or complex cases.",
        "DME supplier for PAP device, mask fitting, supply replacement, and adherence data access.",
        "Dentist trained in dental sleep medicine for oral appliance therapy; ENT for anatomic evaluation; weight-management program as indicated.",
      ],
    },
    basis: [
      "AASM Clinical Practice Guideline for the Treatment of Adult OSA with PAP (2019)",
      "AASM Clinical Practice Guideline on Referral of Adults with OSA for Surgical Consultation (2021)",
      "CMS National Coverage Determination 240.4 (CPAP Therapy for OSA)",
    ],
  },

  // ---------------------------------------------------------------------------------------------
  {
    key: "liver",
    education: {
      en: {
        title: "Living with chronic liver disease",
        whatItIs: "Your liver cleans your blood, helps digest food, and stores energy. Chronic liver disease means your liver has been hurt over a long time, most often by extra fat in the liver (fatty liver), a virus (hepatitis B or C), or alcohol. Over time this can cause scarring, and heavy scarring is called cirrhosis.",
        whyItMatters: "Many people feel fine until the liver is badly damaged. Treating the cause early can stop or even reverse some of the damage and lower your risk of liver failure and liver cancer.",
        whatYouCanDo: [
          "Do not drink alcohol. Even small amounts can hurt a damaged liver.",
          "If you have fatty liver and extra weight, losing 5% to 10% of your weight, slowly, can help your liver heal.",
          "Eat vegetables, fruits, whole grains, and lean protein. Limit sugary drinks and fried or processed foods. Stay active most days.",
          "If you have cirrhosis, eat small meals often, including a bedtime snack. Ask us how much salt and protein you need, and never eat raw oysters or other raw shellfish.",
          "Check with us before taking any new medicine, vitamin, herbal product, or supplement. Some can harm the liver.",
          "Ask us about hepatitis A and B shots and other vaccines that protect your liver and your health.",
          "If you have hepatitis B or C, don't share razors, toothbrushes, or needles, and cover any cuts, so you don't spread the virus.",
        ],
        numbers: [
          "Weight, if you have fatty liver and extra weight: lose 5% to 10% of your weight over time, or the goal your provider sets for you.",
          "A1C (your average blood sugar over 3 months), if you also have diabetes: usually under 7% to 8%, depending on your health, or the goal your provider sets for you.",
          "Liver cancer check, if you have cirrhosis: an ultrasound (a painless picture test), often with a blood test, every 6 months, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicines exactly as prescribed. If you are being treated for hepatitis B or C, don't skip doses, so the treatment can work.",
          "Acetaminophen (a common pain and fever reliever) can be used by many people with liver disease, but only up to a lower daily limit. Ask us how much is safe for you, and read labels, because many cold and flu products also contain it.",
          "If you have cirrhosis, don't take pain relievers like ibuprofen or naproxen unless we say it is OK. They can harm your kidneys and cause bleeding. Also ask us before taking sleeping pills or strong pain medicines.",
          "Don't stop any medicine without talking to us. Bring all your pill bottles, vitamins, and herbal products to every visit, and ask us about side effects.",
        ],
        callUs: [
          "Your skin or the whites of your eyes turn yellow.",
          "Your belly or legs are more swollen, or you gain weight quickly.",
          "You are more forgetful, confused, or sleepy than usual, or you sleep in the day and can't sleep at night.",
          "You have a fever or belly pain, especially if your belly is swollen. Call us right away.",
          "You bruise or bleed more easily than usual, or your urine turns dark.",
        ],
        call911: [
          "Call 911 if you vomit blood or something that looks like coffee grounds.",
          "Call 911 if your stool is black and sticky like tar, or there is a lot of blood in it.",
          "Call 911 if you are very confused, very sleepy, or very hard to wake up.",
          "Call 911 if you feel like you are going to pass out, or you do pass out.",
        ],
      },
      es: {
        title: "Cómo vivir con una enfermedad crónica del hígado",
        whatItIs: "El hígado limpia la sangre, ayuda a digerir los alimentos y guarda energía. Tener una enfermedad crónica del hígado significa que el hígado se ha ido dañando durante mucho tiempo, casi siempre por exceso de grasa en el hígado (hígado graso), por un virus (hepatitis B o C) o por el alcohol. Con el tiempo esto puede dejar cicatrices, y cuando hay muchas cicatrices se le llama cirrosis.",
        whyItMatters: "Muchas personas se sienten bien hasta que el hígado ya está muy dañado. Tratar la causa a tiempo puede detener y hasta revertir parte del daño, y baja el riesgo de que el hígado deje de funcionar o de que aparezca cáncer de hígado.",
        whatYouCanDo: [
          "No tome alcohol. Aun en poca cantidad puede dañar un hígado enfermo.",
          "Si tiene hígado graso y peso de más, bajar poco a poco del 5% al 10% de su peso puede ayudar a que su hígado sane.",
          "Coma verduras, frutas, granos integrales y proteínas bajas en grasa. Limite las bebidas azucaradas y los alimentos fritos o procesados. Manténgase en movimiento la mayoría de los días.",
          "Si tiene cirrosis, coma porciones pequeñas varias veces al día, incluso un refrigerio antes de dormir. Pregúntenos cuánta sal y cuánta proteína necesita, y nunca coma ostiones ni otros mariscos crudos.",
          "Consúltenos antes de tomar cualquier medicina, vitamina, producto de hierbas o suplemento nuevo. Algunos pueden dañar el hígado.",
          "Pregúntenos por las vacunas contra la hepatitis A y B, y otras que protegen su hígado y su salud.",
          "Si tiene hepatitis B o C, no comparta rasuradoras, cepillos de dientes ni agujas, y cúbrase las heridas para no contagiar el virus.",
        ],
        numbers: [
          "Peso, si tiene hígado graso y peso de más: bajar del 5% al 10% de su peso con el tiempo, o la meta que su proveedor le indique.",
          "A1C (su promedio de azúcar en la sangre de los últimos 3 meses), si también tiene diabetes: por lo general menos de 7% a 8%, según su salud, o la meta que su proveedor le indique.",
          "Revisión para detectar cáncer de hígado, si tiene cirrosis: un ultrasonido (un estudio de imágenes que no duele), muchas veces junto con un análisis de sangre, cada 6 meses, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas exactamente como se las recetaron. Si recibe tratamiento para la hepatitis B o C, no se salte ninguna dosis, para que el tratamiento funcione.",
          "Muchas personas con enfermedad del hígado pueden tomar acetaminofén (una medicina común para el dolor y la fiebre), pero solo hasta un límite diario más bajo. Pregúntenos cuánto es seguro para usted y lea las etiquetas, porque muchos productos para la gripe y el resfriado también lo contienen.",
          "Si tiene cirrosis, no tome analgésicos como el ibuprofeno o el naproxeno a menos que le digamos que puede, porque pueden dañar los riñones y causar sangrado. Pregúntenos también antes de tomar pastillas para dormir o medicinas fuertes para el dolor.",
          "No deje ninguna medicina sin hablar antes con nosotros. Traiga todos sus frascos de pastillas, vitaminas y productos de hierbas a cada cita, y pregúntenos por los efectos secundarios.",
        ],
        callUs: [
          "La piel o lo blanco de los ojos se le pone amarillo.",
          "Tiene la barriga o las piernas más hinchadas, o sube de peso rápido.",
          "Tiene más olvidos, confusión o sueño que de costumbre, o duerme de día y no puede dormir de noche.",
          "Tiene fiebre o dolor de barriga, sobre todo si la tiene hinchada. Llámenos de inmediato.",
          "Le salen moretones o sangra con más facilidad que de costumbre, o la orina se le pone oscura.",
        ],
        call911: [
          "Llame al 911 si vomita sangre o algo que parece café molido.",
          "Llame al 911 si sus heces (popó) son negras y pegajosas como el alquitrán, o tienen mucha sangre.",
          "Llame al 911 si tiene mucha confusión, mucho sueño o es muy difícil hacer que se despierte.",
          "Llame al 911 si siente que se va a desmayar o si se desmaya.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Reinforce avoiding all alcohol, and offer support resources if the patient wants help cutting down or stopping.",
        "Remind the patient to check with the care team before any new medicine, supplement, or herbal product and to ask the provider for their safe acetaminophen limit; patients with cirrhosis should avoid ibuprofen and naproxen.",
        "For fatty liver, encourage gradual weight loss, healthy eating, and daily activity; offer a dietitian or weight-management referral.",
        "For cirrhosis, confirm the patient knows about the liver ultrasound every 6 months and help schedule it; reinforce the bedtime snack and any salt limit the provider set.",
        "Check vaccine status (hepatitis A and B, flu, pneumonia, COVID-19) and flag gaps to the provider.",
      ],
      ask: [
        "How much alcohol, if any, have you had in the past month?",
        "What over-the-counter pain relievers, vitamins, herbs, or supplements are you taking?",
        "Have you noticed yellow skin or eyes, swelling in your belly or legs, confusion, or black stools?",
        "When was your last liver ultrasound or blood test, and is the next one scheduled?",
        "Is anything making it hard to take your medicines or get to your appointments?",
      ],
    },
    carePlan: {
      problem: "Chronic liver disease (etiology per provider: MASLD/MASH, chronic hepatitis B or C, or alcohol-associated liver disease), with or without cirrhosis",
      expectedOutcome: "With treatment of the underlying cause, risk-factor control, and surveillance, liver disease progression is halted or slowed, fibrosis may regress, and complications of cirrhosis are prevented or detected early.",
      goals: [
        "Complete alcohol abstinence for patients with cirrhosis, alcohol-associated liver disease, or MASLD with significant fibrosis (or as individualized by the provider).",
        "For MASLD with overweight or obesity: 7–10% body weight loss within 12 months, with at least 5% to reduce liver fat (or as individualized by the provider).",
        "For chronic hepatitis C: sustained virologic response (undetectable HCV RNA 12 weeks after treatment); for chronic hepatitis B on treatment: HBV DNA suppressed to undetectable (or as individualized by the provider).",
        "For cirrhosis: hepatocellular carcinoma surveillance completed every 6 months with no missed intervals, and no decompensating events (ascites, variceal bleeding, encephalopathy) over 12 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Liver panel (ALT, AST, bilirubin, albumin), CBC with platelets, and INR every 6–12 months, or every 3–6 months in cirrhosis.",
        "Noninvasive fibrosis assessment in MASLD: FIB-4 at baseline and every 1–3 years; vibration-controlled transient elastography or ELF test if FIB-4 is 1.3 or higher (a cutoff of 2.0 is often used at age 65 or older).",
        "Hepatocellular carcinoma surveillance with ultrasound, with or without AFP, every 6 months in cirrhosis and in selected chronic hepatitis B patients without cirrhosis.",
        "Hepatitis B: HBV DNA and ALT every 3–6 months on treatment and every 6–12 months when inactive; hepatitis C: HCV RNA 12 weeks after treatment to confirm cure, with continued surveillance if advanced fibrosis.",
        "Varices screening in compensated cirrhosis by endoscopy or noninvasive criteria (Baveno VII), as directed by hepatology.",
        "Metabolic risk factors (A1C, lipids, blood pressure, weight) at least yearly in MASLD; alcohol use (AUDIT-C) at each visit.",
      ],
      interventions: [
        "Treat the underlying cause per provider and hepatology: guideline-directed antiviral therapy for hepatitis B or C, alcohol use disorder treatment, and guideline-directed MASH therapy when indicated.",
        "Lifestyle counseling: alcohol abstinence, calorie-reduced Mediterranean-style eating pattern, and at least 150 minutes per week of physical activity.",
        "Medication safety review at every visit: acetaminophen limit set by the provider, avoid NSAIDs and use sedatives cautiously in cirrhosis, and review herbal and dietary supplements.",
        "Vaccinations per CDC/ACIP: hepatitis A and B if not immune, annual influenza, pneumococcal, COVID-19, and zoster.",
        "Cirrhosis nutrition per provider: avoid prolonged fasting (late-evening snack), adequate protein intake, and sodium restriction if ascites is present.",
        "Hepatitis B or C: counsel on preventing transmission and arrange testing and vaccination of household and sexual contacts as indicated.",
      ],
      selfManagement: [
        "Abstain from alcohol.",
        "Take medications as prescribed and check with the care team before any over-the-counter medicine, herbal product, or supplement.",
        "Follow the individualized eating plan and activity goals, with gradual weight loss if MASLD.",
        "Keep lab, imaging, and 6-month surveillance appointments.",
        "Recognize and promptly report warning signs (jaundice, abdominal swelling, confusion, black stools, vomiting blood).",
      ],
      symptomManagement: [
        "Increasing abdominal girth, leg edema, or rapid weight gain: same-day contact with the care team to evaluate for ascites.",
        "Fever or abdominal pain with ascites: urgent same-day evaluation for spontaneous bacterial peritonitis (ED if not available).",
        "Confusion, sleep-wake reversal, or excessive drowsiness: urgent provider contact for hepatic encephalopathy evaluation; call 911 if severe.",
        "Hematemesis, melena, or hematochezia: call 911 (possible variceal bleeding).",
      ],
      coordination: [
        "Hepatology or gastroenterology for cirrhosis, FIB-4 or elastography suggesting advanced fibrosis, chronic hepatitis B or C needing treatment, abnormal surveillance imaging, or any decompensation; transplant evaluation when MELD is 15 or higher or after decompensation.",
        "Addiction medicine, behavioral health, and peer-support programs for alcohol use disorder.",
        "Registered dietitian for MASLD weight loss or cirrhosis nutrition (malnutrition and muscle loss).",
        "Radiology for 6-month surveillance imaging; endoscopy for varices as directed by hepatology.",
      ],
    },
    basis: [
      "AASLD Practice Guidance on the Clinical Assessment and Management of MASLD (2023)",
      "AASLD Practice Guidance on Prevention, Diagnosis, and Treatment of Hepatocellular Carcinoma (2023)",
      "AASLD-IDSA HCV Guidance and AASLD Chronic Hepatitis B Guidance",
    ],
  },
];
