// Condition library, group A: diabetes and the heart and blood-vessel conditions. DRAFT content until a
// provider approves it in MyPCP (Care plans & education). Written in our own words; targets follow the
// guidelines named in each entry's basis, and every patient-facing number defers to the provider's goal.
import type { ConditionLibraryEntry } from "./types";

export const GROUP_A: ConditionLibraryEntry[] = [
  // ---------------------------------------------------------------------------------------------------
  {
    key: "diabetes",
    education: {
      en: {
        title: "Living with diabetes",
        whatItIs: "Diabetes means there is too much sugar in your blood. Your body uses sugar for energy, but it needs a hormone called insulin to move the sugar into your cells. With diabetes, your body does not make enough insulin or does not use it well.",
        whyItMatters: "Over time, high blood sugar can harm your eyes, kidneys, nerves, feet, and heart. Keeping your sugar in a healthy range lowers these risks and helps you feel better day to day.",
        whatYouCanDo: [
          "Check your blood sugar as often as your care team tells you, and write down the numbers or keep them in your meter.",
          "Fill half your plate with vegetables, one quarter with lean protein (like chicken, fish, or beans), and one quarter with whole grains or starchy foods.",
          "Drink water instead of soda, juice, or sweet tea.",
          "Move your body most days. A 10-minute walk after meals can help lower your blood sugar.",
          "Look at your feet every day for cuts, blisters, or color changes. Wear shoes or slippers, even at home.",
          "If you smoke, ask us for help quitting. It is never too late.",
          "Get your eyes checked every year, and keep your lab appointments.",
        ],
        numbers: [
          "A1c (your average blood sugar over the past 3 months): below 7% for many adults and below 8% for some older adults, or the goal your provider sets for you.",
          "Blood sugar before meals: 80 to 130, or the goal your provider sets for you.",
          "Blood sugar 1 to 2 hours after you start eating: below 180, or the goal your provider sets for you.",
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your diabetes medicines exactly as prescribed, even when you feel fine.",
          "Do not stop or change a medicine without talking to us first.",
          "If you use insulin or a diabetes pill that can make your sugar drop, know the signs of low blood sugar: shaky, sweaty, fast heartbeat, hungry, or confused. If your sugar is below 70, drink half a cup of juice or regular (not diet) soda, wait 15 minutes, and check again. Repeat if it is still low.",
          "Bring all your medicine bottles, your insulin, and your meter to every visit, and tell us about any side effects.",
        ],
        callUs: [
          "Your blood sugar is over 300 two times in a row, or higher than the number your provider gave you.",
          "You have low blood sugar (below 70) more than once a week, or someone had to help you treat a low.",
          "You are sick, throwing up, or cannot eat like you usually do. Some medicines need to be changed on sick days.",
          "You have a sore, blister, or cut on your foot that is not healing, or your foot looks red, swollen, or warm.",
          "Your vision is blurry, or you have new numbness, tingling, or burning in your feet or hands.",
        ],
        call911: [
          "Low blood sugar does not get better after you treat it twice, or the person is confused, passes out, or has a seizure. Never put food or drink in the mouth of someone who has passed out.",
          "You have high blood sugar with throwing up, stomach pain, fast or deep breathing, fruity-smelling breath, or confusion.",
          "You have signs of a heart attack: chest pain, pressure, or squeezing; pain in the arm, back, neck, jaw, or stomach; shortness of breath; cold sweat; nausea; or lightheadedness.",
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911.",
        ],
      },
      es: {
        title: "Cómo vivir bien con diabetes",
        whatItIs: "Tener diabetes quiere decir que hay demasiada azúcar en la sangre. El cuerpo usa el azúcar para tener energía, pero necesita una hormona llamada insulina para que el azúcar entre en las células. Con la diabetes, el cuerpo no produce suficiente insulina o no la aprovecha bien.",
        whyItMatters: "Con el tiempo, el azúcar alto puede dañar los ojos, los riñones, los nervios, los pies y el corazón. Mantener el azúcar en un buen nivel baja estos riesgos y le ayuda a sentirse mejor cada día.",
        whatYouCanDo: [
          "Mídase el azúcar con la frecuencia que le indique su equipo de salud, y anote los resultados o guárdelos en su medidor.",
          "Llene la mitad del plato con verduras, una cuarta parte con proteína baja en grasa (como pollo, pescado o frijoles) y la otra cuarta parte con granos integrales o almidones.",
          "Tome agua en vez de refrescos, jugos o té endulzado.",
          "Muévase la mayoría de los días. Caminar 10 minutos después de comer ayuda a bajar el azúcar.",
          "Revísese los pies todos los días por si hay cortaduras, ampollas o cambios de color. Use zapatos o pantuflas, aun dentro de la casa.",
          "Si fuma, pídanos ayuda para dejarlo. Nunca es tarde.",
          "Hágase un examen de la vista cada año y no falte a sus citas de laboratorio.",
        ],
        numbers: [
          "A1c (el promedio de su azúcar en los últimos 3 meses): menos de 7% para muchos adultos y menos de 8% para algunos adultos mayores, o la meta que su proveedor le indique.",
          "Azúcar antes de comer: entre 80 y 130, o la meta que su proveedor le indique.",
          "Azúcar de 1 a 2 horas después de empezar a comer: menos de 180, o la meta que su proveedor le indique.",
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas para la diabetes tal como se las recetaron, aunque se sienta bien.",
          "No deje ni cambie ninguna medicina sin hablar antes con nosotros.",
          "Si usa insulina o una pastilla para la diabetes que puede bajarle el azúcar, conozca las señales del azúcar bajo: temblor, sudor, latidos rápidos, hambre o confusión. Si su azúcar está por debajo de 70, tome media taza de jugo o de refresco regular (no de dieta), espere 15 minutos y vuelva a medirse. Repita si sigue bajo.",
          "Traiga todos sus frascos de medicina, su insulina y su medidor a cada cita, y avísenos si tiene algún efecto secundario.",
        ],
        callUs: [
          "Su azúcar sale en más de 300 dos veces seguidas, o más alto que el número que le dio su proveedor.",
          "Tiene el azúcar bajo (menos de 70) más de una vez por semana, o alguien tuvo que ayudarle a tratar un bajón de azúcar.",
          "Tiene alguna enfermedad, vómitos o no puede comer como de costumbre. Algunas medicinas se deben ajustar en los días de enfermedad.",
          "Tiene una llaga, ampolla o cortadura en el pie que no sana, o el pie se ve rojo, hinchado o caliente.",
          "Ve borroso, o siente adormecimiento, hormigueo o ardor nuevo en los pies o las manos.",
        ],
        call911: [
          "Un bajón de azúcar no mejora después de tratarlo dos veces, o la persona está confundida, se desmaya o tiene una convulsión. Nunca le dé de comer ni de beber a alguien que está desmayado.",
          "Tiene el azúcar alto junto con vómitos, dolor de estómago, respiración rápida o profunda, aliento con olor a fruta o confusión.",
          "Tiene señales de un ataque al corazón: dolor, presión o apretón en el pecho; dolor en el brazo, la espalda, el cuello, la mandíbula o el estómago; falta de aire; sudor frío; náuseas o mareo.",
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Review the patient's own A1c and blood sugar goals from the care plan, and praise any progress.",
        "Reinforce the signs of low blood sugar and the routine: if below 70, half a cup of juice or regular soda, wait 15 minutes, recheck.",
        "Remind the patient to check both feet every day and to call about any sore that is not healing.",
        "Encourage the plate method, water instead of sugary drinks, and a short walk after meals.",
        "Remind them to bring their meter or log, all medicine bottles, and insulin to every visit.",
        "Check that the yearly eye exam, kidney urine test, and foot exam are done or scheduled, and offer to help book them.",
      ],
      ask: [
        "How have your blood sugar numbers been this month? What were your highest and lowest readings?",
        "Have you had any low blood sugar spells? What happened, and what did you do?",
        "Are you able to take all your diabetes medicines as prescribed? Is anything getting in the way, like cost, side effects, or remembering?",
        "Have you noticed any sores, numbness, or changes in your feet or your vision?",
        "Do you have your eye exam, lab work, and next visit scheduled, and do you have a ride?",
      ],
    },
    carePlan: {
      problem: "Type 2 diabetes mellitus (provider to confirm type and document any complications)",
      expectedOutcome: "Stable with treatment; goal is to reach individualized glycemic targets and prevent complications, hypoglycemia, and hospital visits.",
      goals: [
        "A1c <7.0% for most adults; <8.0% for older adults with multiple chronic conditions, cognitive impairment, or high hypoglycemia risk (or as individualized by the provider)",
        "No severe hypoglycemia and no glucose readings <54 mg/dL; if using CGM, time in range 70–180 mg/dL >70% with <4% below 70 mg/dL (>50% and <1% for older or high-risk adults) (or as individualized by the provider)",
        "Blood pressure <130/80 mmHg (or as individualized by the provider)",
        "LDL-C <70 mg/dL for adults 40–75 with additional cardiovascular risk factors; <55 mg/dL with established ASCVD (or as individualized by the provider)",
      ],
      monitoring: [
        "A1c every 3 months until at goal or after a therapy change, then every 6 months when stable",
        "Home glucose log or CGM data, hypoglycemia events, and home BP reviewed on each monthly CCM call; BP at every office visit",
        "Annual urine albumin-to-creatinine ratio (UACR) and eGFR (every 3–6 months if CKD is present)",
        "Lipid panel annually, and 4–12 weeks after starting or changing lipid-lowering therapy",
        "Annual dilated retinal eye exam (eye care may extend to every 1–2 years if no retinopathy and glycemia is at goal)",
        "Comprehensive foot exam at least annually (monofilament, pulses, skin); visual foot inspection at every visit if high risk",
      ],
      interventions: [
        "Medication reconciliation at every care transition and on monthly CCM calls; adherence support (pill organizer, refill synchronization) and cost or access problem-solving",
        "Provider reviews monitoring data and adjusts guideline-directed glucose-lowering, cardiorenal-protective, BP, and lipid therapy per provider",
        "Hypoglycemia education and a written action plan for patients on insulin or insulin secretagogues; hypoglycemia rescue plan per provider",
        "Remote patient monitoring (connected glucometer or BP cuff) when appropriate",
        "Screen for depression, diabetes distress, cognitive impairment, and social needs (food insecurity, transportation); confirm vaccines are current per the CDC adult schedule",
      ],
      selfManagement: [
        "Check blood glucose (or wear CGM) as directed and keep a log for CCM calls",
        "Follow a plate-method, consistent-carbohydrate meal plan and replace sugary drinks with water",
        "At least 150 minutes/week of moderate activity plus strength exercises 2 days/week, as able",
        "Inspect feet daily and wear protective footwear",
        "Take medicines as prescribed and avoid tobacco",
      ],
      symptomManagement: [
        "Hypoglycemia (<70 mg/dL or symptoms): 15 g fast-acting carbohydrate, recheck in 15 minutes, repeat until >70 mg/dL, then a snack or meal; report every level 2 (<54 mg/dL) or severe event for regimen review",
        "Hyperglycemia (>300 mg/dL twice in a row) or acute illness: follow the sick-day plan, maintain fluids, and contact the office the same day; emergency care for vomiting, inability to keep fluids down, confusion, or rapid breathing",
        "Foot wound, ulcer, or signs of infection: same-day or next-day evaluation and podiatry or wound-care referral",
        "New vision changes or neuropathic symptoms: notify the provider and expedite eye or foot follow-up",
      ],
      coordination: [
        "Diabetes self-management education and support (DSMES) and medical nutrition therapy with a registered dietitian (Medicare-covered benefits)",
        "Ophthalmology or optometry for the annual retinal exam; podiatry for high-risk feet",
        "Endocrinology if not at goal despite therapy or on a complex insulin regimen; nephrology if eGFR <30 mL/min/1.73 m², rapidly declining eGFR, or rising albuminuria",
        "Community resources: food assistance programs, medication-cost assistance, and transportation",
      ],
    },
    basis: ["ADA Standards of Care in Diabetes (2025)", "CDC Adult Immunization Schedule"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "hypertension",
    education: {
      en: {
        title: "Living with high blood pressure",
        whatItIs: "Blood pressure is the force of blood pushing on the walls of your blood vessels. High blood pressure means this force stays too high. Most people with high blood pressure feel fine, so checking it is the only way to know.",
        whyItMatters: "Over time, high blood pressure can damage your heart, brain, kidneys, and eyes. It raises your chance of a heart attack, stroke, and kidney disease, but keeping it under control lowers these risks a lot.",
        whatYouCanDo: [
          "Check your blood pressure at home and write down the numbers. First sit quietly for 5 minutes with your back supported, feet flat, and arm resting at heart level.",
          "Eat less salt. Choose fresh foods and cut back on canned soups, chips, deli meats, and fast food.",
          "Eat more fruits, vegetables, beans, and whole grains.",
          "Move your body about 30 minutes most days, like walking or dancing.",
          "Limit alcohol, and if you smoke, ask us for help quitting.",
          "Aim for a healthy weight. Losing even a few pounds can help.",
          "Tell us if you snore loudly or feel sleepy during the day. Poor sleep can raise blood pressure.",
        ],
        numbers: [
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
          "Salt (sodium): less than 1,500 mg a day if you can, or the goal your provider sets for you.",
          "Activity: about 150 minutes a week, like 30 minutes on 5 days, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your blood pressure medicine every day as prescribed, even when you feel fine.",
          "Do not skip doses or stop a medicine without talking to us first. Stopping some medicines suddenly can make your pressure shoot up.",
          "Tell us about side effects like dizziness, swelling, or a cough. We can often find a better choice for you.",
          "Bring all your medicine bottles to every visit. Ask us before taking cold or pain medicines from the store, since some can raise blood pressure.",
        ],
        callUs: [
          "Your blood pressure is 180/120 or higher, you feel OK, and it is still that high after you rest 5 minutes and check again.",
          "Most of your readings are above your goal for a week or more.",
          "You feel dizzy or lightheaded, especially when you stand up, or you have fallen.",
          "You have side effects, or you cannot afford or get your medicine.",
        ],
        call911: [
          "Your blood pressure is 180/120 or higher and you have chest pain, trouble breathing, back pain, numbness or weakness, a very bad headache, trouble speaking, or changes in your vision.",
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911.",
          "You have signs of a heart attack: chest pain, pressure, or squeezing; pain in the arm, back, neck, jaw, or stomach; shortness of breath; cold sweat; nausea; or lightheadedness.",
        ],
      },
      es: {
        title: "Cómo vivir bien con la presión alta",
        whatItIs: "La presión arterial es la fuerza con la que la sangre empuja las paredes de los vasos sanguíneos. Tener la presión alta quiere decir que esa fuerza se mantiene demasiado alta. La mayoría de las personas con presión alta se sienten bien, por eso medirla es la única forma de saberlo.",
        whyItMatters: "Con el tiempo, la presión alta puede dañar el corazón, el cerebro, los riñones y los ojos. Aumenta el riesgo de un ataque al corazón, un derrame cerebral y enfermedad de los riñones, pero tenerla bajo control baja mucho ese riesgo.",
        whatYouCanDo: [
          "Mídase la presión en casa y anote los números. Antes, descanse 5 minutos en una silla, con la espalda apoyada, los pies en el piso y el brazo descansando a la altura del corazón.",
          "Coma menos sal. Prefiera alimentos frescos y coma menos sopas de lata, papitas, carnes frías y comida rápida.",
          "Coma más frutas, verduras, frijoles y granos integrales.",
          "Muévase unos 30 minutos la mayoría de los días, por ejemplo caminando o bailando.",
          "Tome poco alcohol y, si fuma, pídanos ayuda para dejarlo.",
          "Trate de llegar a un peso saludable. Bajar aunque sea unas cuantas libras ayuda.",
          "Avísenos si ronca fuerte o tiene mucho sueño durante el día. Dormir mal puede subir la presión.",
        ],
        numbers: [
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
          "Sal (sodio): menos de 1,500 mg al día si es posible, o la meta que su proveedor le indique.",
          "Actividad física: unos 150 minutos por semana, por ejemplo 30 minutos 5 días a la semana, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome su medicina para la presión todos los días tal como se la recetaron, aunque se sienta bien.",
          "No se salte dosis ni deje una medicina sin hablar antes con nosotros. Dejar algunas medicinas de golpe puede hacer que la presión suba mucho.",
          "Avísenos si tiene efectos secundarios como mareo, hinchazón o tos. Muchas veces podemos encontrar una mejor opción para usted.",
          "Traiga todos sus frascos de medicina a cada cita. Pregúntenos antes de tomar medicinas para el resfriado o el dolor que se venden sin receta, porque algunas suben la presión.",
        ],
        callUs: [
          "Su presión está en 180/120 o más, se siente bien y sigue igual de alta después de descansar 5 minutos y volver a medirla.",
          "La mayoría de sus lecturas están por encima de su meta durante una semana o más.",
          "Siente mareo o que se va a desmayar, sobre todo al ponerse de pie, o se ha caído.",
          "Tiene efectos secundarios, o no puede pagar o conseguir su medicina.",
        ],
        call911: [
          "Su presión está en 180/120 o más y tiene dolor en el pecho, falta de aire, dolor de espalda, adormecimiento o debilidad, un dolor de cabeza muy fuerte, dificultad para hablar o cambios en la vista.",
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911.",
          "Tiene señales de un ataque al corazón: dolor, presión o apretón en el pecho; dolor en el brazo, la espalda, el cuello, la mandíbula o el estómago; falta de aire; sudor frío; náuseas o mareo.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Review the patient's blood pressure goal and recent readings, and praise any progress.",
        "Coach home technique: rest 5 minutes first, back supported, feet flat, arm at heart level, cuff on a bare upper arm, and no caffeine, exercise, or smoking for 30 minutes before.",
        "Reinforce taking blood pressure medicine every day, even without symptoms, and not stopping it without talking to the provider.",
        "Encourage lower-salt choices (fresh foods, reading labels) and regular walking.",
        "Review the action plan: 180/120 or higher with symptoms means call 911; without symptoms, rest 5 minutes, recheck, and call the office.",
      ],
      ask: [
        "What have your home blood pressure readings been this month? Can you read me a few?",
        "How often are you able to take your blood pressure medicine? Do you ever skip doses or run out?",
        "Have you had any dizziness, falls, headaches, or side effects?",
        "What does a usual day of eating look like for you? Where do you think most of your salt comes from?",
        "Do you have a working blood pressure cuff, and is your next visit scheduled?",
      ],
    },
    carePlan: {
      problem: "Essential (primary) hypertension",
      expectedOutcome: "Controlled with treatment and lifestyle changes; goal is to reach target blood pressure and prevent heart attack, stroke, kidney disease, and hospital visits.",
      goals: [
        "Office and home BP <130/80 mmHg (or as individualized by the provider)",
        "BP at goal within 3–6 months of starting or adjusting therapy, confirmed by home readings (or as individualized by the provider)",
        "Dietary sodium <1,500 mg/day, or at least a 1,000 mg/day reduction (or as individualized by the provider)",
        "At least 150 minutes/week of moderate aerobic activity, alcohol no more than 1 drink/day (women) or 2 (men), and tobacco abstinence (or as individualized by the provider)",
      ],
      monitoring: [
        "BP at every office visit using proper technique; recheck monthly after any medication change until at goal, then every 3–6 months",
        "Home BP with a validated upper-arm cuff: 2 readings 1 minute apart, morning and evening, for at least 3–7 days before visits; reviewed on monthly CCM calls",
        "Basic metabolic panel (creatinine/eGFR, potassium, sodium) 2–4 weeks after starting or changing therapy that affects kidney function or electrolytes, then at least annually",
        "Annual urine albumin-to-creatinine ratio, lipid panel, and A1c or fasting glucose",
        "12-lead ECG at baseline and as clinically indicated",
      ],
      interventions: [
        "Medication reconciliation at every care transition and on monthly CCM calls; adherence support and cost or access problem-solving",
        "Provider titrates guideline-directed antihypertensive therapy per provider until BP is at goal",
        "Home BP monitoring teaching (validated cuff, correct cuff size, technique) and checking the home cuff against an office reading",
        "Remote patient monitoring with a connected BP cuff when appropriate",
        "Lifestyle education: DASH-style eating, sodium reduction, weight management, physical activity, alcohol limits, and tobacco cessation",
        "Evaluate for secondary causes when indicated (e.g., resistant hypertension, suspected sleep apnea) per provider",
      ],
      selfManagement: [
        "Measure and log home BP as instructed and share readings on CCM calls",
        "Follow a DASH-style, lower-sodium eating plan",
        "Stay active at least 150 minutes/week as able and work toward a healthy weight",
        "Take medicines daily and do not stop them without talking to the care team",
        "Limit alcohol and avoid tobacco",
      ],
      symptomManagement: [
        "Home BP ≥180/120 without symptoms: rest 5 minutes and recheck; if still elevated, contact the office the same day",
        "BP ≥180/120 with chest pain, dyspnea, neurologic symptoms, vision change, or severe headache: call 911 (possible hypertensive emergency)",
        "Lightheadedness, falls, or symptomatic low readings (e.g., <90/60): notify the provider the same day for regimen review",
        "Side effects (cough, ankle swelling, fatigue): report rather than stop the medicine; provider reviews alternatives",
      ],
      coordination: [
        "Clinical pharmacist for medication optimization and adherence, if available",
        "Nephrology for CKD with declining eGFR or significant albuminuria; cardiology or a hypertension specialist for resistant hypertension (above goal on 3 or more agents)",
        "Sleep medicine for suspected obstructive sleep apnea",
        "Community resources: nutrition programs, community BP self-monitoring programs, and the tobacco quitline (1-800-QUIT-NOW)",
      ],
    },
    basis: ["2025 AHA/ACC Guideline for High Blood Pressure in Adults", "2017 ACC/AHA Blood Pressure Guideline"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "heart_failure",
    education: {
      en: {
        title: "Living with heart failure",
        whatItIs: "Heart failure means your heart is not pumping as well as it should. It does not mean your heart has stopped. Because blood moves more slowly, fluid can build up in your lungs, legs, and belly.",
        whyItMatters: "When fluid builds up, you may feel short of breath, tired, or swollen, and you may need a hospital stay. Daily habits and the right medicines can help you feel better, stay active, and stay out of the hospital.",
        whatYouCanDo: [
          "Weigh yourself every morning after you use the bathroom and before you eat. Write it down.",
          "Eat less salt. Salt makes your body hold on to water.",
          "If your provider tells you to limit fluids, measure what you drink each day.",
          "Check your feet, ankles, and belly for new swelling.",
          "Stay active with short walks, and rest when you need to. Ask us about cardiac rehab, a supervised exercise program for your heart.",
          "Do not smoke, and limit alcohol.",
          "Get a flu shot every year, and ask us which other vaccines you need.",
        ],
        numbers: [
          "Weight gain: no more than 2 to 3 pounds in a day or 5 pounds in a week, or the goal your provider sets for you.",
          "Salt (sodium): less than 2,000 mg a day for many people, or the goal your provider sets for you.",
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
        ],
        medicines: [
          "Heart failure medicines help your heart work better and help you live longer. Take them every day as prescribed, even when you feel well.",
          "Your provider may raise your doses slowly over time. Do not stop or change a medicine without talking to us.",
          "Some pain pills, cold medicines, and herbal products from the store can make heart failure worse. Ask us before you take anything new.",
          "Bring all your medicine bottles to every visit, and tell us about side effects like dizziness or feeling very tired.",
        ],
        callUs: [
          "You gain more than 2 to 3 pounds in a day or 5 pounds in a week.",
          "You have more swelling in your feet, legs, or belly.",
          "You are more short of breath than usual, you need more pillows to sleep, or you wake up at night short of breath.",
          "You have a cough that will not go away, or you feel much more tired or weak than usual.",
          "You feel dizzy or lightheaded, or you are peeing much less than usual.",
        ],
        call911: [
          "You are struggling to breathe while resting, you are too short of breath to talk, or you cough up pink, foamy mucus.",
          "You have chest pain or pressure that lasts more than a few minutes, or you faint.",
          "Your heart is racing or pounding and you feel like you might pass out.",
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911.",
        ],
      },
      es: {
        title: "Cómo vivir con insuficiencia cardíaca",
        whatItIs: "La insuficiencia cardíaca quiere decir que el corazón no bombea la sangre tan bien como debería. No quiere decir que el corazón se haya detenido. Como la sangre circula más despacio, se puede acumular líquido en los pulmones, las piernas y el vientre.",
        whyItMatters: "Cuando se acumula líquido, puede sentir falta de aire, cansancio o hinchazón, y a veces hay que ir al hospital. Los buenos hábitos diarios y las medicinas correctas le ayudan a sentirse mejor, seguir con sus actividades y no tener que internarse.",
        whatYouCanDo: [
          "Pésese todas las mañanas, después de ir al baño y antes de desayunar. Anote su peso.",
          "Coma menos sal. La sal hace que el cuerpo retenga agua.",
          "Si su proveedor le dijo que limite los líquidos, mida lo que toma cada día.",
          "Revise si tiene más hinchazón en los pies, los tobillos o el vientre.",
          "Manténgase en movimiento con caminatas cortas y descanse cuando lo necesite. Pregúntenos por la rehabilitación cardíaca, un programa de ejercicio supervisado para el corazón.",
          "No fume y tome poco alcohol.",
          "Póngase la vacuna contra la gripe cada año y pregúntenos qué otras vacunas necesita.",
        ],
        numbers: [
          "Aumento de peso: no más de 2 a 3 libras en un día ni 5 libras en una semana, o la meta que su proveedor le indique.",
          "Sal (sodio): menos de 2,000 mg al día para muchas personas, o la meta que su proveedor le indique.",
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas para la insuficiencia cardíaca ayudan a que el corazón trabaje mejor y a vivir más tiempo. Tómelas todos los días como se las recetaron, aunque se sienta bien.",
          "Es posible que su proveedor le suba la dosis poco a poco. No deje ni cambie ninguna medicina sin hablar con nosotros.",
          "Algunas pastillas para el dolor, medicinas para el resfriado y productos naturales que se venden sin receta pueden empeorar la insuficiencia cardíaca. Pregúntenos antes de tomar algo nuevo.",
          "Traiga todos sus frascos de medicina a cada cita y avísenos si tiene efectos secundarios, como mareo o mucho cansancio.",
        ],
        callUs: [
          "Sube más de 2 a 3 libras en un día o 5 libras en una semana.",
          "Tiene más hinchazón en los pies, las piernas o el vientre.",
          "Le falta el aire más de lo normal, necesita más almohadas para dormir o se despierta en la noche con falta de aire.",
          "Tiene una tos que no se le quita, o siente mucho más cansancio o debilidad que de costumbre.",
          "Siente mareo, o está orinando mucho menos que de costumbre.",
        ],
        call911: [
          "Le cuesta mucho respirar aun estando en reposo, le falta tanto el aire que no puede hablar, o tose flema rosada y espumosa.",
          "Tiene dolor o presión en el pecho que dura más de unos minutos, o se desmaya.",
          "Siente el corazón muy acelerado o golpeando fuerte y siente que se va a desmayar.",
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Reinforce daily morning weights written down in a log, and review the rule: call if up 2 to 3 pounds in a day or 5 pounds in a week.",
        "Review the zones: green (doing well), yellow (call the office the same day), red (call 911).",
        "Encourage low-salt choices and reading food labels; reinforce any fluid limit the provider has set.",
        "Remind the patient that heart failure medicines help even when they feel fine, and to ask before taking store-bought pain or cold medicines.",
        "Encourage gentle daily activity, and ask whether they were offered cardiac rehab.",
      ],
      ask: [
        "What has your weight been each morning this week? Any jumps?",
        "Are you more short of breath, using more pillows, or seeing more swelling than last month?",
        "Are you able to take all your heart medicines every day? Any dizziness, side effects, or trouble getting refills?",
        "Have you been to the ER or the hospital since we last talked?",
        "Do you have a working scale and blood pressure cuff, and when is your next heart appointment?",
      ],
    },
    carePlan: {
      problem: "Chronic heart failure (specify HFrEF, HFmrEF, HFimpEF, or HFpEF by most recent LVEF, and NYHA class)",
      expectedOutcome: "Stable or improved symptoms on guideline-directed medical therapy; goal is to prevent decompensation, hospitalizations, and readmissions.",
      goals: [
        "No HF-related ED visits or hospitalizations over the next 12 months (or as individualized by the provider)",
        "No weight gain >2–3 lb in a day or >5 lb in a week above established dry weight on daily home weights (or as individualized by the provider)",
        "Guideline-directed medical therapy at target or maximally tolerated doses per provider/cardiology, with NYHA class stable or improved at each quarterly review (or as individualized by the provider)",
        "BP <130/80 mmHg if tolerated, and sodium intake as directed (commonly <2,000 mg/day) (or as individualized by the provider)",
      ],
      monitoring: [
        "Daily home weights reviewed on each monthly CCM call (and as transmitted if on RPM)",
        "Symptoms, NYHA class, edema, and exercise tolerance at every visit and monthly CCM call",
        "Basic metabolic panel (sodium, potassium, creatinine/eGFR) 1–2 weeks after starting or titrating GDMT or diuretics, then every 3–6 months when stable",
        "BP and heart rate at every visit and on home logs",
        "Echocardiogram to reassess LVEF per cardiology (e.g., 3–6 months after GDMT optimization or with a clinical change)",
        "CBC and iron studies (ferritin, transferrin saturation) at least annually; A1c and lipids per comorbidities",
      ],
      interventions: [
        "Medication reconciliation monthly and at every care transition; flag NSAIDs, decongestants, and other agents that may worsen HF for provider review",
        "Provider and cardiology titrate guideline-directed medical therapy to target or maximally tolerated doses",
        "Transitional care after any HF hospitalization: follow-up call within 2 business days and visit within 7 days",
        "Written HF action plan (green/yellow/red zones); remote patient monitoring with scale and BP cuff when appropriate",
        "Education on daily weights, sodium limits, fluid limits if prescribed, and symptom recognition; vaccines current per CDC",
        "Screen for depression, cognitive impairment, frailty, and social needs; discuss goals of care and advance care planning",
      ],
      selfManagement: [
        "Weigh daily after urinating and before breakfast; log and report changes",
        "Limit sodium as directed and follow any fluid restriction",
        "Stay active as tolerated and attend cardiac rehabilitation if referred",
        "Take medicines daily and avoid over-the-counter NSAIDs and decongestants unless approved",
        "Avoid tobacco and limit alcohol",
      ],
      symptomManagement: [
        "Yellow zone (weight gain >2–3 lb in a day or >5 lb in a week, more edema, worsening dyspnea, orthopnea, persistent cough): contact the office the same day for regimen review",
        "Red zone (dyspnea at rest, chest pain, syncope, confusion, pink frothy sputum): call 911",
        "Dizziness, hypotension, or reduced urine output (possible over-diuresis or worsening kidney function): notify the provider and obtain labs as ordered",
      ],
      coordination: [
        "Cardiology or a heart failure clinic for GDMT optimization and device evaluation",
        "Cardiac rehabilitation (Medicare-covered for stable HFrEF with LVEF ≤35%)",
        "Home health, registered dietitian, and clinical pharmacist as needed",
        "Palliative care for advanced symptoms; community resources such as low-sodium meal delivery",
      ],
    },
    basis: ["2022 AHA/ACC/HFSA Heart Failure Guideline", "2024 ACC Expert Consensus Decision Pathway for HFrEF Treatment"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "cad",
    education: {
      en: {
        title: "Living with coronary artery disease",
        whatItIs: "Coronary artery disease means the blood vessels that feed your heart muscle have become narrow. This happens when a waxy buildup called plaque forms inside them. Less blood reaches your heart, which can cause chest pain (called angina) or a heart attack.",
        whyItMatters: "A heart attack can happen if a piece of plaque breaks open and a blood clot blocks blood flow. Healthy habits and medicines can slow the disease, ease chest pain, and lower your risk of a heart attack.",
        whatYouCanDo: [
          "If you smoke or vape, quitting is the most important step you can take. Ask us for help.",
          "Eat heart-healthy foods: vegetables, fruits, beans, nuts, fish, and whole grains. Cut back on fried foods, fatty meats, and salt.",
          "Be active most days, at a level your care team says is safe for you.",
          "Ask us about cardiac rehab, a supervised exercise and learning program for people with heart disease.",
          "Keep your blood pressure, cholesterol, and blood sugar at their goals.",
          "Learn your chest pain plan, and carry a list of your medicines with you.",
          "Get a flu shot every year, and ask us which other vaccines you need.",
        ],
        numbers: [
          "LDL (\"bad\") cholesterol: below 70 for most people with heart disease, or the goal your provider sets for you.",
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
          "Activity: about 150 minutes a week, like 30 minutes on 5 days, or the goal your provider sets for you.",
        ],
        medicines: [
          "Heart medicines lower your chance of a heart attack. Take them every day as prescribed, even when you feel fine.",
          "If you have a stent (a small tube that holds an artery open), never stop a medicine that keeps your blood from clotting unless your heart doctor says it is OK. Stopping too soon can cause a dangerous clot.",
          "If you were given a fast-acting medicine for chest pain, keep it with you and use it the way your provider showed you.",
          "Bring all your medicine bottles to every visit, tell us about side effects, and ask us before taking anything new, including medicines for sexual problems.",
        ],
        callUs: [
          "Your chest pain comes more often, with less activity, or lasts longer than before.",
          "You get more short of breath or tired doing your usual activities.",
          "You have new swelling in your feet or ankles, or you feel dizzy or lightheaded.",
          "You see black or bloody stools, have bleeding gums, or bruise easily while taking a medicine that thins your blood.",
          "You have side effects, or you cannot afford or get your medicines.",
        ],
        call911: [
          "You have signs of a heart attack: chest pain, pressure, squeezing, or fullness that lasts more than a few minutes or goes away and comes back; pain in one or both arms, the back, neck, jaw, or stomach; shortness of breath; cold sweat, nausea, or lightheadedness. Do not drive yourself.",
          "Your chest pain is not better, or is worse, 5 minutes after you take your fast-acting chest pain medicine.",
          "You suddenly feel very short of breath, sick to your stomach, or unusually tired. Women, older adults, and people with diabetes may have only these signs of a heart attack.",
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911.",
        ],
      },
      es: {
        title: "Cómo vivir con enfermedad de las arterias coronarias",
        whatItIs: "La enfermedad de las arterias coronarias quiere decir que los vasos que llevan sangre al músculo del corazón se han vuelto más estrechos. Esto pasa cuando por dentro se forma una capa de grasa llamada placa. Al llegar menos sangre al corazón, puede haber dolor de pecho (llamado angina) o un ataque al corazón.",
        whyItMatters: "Un ataque al corazón puede ocurrir si una parte de la placa se rompe y un coágulo tapa el paso de la sangre. Los hábitos saludables y las medicinas pueden frenar la enfermedad, aliviar el dolor de pecho y bajar el riesgo de un ataque al corazón.",
        whatYouCanDo: [
          "Si fuma o usa cigarrillos electrónicos, dejarlo es lo más importante que puede hacer. Pídanos ayuda.",
          "Coma alimentos buenos para el corazón: verduras, frutas, frijoles, nueces, pescado y granos integrales. Coma menos frituras, carnes grasosas y sal.",
          "Haga actividad física la mayoría de los días, al nivel que su equipo de salud le diga que es seguro para usted.",
          "Pregúntenos por la rehabilitación cardíaca, un programa supervisado de ejercicio y aprendizaje para personas con enfermedad del corazón.",
          "Mantenga la presión, el colesterol y el azúcar en sus metas.",
          "Conozca su plan para el dolor de pecho y lleve siempre una lista de sus medicinas.",
          "Póngase la vacuna contra la gripe cada año y pregúntenos qué otras vacunas necesita.",
        ],
        numbers: [
          "Colesterol LDL (el \"malo\"): menos de 70 para la mayoría de las personas con enfermedad del corazón, o la meta que su proveedor le indique.",
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
          "Actividad física: unos 150 minutos por semana, por ejemplo 30 minutos 5 días a la semana, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas para el corazón bajan el riesgo de un ataque al corazón. Tómelas todos los días como se las recetaron, aunque se sienta bien.",
          "Si tiene un stent (un tubito que mantiene abierta una arteria), nunca deje una medicina que evita los coágulos a menos que su cardiólogo le diga que puede hacerlo. Dejarla antes de tiempo puede causar un coágulo peligroso.",
          "Si le dieron una medicina de acción rápida para el dolor de pecho, llévela siempre con usted y úsela como le enseñó su proveedor.",
          "Traiga todos sus frascos de medicina a cada cita, avísenos de cualquier efecto secundario y pregúntenos antes de tomar algo nuevo, incluso medicinas para problemas sexuales.",
        ],
        callUs: [
          "El dolor de pecho le da más seguido, con menos esfuerzo o le dura más que antes.",
          "Le falta el aire o se cansa más de lo normal al hacer sus actividades de siempre.",
          "Tiene hinchazón nueva en los pies o los tobillos, o siente mareo.",
          "Ve heces negras o con sangre, le sangran las encías o le salen moretones con facilidad mientras toma una medicina que adelgaza la sangre.",
          "Tiene efectos secundarios, o no puede pagar o conseguir sus medicinas.",
        ],
        call911: [
          "Tiene señales de un ataque al corazón: dolor, presión, apretón o pesadez en el pecho que dura más de unos minutos o que se quita y vuelve; dolor en uno o ambos brazos, la espalda, el cuello, la mandíbula o el estómago; falta de aire; sudor frío, náuseas o mareo. No maneje usted mismo al hospital.",
          "El dolor de pecho no mejora, o empeora, 5 minutos después de tomar su medicina de acción rápida para el dolor de pecho.",
          "De repente siente mucha falta de aire, náuseas o un cansancio fuera de lo común. Las mujeres, los adultos mayores y las personas con diabetes a veces solo tienen estas señales de un ataque al corazón.",
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Review heart attack warning signs and the rule: call 911 and do not drive yourself.",
        "If the patient has a fast-acting chest pain medicine, confirm they know to call 911 if the pain is not better 5 minutes after the first dose.",
        "Reinforce taking heart medicines every day; patients with a stent must not stop clot-preventing medicine without their cardiologist's OK.",
        "Encourage quitting tobacco, heart-healthy eating, and safe daily activity; ask whether they were offered cardiac rehab.",
        "Review the patient's LDL and blood pressure goals and when their next labs are due.",
      ],
      ask: [
        "Have you had any chest pain, pressure, or shortness of breath this month? What brings it on, and how long does it last?",
        "Has your chest pain changed, like happening more often, with less activity, or while resting?",
        "Are you taking your heart medicines every day? Any side effects, bleeding, or trouble paying for them?",
        "Are you smoking or using any tobacco? Would you like help quitting?",
        "When is your next heart doctor visit, and do you have a ride?",
      ],
    },
    carePlan: {
      problem: "Chronic coronary disease (atherosclerotic coronary artery disease)",
      expectedOutcome: "Stable with guideline-directed therapy and risk-factor control; goal is to control angina and prevent heart attack, unplanned revascularization, and hospital visits.",
      goals: [
        "LDL-C <70 mg/dL, with <55 mg/dL reasonable for very high-risk patients (or as individualized by the provider)",
        "BP <130/80 mmHg (or as individualized by the provider)",
        "No unplanned ED visits or hospitalizations for chest pain, with stable or reduced angina frequency (or as individualized by the provider)",
        "Tobacco abstinence and at least 150 minutes/week of moderate activity; A1c <7% if diabetic (or as individualized by the provider)",
      ],
      monitoring: [
        "Lipid panel 4–12 weeks after starting or changing lipid-lowering therapy, then every 3–12 months as needed (at least annually)",
        "BP and heart rate at every visit; home BP reviewed on monthly CCM calls",
        "Angina frequency, triggers, and short-acting antianginal use at every visit and monthly CCM call",
        "Basic metabolic panel/eGFR and A1c at least annually (more often per comorbidities)",
        "Tobacco use status at every visit; depression screen at least annually",
      ],
      interventions: [
        "Medication reconciliation and adherence support; reinforce that antiplatelet therapy after stenting is never stopped without cardiology input",
        "Provider manages guideline-directed medical therapy (antiplatelet, lipid-lowering, antianginal, and BP therapy) per provider",
        "Refer to cardiac rehabilitation after MI, PCI, or CABG, or for stable angina",
        "Tobacco cessation counseling with pharmacotherapy per provider",
        "Education on heart attack warning signs and the chest-pain action plan; annual influenza vaccination and other vaccines per CDC",
      ],
      selfManagement: [
        "Take heart medicines daily and carry an updated medication list",
        "Follow a heart-healthy eating pattern (Mediterranean or DASH style) low in saturated fat and sodium",
        "Stay physically active as cleared by the care team",
        "Avoid all tobacco and limit alcohol",
        "Know and follow the chest-pain action plan",
      ],
      symptomManagement: [
        "Stable exertional angina: stop and rest; use short-acting antianginal as prescribed; call 911 if pain is not improved or is worse 5 minutes after the first dose",
        "Accelerating angina (more frequent or with less exertion) without rest pain: contact the office the same day; angina at rest or lasting more than a few minutes: call 911",
        "Bleeding, muscle symptoms, or dizziness on therapy: report to the provider; do not stop antiplatelet therapy without provider or cardiology input",
      ],
      coordination: [
        "Cardiology for ongoing care and after any ischemic event or procedure",
        "Cardiac rehabilitation program",
        "Tobacco quitline (1-800-QUIT-NOW) and registered dietitian",
        "Community exercise and support programs; medication-cost assistance as needed",
      ],
    },
    basis: ["2023 AHA/ACC Chronic Coronary Disease Guideline", "2018 AHA/ACC Cholesterol Guideline"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "afib",
    education: {
      en: {
        title: "Living with atrial fibrillation (AFib)",
        whatItIs: "Atrial fibrillation, or AFib, is a common heart rhythm problem. The top chambers of your heart quiver instead of beating in a steady rhythm. Your heartbeat may feel fast, fluttering, or uneven, but some people feel nothing at all.",
        whyItMatters: "With AFib, blood can pool in the heart and form clots that travel to the brain and cause a stroke. Treatment lowers your stroke risk, protects your heart, and helps you feel better.",
        whatYouCanDo: [
          "Learn how to check your pulse, and write down when your heart races or flutters and how long it lasts.",
          "Cut back on alcohol or stop drinking. Even small amounts can set off AFib.",
          "If you are overweight, losing about 10% of your weight can make AFib happen less often.",
          "Be active most days, at a level your care team says is safe for you.",
          "If you smoke, ask us for help quitting.",
          "Tell us if you snore loudly or feel sleepy during the day. Sleep apnea, a problem where your breathing stops and starts while you sleep, can make AFib worse.",
          "Make your home safer from falls: clear clutter, remove loose rugs, and use night lights.",
        ],
        numbers: [
          "Resting heart rate (pulse): below about 100 to 110 beats a minute, or the goal your provider sets for you.",
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
        ],
        medicines: [
          "Many people with AFib take a blood thinner to prevent stroke. Take it every day at the same time. Do not skip doses or stop it without talking to us.",
          "If you take a blood thinner, watch for bleeding: bleeding gums, nosebleeds, easy bruising, pink or brown urine, or black stools. Tell every doctor and dentist that you take it.",
          "Ask us before taking any new medicine, pain pill, vitamin, or herbal product. Some can raise your bleeding risk or affect your heart rhythm.",
          "Bring all your medicine bottles to every visit, and tell us about any side effects.",
        ],
        callUs: [
          "Your heart races, flutters, or pounds more often or for longer than usual.",
          "Your resting pulse is often above 110, or it is below 50 and you feel tired or dizzy.",
          "You are more short of breath, tired, or dizzy than usual, or you have new swelling in your legs.",
          "You have small bleeds that keep coming back, like nosebleeds or bleeding gums, or bruises you cannot explain.",
          "You missed doses of your blood thinner, or you cannot afford or get it.",
        ],
        call911: [
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911. Note the time the signs started.",
          "You have chest pain or pressure, you faint, or you are very short of breath.",
          "You have serious bleeding: bleeding that does not stop after 10 minutes of firm pressure, throwing up blood or something that looks like coffee grounds, or red or black stools.",
          "You fall and hit your head while taking a blood thinner, even if you feel fine.",
        ],
      },
      es: {
        title: "Cómo vivir con fibrilación auricular",
        whatItIs: "La fibrilación auricular es un problema común del ritmo del corazón. Las cavidades de arriba del corazón tiemblan en lugar de latir con un ritmo parejo. Puede sentir el corazón acelerado, como aleteando o irregular, aunque algunas personas no sienten nada.",
        whyItMatters: "Con la fibrilación auricular, la sangre se puede estancar en el corazón y formar coágulos que viajan al cerebro y causan un derrame cerebral. El tratamiento baja el riesgo de un derrame, protege el corazón y le ayuda a sentirse mejor.",
        whatYouCanDo: [
          "Aprenda a tomarse el pulso y anote cuándo siente el corazón acelerado o como aleteando, y cuánto tiempo le dura.",
          "Tome menos alcohol o deje de tomar. Aun cantidades pequeñas pueden provocar la fibrilación.",
          "Si tiene sobrepeso, bajar alrededor del 10% de su peso puede hacer que la fibrilación le dé menos seguido.",
          "Haga actividad física la mayoría de los días, al nivel que su equipo de salud le diga que es seguro para usted.",
          "Si fuma, pídanos ayuda para dejarlo.",
          "Avísenos si ronca fuerte o tiene mucho sueño durante el día. La apnea del sueño, un problema en el que la respiración se detiene y vuelve a empezar mientras duerme, puede empeorar la fibrilación.",
          "Prevenga caídas en casa: quite el desorden y las alfombras o tapetes sueltos, y use luces de noche.",
        ],
        numbers: [
          "Pulso en reposo: menos de unos 100 a 110 latidos por minuto, o la meta que su proveedor le indique.",
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Muchas personas con fibrilación auricular toman un anticoagulante (medicina que evita los coágulos) para prevenir un derrame cerebral. Tómelo todos los días a la misma hora. No se salte dosis ni lo deje sin hablar con nosotros.",
          "Si toma un anticoagulante, fíjese si tiene señales de sangrado: encías que sangran, sangrado de nariz, moretones fáciles, orina rosada o café, o heces negras. Dígales a todos sus médicos y a su dentista que lo toma.",
          "Pregúntenos antes de tomar cualquier medicina nueva, pastilla para el dolor, vitamina o producto natural. Algunos pueden aumentar el riesgo de sangrado o afectar el ritmo del corazón.",
          "Traiga todos sus frascos de medicina a cada cita y avísenos de cualquier efecto secundario.",
        ],
        callUs: [
          "Siente el corazón acelerado, como aleteando o golpeando fuerte, más seguido o por más tiempo que antes.",
          "Su pulso en reposo con frecuencia pasa de 110, o baja de 50 y siente cansancio o mareo.",
          "Le falta el aire, se cansa o se marea más de lo normal, o tiene hinchazón nueva en las piernas.",
          "Tiene sangrados pequeños que se repiten, como de la nariz o de las encías, o moretones sin explicación.",
          "Se le olvidaron dosis de su anticoagulante, o no puede pagarlo o conseguirlo.",
        ],
        call911: [
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911. Fíjese en la hora en que empezaron las señales.",
          "Tiene dolor o presión en el pecho, se desmaya o le falta mucho el aire.",
          "Tiene un sangrado grave: sangrado que no para después de 10 minutos de presión firme, vómito con sangre o con algo que parece café molido, o heces rojas o negras.",
          "Se cae y se golpea la cabeza mientras toma un anticoagulante, aunque se sienta bien.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Reinforce stroke warning signs (BE FAST) and calling 911 right away.",
        "If the patient takes a blood thinner, reinforce taking it every day at the same time, and calling the office about missed doses instead of doubling up on their own.",
        "Review bleeding warning signs and fall prevention at home.",
        "Encourage limiting alcohol, staying active, losing weight if overweight, and mentioning snoring or daytime sleepiness to the provider.",
        "Remind the patient to tell every doctor and dentist about their blood thinner before any procedure, and to ask before taking new medicines or supplements.",
      ],
      ask: [
        "Have you felt your heart racing, fluttering, or skipping this month? How often, and for how long?",
        "Are you taking your blood thinner and heart medicines every day? Any missed doses or trouble getting them?",
        "Have you noticed any bleeding, unusual bruising, black stools, or falls?",
        "Have you had dizziness, shortness of breath, or swelling?",
        "Do you have any procedures, dental work, or heart appointments coming up?",
      ],
    },
    carePlan: {
      problem: "Atrial fibrillation (specify paroxysmal, persistent, long-standing persistent, or permanent; includes atrial flutter)",
      expectedOutcome: "Stable with treatment; goal is to control symptoms and heart rate, prevent stroke, and avoid bleeding complications and hospital visits.",
      goals: [
        "Stroke risk (CHA2DS2-VASc) documented at least annually with a shared decision on anticoagulation; if anticoagulated, no missed doses and no major bleeding events (or as individualized by the provider)",
        "Resting heart rate <100–110 bpm with symptoms controlled when a rate-control strategy is used (or as individualized by the provider)",
        "BP <130/80 mmHg (or as individualized by the provider)",
        "Risk-factor modification: at least 10% weight loss if BMI ≥27, alcohol ≤3 drinks/week or abstinence, tobacco abstinence, and at least 150 minutes/week of moderate activity (or as individualized by the provider)",
      ],
      monitoring: [
        "Heart rate, rhythm, and BP at every visit; symptom review (palpitations, dyspnea, fatigue, dizziness) on monthly CCM calls",
        "CBC and creatinine/creatinine clearance at least annually on anticoagulation; more often (e.g., every 3–6 months) if CrCl <60 mL/min, age ≥75, or frail",
        "INR per anticoagulation-clinic protocol if on a vitamin K antagonist",
        "Annual reassessment of stroke risk, modifiable bleeding risk factors, and fall risk",
        "TSH at baseline and when clinically indicated; echocardiogram and rhythm monitoring per cardiology",
      ],
      interventions: [
        "Medication reconciliation and anticoagulant adherence support; screen for interacting medicines (NSAIDs, antiplatelets, supplements) for pharmacist or provider review",
        "Provider and cardiology choose rate or rhythm control and anticoagulation per guideline with shared decision-making; refer for ablation or left atrial appendage occlusion evaluation when indicated",
        "Coordinate peri-procedural anticoagulation plans with the prescriber before dental work or surgery",
        "Risk-factor modification support (weight, alcohol, BP, diabetes) and screening for obstructive sleep apnea",
        "Education on stroke (BE FAST) and bleeding warning signs; fall-risk assessment and prevention; RPM for BP and heart rate when appropriate",
      ],
      selfManagement: [
        "Take anticoagulant and heart medicines at the same time every day",
        "Check pulse and log palpitations or other symptoms",
        "Limit or avoid alcohol and work toward a healthy weight",
        "Tell every clinician and dentist about anticoagulant use and carry a medication list",
      ],
      symptomManagement: [
        "Palpitations or rapid heart rate with mild symptoms: rest, check and log pulse; contact the office the same day if resting HR stays >110 or symptoms are new or worse",
        "Stroke signs (BE FAST), chest pain, syncope, or severe dyspnea: call 911",
        "Minor bleeding (gums, nose, bruising): apply pressure and report; major bleeding or any head injury while anticoagulated: call 911 for emergency evaluation",
      ],
      coordination: [
        "Cardiology or electrophysiology for rhythm management and procedures",
        "Anticoagulation clinic or clinical pharmacist",
        "Sleep medicine for suspected sleep apnea; dentists and surgeons for peri-procedural planning",
        "Community resources: alcohol-reduction support and weight-management programs",
      ],
    },
    basis: ["2023 ACC/AHA/ACCP/HRS Atrial Fibrillation Guideline"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "lipids",
    education: {
      en: {
        title: "Managing high cholesterol",
        whatItIs: "Cholesterol is a waxy fat in your blood. Your body needs some, but too much LDL, the \"bad\" cholesterol, can build up inside your blood vessels. High cholesterol usually has no symptoms, so a blood test is the only way to know.",
        whyItMatters: "Over time, this buildup narrows your blood vessels and raises your risk of a heart attack or stroke. Lowering your LDL lowers that risk.",
        whatYouCanDo: [
          "Eat more vegetables, fruits, beans, oats, nuts, and whole grains.",
          "Choose fish, skinless chicken, and beans more often than red meat and processed meats like bacon, sausage, and hot dogs.",
          "Cook with olive or canola oil instead of butter, lard, or shortening.",
          "Cut back on fried foods, pastries, and fast food.",
          "Move your body about 30 minutes most days.",
          "If you smoke, ask us for help quitting.",
          "Get your cholesterol blood test when your care team asks.",
        ],
        numbers: [
          "LDL (\"bad\") cholesterol: below 100 for many adults, and below 70 if you have heart disease, diabetes, or a past stroke, or the goal your provider sets for you.",
          "Triglycerides (another fat in your blood): below 150, or the goal your provider sets for you.",
          "HDL (\"good\") cholesterol: higher is better, above 40 for men and above 50 for women, or the goal your provider sets for you.",
        ],
        medicines: [
          "Cholesterol medicine only works while you take it. Take it every day as prescribed, even though you will not feel a difference.",
          "Do not stop your medicine without talking to us. If you have side effects, we can often change the dose or try a different medicine.",
          "Bring all your medicine bottles to visits, and tell us about any vitamins or herbal products you take.",
        ],
        callUs: [
          "You have new muscle aches, cramps, or weakness that do not go away.",
          "Your urine turns dark like tea, or your skin or the whites of your eyes turn yellow.",
          "Side effects are making you want to stop your medicine.",
          "You cannot afford or get your medicine.",
        ],
        call911: [
          "You have signs of a heart attack: chest pain, pressure, or squeezing; pain in the arm, back, neck, jaw, or stomach; shortness of breath; cold sweat; nausea; or lightheadedness.",
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911.",
        ],
      },
      es: {
        title: "Cómo controlar el colesterol alto",
        whatItIs: "El colesterol es una grasa que está en la sangre. El cuerpo necesita un poco, pero el exceso de LDL, el colesterol \"malo\", se puede acumular dentro de los vasos sanguíneos. El colesterol alto casi nunca causa síntomas, por eso un análisis de sangre es la única forma de saberlo.",
        whyItMatters: "Con el tiempo, esa acumulación estrecha los vasos sanguíneos y aumenta el riesgo de un ataque al corazón o un derrame cerebral. Bajar el LDL baja ese riesgo.",
        whatYouCanDo: [
          "Coma más verduras, frutas, frijoles, avena, nueces y granos integrales.",
          "Escoja pescado, pollo sin piel y frijoles más seguido que carne roja y carnes procesadas como tocino, chorizo y salchichas.",
          "Cocine con aceite de oliva o de canola en lugar de mantequilla, manteca o grasa vegetal sólida.",
          "Coma menos frituras, pan dulce y comida rápida.",
          "Muévase unos 30 minutos la mayoría de los días.",
          "Si fuma, pídanos ayuda para dejarlo.",
          "Hágase el análisis de colesterol cuando su equipo de salud se lo pida.",
        ],
        numbers: [
          "Colesterol LDL (el \"malo\"): menos de 100 para muchos adultos, y menos de 70 si tiene enfermedad del corazón, diabetes o tuvo un derrame cerebral, o la meta que su proveedor le indique.",
          "Triglicéridos (otra grasa de la sangre): menos de 150, o la meta que su proveedor le indique.",
          "Colesterol HDL (el \"bueno\"): mientras más alto, mejor; más de 40 en los hombres y más de 50 en las mujeres, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "La medicina para el colesterol solo funciona mientras la toma. Tómela todos los días como se la recetaron, aunque no note ningún cambio.",
          "No deje su medicina sin hablar con nosotros. Si tiene efectos secundarios, muchas veces podemos cambiar la dosis o probar otra medicina.",
          "Traiga todos sus frascos de medicina a las citas y díganos si toma vitaminas o productos naturales.",
        ],
        callUs: [
          "Tiene dolores, calambres o debilidad en los músculos que son nuevos y no se le quitan.",
          "Su orina se pone oscura como el té, o la piel o lo blanco de los ojos se le ponen amarillos.",
          "Los efectos secundarios le hacen querer dejar la medicina.",
          "No puede pagar o conseguir su medicina.",
        ],
        call911: [
          "Tiene señales de un ataque al corazón: dolor, presión o apretón en el pecho; dolor en el brazo, la espalda, el cuello, la mandíbula o el estómago; falta de aire; sudor frío; náuseas o mareo.",
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Explain that high cholesterol has no symptoms, so medicines and lab checks matter even when the patient feels fine.",
        "Reinforce taking cholesterol medicine every day and not stopping it without talking to the provider.",
        "Encourage simple swaps: olive oil for butter or lard, beans and fish for red and processed meats, and more fiber.",
        "Review the patient's LDL goal and when the next cholesterol test is due.",
        "Review heart attack and stroke warning signs and when to call 911.",
      ],
      ask: [
        "How many days in a week do you usually take your cholesterol medicine? What makes it hard to remember?",
        "Have you had any muscle aches, weakness, or other side effects?",
        "What changes, if any, have you made in how you eat or how active you are?",
        "Do you know when your next cholesterol test is? Would you like help scheduling it?",
      ],
    },
    carePlan: {
      problem: "Hyperlipidemia (specify pure hypercholesterolemia, mixed hyperlipidemia, or hypertriglyceridemia)",
      expectedOutcome: "Controlled with lifestyle changes and lipid-lowering therapy; goal is to lower LDL-C and reduce the risk of heart attack and stroke.",
      goals: [
        "LDL-C reduction ≥50% from baseline for clinical ASCVD, LDL-C ≥190 mg/dL, or higher-risk diabetes; 30–49% reduction for other treated primary-prevention patients (or as individualized by the provider)",
        "LDL-C <70 mg/dL with clinical ASCVD or higher-risk diabetes (<55 mg/dL reasonable if very high risk); <100 mg/dL for other primary prevention (or as individualized by the provider)",
        "Triglycerides <150 mg/dL, with prompt provider review if ≥500 mg/dL (or as individualized by the provider)",
        "Adherence with at least 80% of days covered by lipid-lowering therapy (or as individualized by the provider)",
      ],
      monitoring: [
        "Fasting or nonfasting lipid panel 4–12 weeks after starting or changing therapy, then every 3–12 months as needed (at least annually when stable)",
        "Baseline hepatic panel before starting therapy, then only as clinically indicated",
        "Muscle symptoms and adherence reviewed on monthly CCM calls; CK only if significant muscle symptoms",
        "10-year ASCVD risk recalculated every 4–6 years in primary prevention (adults 40–75)",
        "Lipoprotein(a) measured once if never done, per provider",
      ],
      interventions: [
        "Medication reconciliation and adherence support (90-day fills, refill synchronization, cost assistance)",
        "Provider selects lipid-lowering intensity per guideline and adds nonstatin therapy if LDL-C remains above threshold",
        "Education on heart-healthy eating (less saturated and trans fat, more soluble fiber), activity, weight management, and tobacco cessation",
        "Evaluate statin-associated muscle symptoms with the provider rather than discontinuing therapy",
        "If LDL-C ≥190 mg/dL or familial hypercholesterolemia is suspected, recommend screening of first-degree relatives",
      ],
      selfManagement: [
        "Take lipid-lowering medicine daily as prescribed",
        "Follow a heart-healthy eating pattern with more fiber and less saturated fat",
        "Be physically active at least 150 minutes/week as able",
        "Avoid tobacco and complete follow-up lipid labs",
      ],
      symptomManagement: [
        "New muscle aches or weakness: report to the provider for evaluation; do not stop therapy without guidance",
        "Severe muscle pain or weakness with dark urine, or jaundice: same-day evaluation",
        "Heart attack or stroke symptoms: call 911",
      ],
      coordination: [
        "Cardiology or a lipid specialist for LDL-C ≥190 mg/dL, suspected familial hypercholesterolemia, or not at goal on maximally tolerated therapy",
        "Registered dietitian for medical nutrition therapy",
        "Community resources: tobacco quitline, exercise programs, and medication-cost assistance",
      ],
    },
    basis: ["2018 AHA/ACC Multisociety Cholesterol Guideline", "2022 ACC Expert Consensus Decision Pathway on Nonstatin Therapies for LDL-C Lowering"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "pvd",
    education: {
      en: {
        title: "Living with peripheral artery disease (PAD)",
        whatItIs: "Peripheral artery disease, or PAD, means the blood vessels that carry blood to your legs and feet have become narrow. This is caused by a waxy buildup called plaque. Many people feel cramping or pain in their legs when they walk that goes away when they rest.",
        whyItMatters: "With less blood flow, sores on your feet and legs heal slowly and can get infected. People with PAD also have a higher risk of heart attack and stroke, so caring for PAD protects your whole body.",
        whatYouCanDo: [
          "If you smoke, quitting is the most important thing you can do for your legs. Ask us for help.",
          "Walk most days. Walk until your legs hurt a moderate amount, rest until the pain goes away, then walk again. Over time you will be able to walk farther.",
          "Ask us about a supervised walking program. Medicare covers it for many people with PAD leg pain.",
          "Check your feet and legs every day for sores, cuts, blisters, or color changes. Use a mirror or ask someone to help.",
          "Wear shoes and socks that fit well. Do not walk barefoot, even at home.",
          "Keep your feet warm, but do not use heating pads or hot water bottles on them, because they can burn your skin.",
          "Keep your blood pressure, cholesterol, and blood sugar at their goals.",
        ],
        numbers: [
          "Walking exercise: work up to at least 30 minutes, 3 or more times a week, or the goal your provider sets for you.",
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
          "LDL (\"bad\") cholesterol: below 70 for many people with PAD, or the goal your provider sets for you.",
          "A1c if you have diabetes: below 7% for many adults, or the goal your provider sets for you.",
        ],
        medicines: [
          "Medicines for PAD help prevent clots, heart attacks, and strokes. Take them every day as prescribed.",
          "Do not stop any medicine without talking to us, especially one that keeps your blood from clotting.",
          "If you take a medicine that thins your blood, tell us about bleeding gums, nosebleeds, easy bruising, or black stools.",
          "Bring all your medicine bottles to every visit, and tell us about any side effects.",
        ],
        callUs: [
          "A sore, cut, or blister on your foot or leg is not healing, or it looks red, warm, or swollen, or has pus.",
          "Your legs or feet hurt while you are resting or at night, especially if hanging your foot over the side of the bed helps.",
          "Your toes or feet turn pale, blue, or dark, or feel colder than usual.",
          "Leg pain starts sooner when you walk than it used to.",
          "You have side effects, or you cannot afford or get your medicines.",
        ],
        call911: [
          "Your leg or foot suddenly becomes very painful, cold, pale or blue, numb, or weak, or you cannot move it.",
          "You have signs of a heart attack: chest pain, pressure, or squeezing; pain in the arm, back, neck, jaw, or stomach; shortness of breath; cold sweat; nausea; or lightheadedness.",
          "You have signs of a stroke. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911.",
        ],
      },
      es: {
        title: "Cómo vivir con enfermedad arterial periférica",
        whatItIs: "La enfermedad arterial periférica quiere decir que los vasos que llevan sangre a las piernas y los pies se han vuelto más estrechos. La causa es una capa de grasa llamada placa. Muchas personas sienten calambres o dolor en las piernas al caminar, que se quita al descansar.",
        whyItMatters: "Con menos sangre, las heridas en los pies y las piernas tardan en sanar y se pueden infectar. Las personas con esta enfermedad también tienen más riesgo de un ataque al corazón o un derrame cerebral, así que cuidarse protege todo el cuerpo.",
        whatYouCanDo: [
          "Si fuma, dejarlo es lo más importante que puede hacer por sus piernas. Pídanos ayuda.",
          "Camine la mayoría de los días. Camine hasta que le duelan las piernas de forma moderada, descanse hasta que se le quite el dolor y vuelva a caminar. Con el tiempo podrá caminar más lejos.",
          "Pregúntenos por un programa de caminata supervisado. Medicare lo cubre para muchas personas que tienen dolor de piernas por esta enfermedad.",
          "Revise sus pies y piernas todos los días por si hay heridas, cortaduras, ampollas o cambios de color. Use un espejo o pida ayuda.",
          "Use zapatos y calcetines que le queden bien. No ande sin zapatos, ni siquiera en la casa.",
          "Mantenga los pies abrigados, pero no use almohadillas eléctricas ni bolsas de agua caliente, porque le pueden quemar la piel.",
          "Mantenga la presión, el colesterol y el azúcar en sus metas.",
        ],
        numbers: [
          "Caminata: llegue poco a poco a 30 minutos o más, 3 o más veces por semana, o la meta que su proveedor le indique.",
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
          "Colesterol LDL (el \"malo\"): menos de 70 para muchas personas con esta enfermedad, o la meta que su proveedor le indique.",
          "A1c, si tiene diabetes: menos de 7% para muchos adultos, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas para esta enfermedad ayudan a prevenir coágulos, ataques al corazón y derrames cerebrales. Tómelas todos los días como se las recetaron.",
          "No deje ninguna medicina sin hablar con nosotros, sobre todo la que evita que se formen coágulos.",
          "Si toma una medicina que adelgaza la sangre, avísenos si le sangran las encías o la nariz, si le salen moretones con facilidad o si tiene heces negras.",
          "Traiga todos sus frascos de medicina a cada cita y avísenos de cualquier efecto secundario.",
        ],
        callUs: [
          "Tiene una herida, cortadura o ampolla en el pie o la pierna que no sana, o que se ve roja, caliente, hinchada o con pus.",
          "Le duelen las piernas o los pies estando en reposo o por la noche, sobre todo si se le alivia al colgar el pie fuera de la cama.",
          "Los dedos o los pies se le ponen pálidos, morados u oscuros, o los siente más fríos que de costumbre.",
          "El dolor de piernas le empieza más pronto al caminar que antes.",
          "Tiene efectos secundarios, o no puede pagar o conseguir sus medicinas.",
        ],
        call911: [
          "De repente la pierna o el pie le duele mucho, se pone frío, pálido o morado, se le duerme o se le debilita, o no lo puede mover.",
          "Tiene señales de un ataque al corazón: dolor, presión o apretón en el pecho; dolor en el brazo, la espalda, el cuello, la mandíbula o el estómago; falta de aire; sudor frío; náuseas o mareo.",
          "Tiene señales de un derrame cerebral. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Reinforce that quitting tobacco is the single most important step, and offer the quitline and provider help.",
        "Coach the walk-rest-walk routine, and ask whether the patient was offered a supervised exercise program.",
        "Review daily foot checks, well-fitting shoes and socks, and never walking barefoot.",
        "Review warning signs: sores that do not heal, pain at rest, or color changes mean call the office; a sudden cold, pale, painful leg means call 911.",
        "Reinforce taking medicines every day to prevent heart attack and stroke.",
      ],
      ask: [
        "How far or how long can you walk before your legs start to hurt? Is that better or worse than last month?",
        "Have you had any pain in your legs or feet while resting or at night?",
        "Have you noticed any sores, color changes, or cold spots on your feet?",
        "Are you using any tobacco? Are you able to take your medicines every day?",
        "Do you have any appointments with the vascular doctor or foot doctor coming up?",
      ],
    },
    carePlan: {
      problem: "Peripheral artery disease of the lower extremities (atherosclerotic), with or without intermittent claudication",
      expectedOutcome: "Stable with treatment and exercise; goal is to improve walking distance, prevent limb complications and amputation, and lower the risk of heart attack and stroke.",
      goals: [
        "Complete tobacco and nicotine abstinence (or as individualized by the provider)",
        "Complete a supervised exercise program (30–60 minute sessions, at least 3 times/week for 12 weeks) or structured home walking, with improved pain-free walking distance (or as individualized by the provider)",
        "LDL-C <70 mg/dL and BP <130/80 mmHg (or as individualized by the provider)",
        "A1c <7% if diabetic, and no new foot ulcers or major adverse limb events over 12 months (or as individualized by the provider)",
      ],
      monitoring: [
        "Ankle-brachial index (ABI) at diagnosis and with any change in symptoms; vascular surveillance after revascularization per the vascular specialist",
        "Claudication distance and rest-pain review at every visit and monthly CCM call",
        "Foot exam (pulses, skin, color, temperature, wounds) at every visit; patient daily foot checks",
        "Lipid panel 4–12 weeks after therapy changes, then every 3–12 months; BP at every visit",
        "Tobacco use status at every visit",
      ],
      interventions: [
        "Medication reconciliation and adherence support for antithrombotic and lipid-lowering therapy per provider",
        "Refer to supervised exercise therapy (Medicare-covered for symptomatic PAD) or coach a structured home walking program",
        "Tobacco cessation counseling with pharmacotherapy per provider and quitline referral",
        "Foot-care and footwear education; podiatry referral for high-risk feet",
        "Education on warning signs of chronic limb-threatening ischemia and acute limb ischemia",
      ],
      selfManagement: [
        "Walk most days using the walk-rest-walk method",
        "Avoid all tobacco and nicotine products",
        "Inspect feet daily, wear well-fitting shoes and socks, and avoid walking barefoot or using heat on the feet",
        "Take medicines daily and keep BP, cholesterol, and blood sugar at goal",
      ],
      symptomManagement: [
        "Claudication: walk to moderate pain, rest until it eases, then resume; report a shortening walking distance",
        "Rest pain, a wound not healing after 2 weeks, skin color change, or gangrene: urgent vascular evaluation (possible chronic limb-threatening ischemia)",
        "Sudden pain, pallor, coldness, numbness, or weakness of a limb: call 911 (possible acute limb ischemia)",
        "Bleeding on antithrombotic therapy: report to the provider; major bleeding: call 911",
      ],
      coordination: [
        "Vascular medicine or vascular surgery for evaluation and revascularization decisions",
        "Supervised exercise therapy program",
        "Podiatry and wound care",
        "Tobacco quitline (1-800-QUIT-NOW) and community support resources",
      ],
    },
    basis: ["2024 ACC/AHA Multisociety Guideline for Lower Extremity Peripheral Artery Disease"],
  },

  // ---------------------------------------------------------------------------------------------------
  {
    key: "stroke",
    education: {
      en: {
        title: "Life after a stroke",
        whatItIs: "A stroke happens when blood flow to part of the brain is blocked or a blood vessel in the brain bleeds. This hurts brain cells and can change how you move, talk, think, swallow, or feel. Many people keep getting better for months with therapy and practice.",
        whyItMatters: "Having one stroke raises your chance of having another. Controlling your blood pressure and other risks, and taking your medicines, can greatly lower that chance.",
        whatYouCanDo: [
          "Do your therapy exercises every day, even small ones. Practice helps your brain relearn skills.",
          "Check your blood pressure at home and write down the numbers.",
          "Make your home safer: clear clutter and loose rugs, add night lights, and use grab bars or a shower chair.",
          "If swallowing is hard, sit up straight to eat, take small bites and sips, and follow the tips your therapist gave you.",
          "Eat more vegetables, fruits, beans, fish, and whole grains, and use less salt.",
          "If you smoke, ask us for help quitting, and limit alcohol.",
          "Stay in touch with family, friends, or a stroke support group. Feeling sad or worried after a stroke is common, and it can be treated.",
        ],
        numbers: [
          "Blood pressure: below 130/80, or the goal your provider sets for you.",
          "LDL (\"bad\") cholesterol: below 70 for many people after a stroke, or the goal your provider sets for you.",
          "A1c if you have diabetes: below 7% for many adults, or the goal your provider sets for you.",
        ],
        medicines: [
          "Medicines that lower blood pressure, lower cholesterol, or prevent clots help keep you from having another stroke. Take them every day as prescribed.",
          "Do not stop any medicine without talking to us. Stopping a medicine that prevents clots can raise your risk of another stroke.",
          "If you take a blood thinner, tell us about bleeding gums, nosebleeds, easy bruising, or black stools.",
          "If pills are hard to swallow, ask us before you crush or split them, since some must be swallowed whole. Bring all your medicine bottles to every visit.",
        ],
        callUs: [
          "You have new or worse trouble swallowing, or you cough or choke when you eat or drink.",
          "You feel sad, hopeless, or worried most days, or you no longer enjoy things you used to.",
          "You have fallen, or you feel less steady on your feet.",
          "You have new problems with memory, bladder control, muscle stiffness, or pain.",
          "You have side effects, or you have trouble getting your medicines, therapy, or equipment.",
        ],
        call911: [
          "You have any new stroke signs, even if they go away. Think BE FAST: Balance loss, Eyes (sudden trouble seeing), Face drooping, Arm or leg weakness, Speech that is slurred or strange, Time to call 911. Note the time the signs started.",
          "You have a seizure, or you fall and hit your head while taking a blood thinner.",
          "You have chest pain or pressure, or sudden trouble breathing.",
          "You have thoughts of hurting yourself and are in danger now. You can also call or text 988, the Suicide and Crisis Lifeline, any time.",
        ],
      },
      es: {
        title: "La vida después de un derrame cerebral",
        whatItIs: "Un derrame cerebral (accidente cerebrovascular) ocurre cuando se tapa el paso de la sangre a una parte del cerebro o cuando se rompe un vaso sanguíneo del cerebro. Esto daña las células del cerebro y puede cambiar la forma en que usted se mueve, habla, piensa, traga o siente. Muchas personas siguen mejorando durante meses con terapia y práctica.",
        whyItMatters: "Haber tenido un derrame aumenta el riesgo de tener otro. Controlar la presión y otros riesgos, y tomar sus medicinas, puede bajar mucho ese riesgo.",
        whatYouCanDo: [
          "Haga sus ejercicios de terapia todos los días, aunque sean pequeños. La práctica le ayuda al cerebro a volver a aprender.",
          "Mídase la presión en casa y anote los números.",
          "Haga su casa más segura: quite el desorden y las alfombras o tapetes sueltos, ponga luces de noche y use barras de apoyo o una silla para la ducha.",
          "Si le cuesta tragar, siéntese con la espalda recta para comer, dé bocados y sorbos pequeños, y siga los consejos que le dio su terapeuta.",
          "Coma más verduras, frutas, frijoles, pescado y granos integrales, y use menos sal.",
          "Si fuma, pídanos ayuda para dejarlo, y tome poco alcohol.",
          "Manténgase en contacto con su familia, sus amistades o un grupo de apoyo para personas que han tenido un derrame. Es común sentir tristeza o preocupación después de un derrame, y tiene tratamiento.",
        ],
        numbers: [
          "Presión arterial: menos de 130/80, o la meta que su proveedor le indique.",
          "Colesterol LDL (el \"malo\"): menos de 70 para muchas personas que han tenido un derrame, o la meta que su proveedor le indique.",
          "A1c, si tiene diabetes: menos de 7% para muchos adultos, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas que bajan la presión, bajan el colesterol o evitan los coágulos le ayudan a no tener otro derrame. Tómelas todos los días como se las recetaron.",
          "No deje ninguna medicina sin hablar con nosotros. Dejar una medicina que evita los coágulos puede aumentar el riesgo de otro derrame.",
          "Si toma un anticoagulante, avísenos si le sangran las encías o la nariz, si le salen moretones con facilidad o si tiene heces negras.",
          "Si le cuesta tragar las pastillas, pregúntenos antes de molerlas o partirlas, porque algunas se deben tragar enteras. Traiga todos sus frascos de medicina a cada cita.",
        ],
        callUs: [
          "Le cuesta más tragar, o tose o se atraganta al comer o beber.",
          "Siente tristeza, desesperanza o preocupación casi todos los días, o ya no disfruta las cosas que antes le gustaban.",
          "Se ha caído, o se siente menos firme al caminar.",
          "Tiene problemas nuevos con la memoria, para controlar la orina, rigidez en los músculos o dolor.",
          "Tiene efectos secundarios, o le cuesta conseguir sus medicinas, su terapia o su equipo médico.",
        ],
        call911: [
          "Tiene cualquier señal nueva de derrame, aunque se le quite. Recuerde la palabra RÁPIDO: Rostro caído de un lado, Alteración del equilibrio, Pérdida de fuerza en un brazo o una pierna, Impedimento repentino para ver, Dificultad para hablar, Obtenga ayuda llamando al 911. Fíjese en la hora en que empezaron las señales.",
          "Tiene una convulsión, o se cae y se golpea la cabeza mientras toma un anticoagulante.",
          "Tiene dolor o presión en el pecho, o de repente le falta el aire.",
          "Tiene pensamientos de hacerse daño y está en peligro ahora mismo. También puede llamar o enviar un mensaje de texto al 988, la Línea de Prevención del Suicidio y Crisis, a cualquier hora (para español, marque 2).",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Review BE FAST and calling 911 right away for any new symptoms, even if they go away, and noting the time they started.",
        "Reinforce taking medicines every day to prevent another stroke, and never stopping clot-preventing medicine without the provider.",
        "Encourage the daily home exercises from physical, occupational, and speech therapy, and any safe-swallowing tips.",
        "Review fall prevention at home: clear paths, night lights, grab bars, sturdy shoes, and using a walker or cane as instructed.",
        "Let the patient and caregiver know that mood changes after a stroke are common and that help is available.",
        "Check in on how the caregiver is doing, and offer community resources.",
      ],
      ask: [
        "What have your home blood pressure readings been?",
        "Are you able to take all your medicines every day? Any trouble swallowing pills or getting refills?",
        "Have you had any falls or near-falls, or new problems with walking, speech, or swallowing?",
        "How has your mood been? Have you felt down or lost interest in things you used to enjoy?",
        "Are you still getting therapy, and do you have the equipment and help you need at home?",
      ],
    },
    carePlan: {
      problem: "Sequelae of stroke (late effects of cerebrovascular disease); specify ischemic or hemorrhagic and residual deficits",
      expectedOutcome: "Stable with rehabilitation and secondary prevention; goal is to maximize function and independence and prevent recurrent stroke, falls, and hospital visits.",
      goals: [
        "BP <130/80 mmHg for most patients (or as individualized by the provider)",
        "LDL-C <70 mg/dL after ischemic stroke with atherosclerotic disease (or as individualized by the provider)",
        "No recurrent stroke or TIA, falls with injury, or aspiration pneumonia over 12 months (or as individualized by the provider)",
        "Functional status (ADLs, mobility) maintained or improved at each quarterly review; A1c <7% if diabetic (or as individualized by the provider)",
      ],
      monitoring: [
        "BP at every visit; home BP reviewed on monthly CCM calls",
        "Lipid panel 4–12 weeks after starting or changing therapy, then every 3–12 months; A1c every 3–6 months if diabetic",
        "Function, mobility, and fall risk at every visit and CCM call; cognitive screen at least annually",
        "Depression screen (PHQ-2/PHQ-9) at least annually and with any mood change, more often in the first year after stroke",
        "Swallowing, nutrition, and weight at every visit; atrial fibrillation screening (ECG or ambulatory monitoring) after cryptogenic ischemic stroke per neurology or cardiology",
      ],
      interventions: [
        "Medication reconciliation and adherence support for antithrombotic (if indicated), BP, and lipid therapy per provider",
        "Provider and neurology manage guideline-directed secondary prevention",
        "Referrals for physical, occupational, and speech-language therapy; home safety evaluation and durable medical equipment as needed",
        "Education on BE FAST and calling 911; individualized fall-prevention plan",
        "Caregiver support and screening for depression, cognitive impairment, and social needs; behavioral health referral when indicated",
        "Tobacco cessation support and screening for obstructive sleep apnea",
      ],
      selfManagement: [
        "Take medicines daily and check home BP as directed",
        "Do home exercise programs from physical, occupational, and speech therapy",
        "Follow safe-swallowing strategies and any diet-texture changes",
        "Follow a heart-healthy, lower-sodium eating pattern; avoid tobacco and limit alcohol",
        "Use assistive devices and home safety changes to prevent falls",
      ],
      symptomManagement: [
        "New BE FAST symptoms, even if transient: call 911 and note the time last known well",
        "Coughing or choking with meals, recurrent pneumonia, or weight loss: speech-language pathology swallow evaluation",
        "Low mood, anxiety, or apathy: PHQ-9 and provider follow-up; suicidal thoughts: 988 or 911 per the practice safety protocol",
        "Falls, spasticity, shoulder pain, or new incontinence: provider evaluation and PT/OT referral",
      ],
      coordination: [
        "Neurology for secondary prevention and post-stroke complications; cardiology as indicated",
        "Rehabilitation services (PT, OT, speech-language pathology) and home health",
        "Behavioral health, including the practice BHI program when enrolled",
        "Community resources: stroke support groups, caregiver support, the local Area Agency on Aging, and transportation",
      ],
    },
    basis: ["2021 AHA/ASA Guideline for the Prevention of Stroke in Patients With Stroke and TIA", "2016 AHA/ASA Guidelines for Adult Stroke Rehabilitation and Recovery"],
  },
];
