import type { ConditionLibraryEntry } from "./types";

// Group C: musculoskeletal, pain and neurologic conditions. DRAFT content for provider review.

export const GROUP_C: ConditionLibraryEntry[] = [
  // ---------------------------------------------------------------- Osteoarthritis
  {
    key: "osteoarthritis",
    education: {
      en: {
        title: "Living with osteoarthritis",
        whatItIs: "Osteoarthritis is the most common kind of arthritis. Over time, the smooth padding at the ends of your bones (called cartilage) wears down. This can make your joints stiff, swollen and sore, most often in the knees, hips, hands and back.",
        whyItMatters: "Joint pain can make it hard to walk, sleep and do the things you enjoy. Staying active and at a healthy weight can ease pain and help you move safely and avoid falls.",
        whatYouCanDo: [
          "Move every day. Walking, swimming, water exercise or a stationary bike are gentle on your joints.",
          "Do simple exercises to make the muscles around your joints stronger. A physical therapist can show you how.",
          "If you carry extra weight, losing even a few pounds takes pressure off your knees and hips.",
          "Use heat to ease stiffness and cold packs to calm swelling, about 15 to 20 minutes at a time.",
          "Use a cane, walker, brace or grab bars if they help you move safely.",
          "Pace yourself. Switch between activity and rest during the day.",
        ],
        numbers: [
          "Pain score: rate your pain from 0 (none) to 10 (worst). A common goal is pain low enough to do your daily activities, or the goal your provider sets for you.",
          "Activity: work up slowly to about 150 minutes of moderate activity a week (for example, 30 minutes, 5 days a week), or the goal your provider sets for you.",
          "Weight: if you are overweight, losing about 5% of your body weight (10 pounds if you weigh 200 pounds) can ease knee and hip pain, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your medicines only as prescribed, and do not stop or change them without talking to us.",
          "Ask us before you take any pain reliever you buy at the store, and never take more than the label says. Some can harm your stomach, kidneys or liver.",
          "Do not drink alcohol while you take pain medicine.",
          "Bring all your medicine bottles to every visit, including vitamins and supplements, and tell us about any side effects.",
        ],
        callUs: [
          "A joint suddenly becomes red, hot and very swollen, especially if you also have a fever.",
          "Your pain is getting worse, or it keeps you from sleeping or doing daily tasks.",
          "You cannot put weight on a joint, or it locks or gives way.",
          "You fall, even if you do not seem hurt.",
          "You have stomach pain or black, sticky stools while taking pain medicine.",
        ],
        call911: [
          "You fall and hit your head, you cannot get up, or you cannot put any weight on your leg after a fall.",
          "You vomit blood or something that looks like coffee grounds, or you have black stools and feel dizzy or faint.",
        ],
      },
      es: {
        title: "Vivir con osteoartritis",
        whatItIs: "La osteoartritis es el tipo de artritis más común. Con el tiempo se desgasta el cartílago, que es el acolchado liso que cubre los extremos de los huesos. Por eso las articulaciones (coyunturas) se ponen rígidas, hinchadas y adoloridas, sobre todo las rodillas, las caderas, las manos y la espalda.",
        whyItMatters: "El dolor en las articulaciones puede hacer difícil caminar, dormir y disfrutar de sus actividades. Mantenerse activo y en un peso saludable puede aliviar el dolor y ayudarle a moverse con seguridad y evitar caídas.",
        whatYouCanDo: [
          "Muévase todos los días. Caminar, nadar, hacer ejercicios en el agua o usar una bicicleta fija no lastiman las articulaciones.",
          "Haga ejercicios sencillos para fortalecer los músculos alrededor de sus articulaciones. Un fisioterapeuta le puede enseñar cómo.",
          "Si tiene sobrepeso, bajar aunque sea unas cuantas libras le quita presión a las rodillas y las caderas.",
          "Use calor para la rigidez y compresas frías para la hinchazón, de 15 a 20 minutos cada vez.",
          "Use bastón, andadera, rodillera o barras de apoyo si le ayudan a moverse con seguridad.",
          "Vaya a su propio ritmo: alterne ratos de actividad con ratos de descanso durante el día.",
        ],
        numbers: [
          "Nivel de dolor: califique su dolor del 0 (nada) al 10 (el peor). Una meta común es que el dolor baje lo suficiente para hacer sus actividades diarias, o la meta que su proveedor le indique.",
          "Actividad: poco a poco, llegue a unos 150 minutos de actividad moderada por semana (por ejemplo, 30 minutos, 5 días a la semana), o la meta que su proveedor le indique.",
          "Peso: si tiene sobrepeso, bajar alrededor del 5% de su peso (10 libras si pesa 200 libras) puede aliviar el dolor de rodillas y caderas, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome sus medicinas solo como se las recetaron, y no las deje ni las cambie sin hablar con nosotros.",
          "Pregúntenos antes de tomar cualquier medicina para el dolor que se compra sin receta, y nunca tome más de lo que dice la etiqueta. Algunas pueden dañar el estómago, los riñones o el hígado.",
          "No tome bebidas alcohólicas mientras use medicinas para el dolor.",
          "Traiga todos sus frascos de medicinas a cada cita, incluso vitaminas y suplementos, y díganos si nota algún efecto secundario.",
        ],
        callUs: [
          "Una articulación se pone de repente roja, caliente y muy hinchada, sobre todo si también tiene fiebre.",
          "El dolor empeora, o no le deja dormir ni hacer sus tareas diarias.",
          "No puede apoyar el peso en una articulación, o esta se traba o se le dobla.",
          "Se cae, aunque no parezca que se lastimó.",
          "Tiene dolor de estómago o heces negras y pegajosas mientras toma medicina para el dolor.",
        ],
        call911: [
          "Se cae y se golpea la cabeza, no se puede levantar, o después de la caída no puede apoyar la pierna.",
          "Vomita sangre o algo que parece café molido, o tiene heces negras y siente mareo o que se va a desmayar.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Movement is medicine: regular low-impact activity (walking, water exercise, cycling, tai chi) lowers pain and stiffness over time.",
        "Reinforce the home exercise program from physical therapy, if one was given.",
        "Heat for stiffness, cold for swelling, and pacing activity with rest through the day.",
        "For patients who are overweight, losing even about 5% of body weight can lessen knee and hip pain.",
        "Pain medicine safety: take as prescribed, no alcohol, and check with the care team before adding any over-the-counter pain reliever.",
        "Fall prevention: use recommended assistive devices, clear walkways, good lighting and sturdy shoes.",
      ],
      ask: [
        "What activities has joint pain made harder for you this month?",
        "On a scale of 0 to 10, how has your pain been on most days, and what helps it?",
        "Have you fallen, nearly fallen, or felt unsteady since we last talked?",
        "How are you taking your pain medicines, and have you noticed any side effects like stomach upset?",
        "Are you able to do your exercises? What gets in the way?",
      ],
    },
    carePlan: {
      problem: "Osteoarthritis (specify joint(s) and laterality, e.g., primary osteoarthritis of the right knee)",
      expectedOutcome: "Osteoarthritis is chronic and may slowly progress; the expected outcome is less pain, maintained or improved joint function and mobility, and prevention of falls and medication-related harm.",
      goals: [
        "Clinically meaningful pain reduction (at least 2 points or 30% on a 0–10 scale) with improved ability to perform daily activities within 3 months (or as individualized by the provider).",
        "At least 150 minutes per week of moderate low-impact activity plus muscle strengthening 2 or more days per week (or as individualized by the provider).",
        "For overweight or obese patients with knee or hip OA, weight loss of at least 5% of body weight within 6 months (or as individualized by the provider).",
        "Independent mobility and ADLs maintained, with no injurious falls over 12 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Pain score (0–10) and functional status (ADLs, walking tolerance) at each monthly CCM contact and office visit.",
        "Fall history at each monthly CCM contact; fall-risk screening (e.g., STEADI) at least annually and after any fall.",
        "Weight/BMI at each office visit.",
        "Medication reconciliation, including over-the-counter analgesics and supplements, at each visit and monthly CCM contact.",
        "For patients on regular oral NSAIDs: blood pressure each visit and renal function at least annually, or more often per provider.",
      ],
      interventions: [
        "Referral to physical therapy for strengthening, range-of-motion and balance training; occupational therapy for hand OA and daily-task adaptation as needed.",
        "Fall-risk assessment and home safety review; recommend assistive devices (cane, walker, bracing) as appropriate.",
        "Weight-management counseling and/or nutrition referral when indicated.",
        "Pain management therapy per provider, emphasizing non-drug approaches and medication safety education.",
        "Referral to evidence-based community programs (tai chi, arthritis exercise or walking programs).",
        "Orthopedic referral when symptoms are severe and refractory to conservative care, per provider.",
      ],
      selfManagement: [
        "Complete the home exercise program and low-impact activity most days of the week.",
        "Use heat, cold and activity pacing to manage flares.",
        "Use assistive devices and supportive footwear as recommended.",
        "Take pain medicines only as prescribed; avoid alcohol and check before adding over-the-counter pain relievers.",
        "Track pain and activity and report changes to the care team.",
      ],
      symptomManagement: [
        "Flare of joint pain or stiffness: activity pacing, heat/cold and as-needed therapy per provider; contact the care team if not improving within 1–2 weeks.",
        "Acutely hot, red, swollen joint (especially with fever): same-day evaluation to exclude infection or crystal arthritis.",
        "Fall or new instability: same-day triage; emergency evaluation for head injury or inability to bear weight.",
        "GI upset, dark stools or rising blood pressure while taking NSAIDs: notify the provider promptly for evaluation.",
      ],
      coordination: [
        "Physical therapy and occupational therapy.",
        "Orthopedics or sports medicine when conservative care fails; rheumatology if inflammatory arthritis is suspected.",
        "Community exercise and tai chi programs and the Area Agency on Aging for home-safety and transportation support.",
        "Nutrition or weight-management services as needed.",
      ],
    },
    basis: [
      "ACR/Arthritis Foundation Guideline for the Management of Osteoarthritis of the Hand, Hip, and Knee (2019)",
      "CDC STEADI (Stopping Elderly Accidents, Deaths & Injuries) fall-prevention guidance",
      "Physical Activity Guidelines for Americans, 2nd edition (HHS)",
    ],
  },

  // ---------------------------------------------------------------- Rheumatoid arthritis
  {
    key: "rheumatoid",
    education: {
      en: {
        title: "Living with rheumatoid arthritis",
        whatItIs: "Rheumatoid arthritis (RA) is a disease where your immune system, which normally fights germs, attacks the lining of your joints by mistake. This causes pain, swelling and stiffness, often in the hands, wrists and feet on both sides of the body. It can also make you feel very tired.",
        whyItMatters: "Without treatment, RA can damage your joints for good and affect your heart, lungs and eyes. Starting treatment early and staying on it can calm the disease and protect your joints.",
        whatYouCanDo: [
          "Keep every visit with your arthritis specialist (rheumatologist), and get your blood tests on time.",
          "Stay active with gentle exercise like walking, water exercise or stretching. Rest more during flares (times when your symptoms get worse).",
          "Protect your joints. Use both hands to lift things, and use tools with large handles or jar openers.",
          "Wash your hands often and stay away from people who are sick.",
          "Stay up to date on vaccines, like the flu and pneumonia shots. Ask us first, because some vaccines are not safe with certain RA medicines.",
          "If you smoke, quitting helps control RA and helps your medicines work better. We can help you quit.",
          "Take care of your heart with healthy food and activity, because RA raises the risk of heart disease.",
        ],
        numbers: [
          "Symptoms: rate your joint pain and tiredness from 0 to 10, and notice how many minutes your joints stay stiff in the morning. The goal is little or no disease activity, or the goal your provider sets for you.",
          "Blood tests: many RA medicines need blood tests about every 1 to 3 months to check your blood, liver and kidneys, or the goal your provider sets for you.",
          "Activity: aim for about 150 minutes of gentle activity a week, as your joints allow, or the goal your provider sets for you.",
        ],
        medicines: [
          "RA medicines work best when you take them exactly as prescribed. Do not stop or skip them without talking to us or your rheumatologist.",
          "Many RA medicines weaken your body's defense against germs (your immune system). Call us if you have a fever or signs of infection, and tell us before any surgery.",
          "Ask us before taking any pain reliever you buy at the store, and ask whether alcohol is safe with your medicines. Some RA medicines and alcohol together can harm the liver.",
          "Bring all your medicine bottles to every visit, and tell us about side effects like mouth sores, a rash or an upset stomach.",
        ],
        callUs: [
          "You have a fever of 100.4°F (38°C) or higher, chills, a cough, burning when you urinate, or a red, warm, painful area of skin.",
          "Your joints are more painful, swollen or stiff for more than a few days.",
          "You have new side effects, such as mouth sores, a rash, bruising easily, or yellow skin or eyes.",
          "You have new shortness of breath, a cough that will not go away, or red, painful eyes.",
        ],
        call911: [
          "You have a high fever with confusion or trouble breathing, or you feel very weak or faint.",
          "You have chest pain, or signs of a stroke such as face drooping, arm weakness or trouble speaking.",
        ],
      },
      es: {
        title: "Vivir con artritis reumatoide",
        whatItIs: "La artritis reumatoide (AR) es una enfermedad en la que el sistema inmunitario, que normalmente combate los microbios, ataca por error el revestimiento de las articulaciones. Esto causa dolor, hinchazón y rigidez, a menudo en las manos, las muñecas y los pies de los dos lados del cuerpo. También puede causar mucho cansancio.",
        whyItMatters: "Sin tratamiento, la AR puede dañar las articulaciones para siempre y afectar el corazón, los pulmones y los ojos. Empezar el tratamiento a tiempo y seguirlo puede calmar la enfermedad y proteger sus articulaciones.",
        whatYouCanDo: [
          "No falte a sus citas con el especialista en artritis (reumatólogo), y hágase los análisis de sangre a tiempo.",
          "Manténgase activo con ejercicio suave, como caminar, ejercicios en el agua o estiramientos. Descanse más durante los brotes (épocas en que los síntomas empeoran).",
          "Cuide sus articulaciones. Use las dos manos para levantar cosas y utilice utensilios de mango grueso o abridores de frascos.",
          "Lávese las manos con frecuencia y aléjese de las personas enfermas.",
          "Mantenga sus vacunas al día, como la de la gripe y la de la neumonía. Pregúntenos antes, porque algunas vacunas no son seguras con ciertas medicinas para la AR.",
          "Si fuma, dejarlo ayuda a controlar la AR y a que sus medicinas funcionen mejor. Le podemos ayudar a dejarlo.",
          "Cuide su corazón con comida saludable y actividad, porque la AR aumenta el riesgo de enfermedades del corazón.",
        ],
        numbers: [
          "Síntomas: califique el dolor de sus articulaciones y su cansancio del 0 al 10, y fíjese cuántos minutos le duran rígidas las articulaciones por la mañana. La meta es que la enfermedad esté muy tranquila o sin actividad, o la meta que su proveedor le indique.",
          "Análisis de sangre: muchas medicinas para la AR necesitan análisis más o menos cada 1 a 3 meses para revisar la sangre, el hígado y los riñones, o la meta que su proveedor le indique.",
          "Actividad: trate de hacer unos 150 minutos de actividad suave por semana, según lo permitan sus articulaciones, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas para la AR funcionan mejor si las toma tal como se las recetaron. No las suspenda ni se salte dosis sin hablar con nosotros o con su reumatólogo.",
          "Muchas medicinas para la AR bajan las defensas del cuerpo contra los microbios. Llámenos si tiene fiebre o señales de infección, y avísenos antes de cualquier cirugía.",
          "Pregúntenos antes de tomar cualquier medicina para el dolor sin receta, y pregunte si puede tomar alcohol con sus medicinas. Algunas medicinas para la AR junto con el alcohol pueden dañar el hígado.",
          "Traiga todos sus frascos de medicinas a cada cita, y díganos si tiene efectos secundarios como llagas en la boca, sarpullido o malestar de estómago.",
        ],
        callUs: [
          "Tiene fiebre de 100.4 °F (38 °C) o más, escalofríos, tos, ardor al orinar, o una zona de la piel roja, caliente y dolorosa.",
          "Sus articulaciones están más adoloridas, hinchadas o rígidas por más de unos días.",
          "Tiene efectos secundarios nuevos, como llagas en la boca, sarpullido, moretones con facilidad, o piel u ojos amarillos.",
          "Le falta el aire como antes no le pasaba, tiene una tos que no se quita, o los ojos rojos y adoloridos.",
        ],
        call911: [
          "Tiene fiebre alta con confusión o dificultad para respirar, o se siente muy débil o a punto de desmayarse.",
          "Tiene dolor de pecho o señales de un derrame cerebral, como la cara caída, debilidad en un brazo o dificultad para hablar.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "RA is an autoimmune disease; steady use of the disease-modifying therapy prescribed by rheumatology protects the joints and prevents lasting damage.",
        "RA medicines should not be stopped or skipped without talking to the prescriber, and lab appointments for medicine safety must be kept.",
        "Infection precautions on immune-suppressing medicines: hand-washing, avoiding sick contacts, and reporting fever or infection signs right away.",
        "Vaccines matter; patients should check with the care team or rheumatologist before any vaccine, since some live vaccines are not safe with certain RA medicines.",
        "Joint protection, gentle exercise and pacing, with more rest during flares.",
        "Heart health and quitting smoking are part of RA care, because RA raises cardiovascular risk.",
      ],
      ask: [
        "How have your joints been this month? Any flares, new swelling, or long morning stiffness?",
        "Are you able to take your RA medicines as prescribed? Have any doses or lab draws been missed, and what got in the way?",
        "Have you had any fevers, infections or new side effects?",
        "When is your next rheumatology visit and lab draw, and do you have a way to get there?",
        "What daily tasks are hard for you right now, and how are your mood and energy?",
      ],
    },
    carePlan: {
      problem: "Rheumatoid arthritis (specify seropositive or seronegative and sites involved)",
      expectedOutcome: "Rheumatoid arthritis is a chronic autoimmune disease; with sustained treat-to-target therapy the expected outcome is remission or low disease activity, preserved joint function, and prevention of treatment-related complications.",
      goals: [
        "Remission or low disease activity on a validated measure (e.g., CDAI ≤10 or DAS28 <3.2) within 6 months of a treatment change (or as individualized by the provider).",
        "All DMARD safety labs completed on the schedule set by rheumatology (or as individualized by the provider).",
        "Age-appropriate vaccines up to date (annual influenza, pneumococcal, recombinant zoster, COVID-19) within 6 months, timed with therapy per rheumatology (or as individualized by the provider).",
        "Physical function maintained or improved on a patient-reported measure (e.g., HAQ or MDHAQ) at each rheumatology review (or as individualized by the provider).",
      ],
      monitoring: [
        "Disease activity (e.g., CDAI, RAPID3 or DAS28) at rheumatology visits, typically every 1–3 months with active disease and every 3–6 months when stable, per rheumatology.",
        "DMARD lab monitoring (CBC, liver enzymes, creatinine) per rheumatology, commonly every 4–12 weeks depending on agent and treatment duration.",
        "Infection screening before biologic or targeted therapy (e.g., TB and hepatitis B) per rheumatology; infection symptoms at each monthly CCM contact.",
        "Cardiovascular risk factors: blood pressure each visit; lipids and glucose per primary care schedule.",
        "Bone health: fracture-risk assessment and DEXA as indicated, especially with glucocorticoid exposure.",
        "Pain, function, fatigue, mood and medication adherence at each monthly CCM contact.",
      ],
      interventions: [
        "Track rheumatology follow-up and required lab monitoring; close the loop on results with the patient and specialist.",
        "Monthly medication reconciliation and adherence support; therapy per rheumatology.",
        "Vaccination review and update per the CDC adult schedule, coordinating timing with immunosuppressive therapy per rheumatology.",
        "Referral to physical and/or occupational therapy for joint protection, splints, adaptive devices and exercise.",
        "Cardiovascular risk reduction and smoking-cessation support.",
        "Screen for depression and fall risk; refer to behavioral health as needed.",
      ],
      selfManagement: [
        "Take RA medicines exactly as prescribed and complete scheduled labs.",
        "Follow infection precautions and report fever or infection signs promptly.",
        "Do regular low-impact exercise and joint-protection techniques; pace activity during flares.",
        "Avoid smoking and limit alcohol per provider guidance.",
        "Keep a symptom diary (flares, morning stiffness, side effects) to bring to visits.",
      ],
      symptomManagement: [
        "Flare (more swollen or tender joints, prolonged morning stiffness): contact rheumatology or primary care within a few days for a flare plan per provider.",
        "Fever or infection signs on immunosuppressive therapy: same-day evaluation; any decision to hold therapy is made by the provider or rheumatology.",
        "New cough or shortness of breath, eye pain or redness, or medication side effects (mouth ulcers, rash, jaundice, unusual bruising): prompt provider evaluation.",
      ],
      coordination: [
        "Rheumatology for disease-modifying therapy and treat-to-target monitoring.",
        "Physical and occupational therapy.",
        "Ophthalmology for retinal screening when required by therapy, or for eye symptoms.",
        "Behavioral health and community resources (Arthritis Foundation, Area Agency on Aging) as needed.",
      ],
    },
    basis: [
      "ACR Guideline for the Treatment of Rheumatoid Arthritis (2021)",
      "ACR Guideline for Vaccinations in Patients with Rheumatic and Musculoskeletal Diseases (2022)",
      "EULAR recommendations for the management of rheumatoid arthritis (2022 update)",
    ],
  },

  // ---------------------------------------------------------------- Osteoporosis
  {
    key: "osteoporosis",
    education: {
      en: {
        title: "Living with osteoporosis",
        whatItIs: "Osteoporosis means your bones have become thin and weak. Weak bones can break easily, even from a small fall or a bump. You usually cannot feel your bones getting weaker, so a bone density test is how we find it.",
        whyItMatters: "A broken hip, wrist or spine bone can cause pain, a stooped back and loss of independence. Treatment, exercise and preventing falls can make your bones stronger and lower your chance of a break.",
        whatYouCanDo: [
          "Get enough calcium, mostly from foods like milk, yogurt, cheese, canned fish with soft bones, and leafy greens.",
          "Get enough vitamin D. Ask us if you need a supplement.",
          "Do weight-bearing exercise (exercise on your feet), like walking, plus exercises for strength and balance, such as tai chi.",
          "Make your home safe from falls: remove loose rugs, add night lights, and put grab bars in the bathroom.",
          "Wear sturdy shoes with non-slip soles, and use your cane or walker if you have one.",
          "Do not smoke, and limit alcohol. Both make bones weaker.",
          "Ask us how to bend and lift safely to protect your spine.",
        ],
        numbers: [
          "Calcium: most adults over 50 need about 1,000 to 1,200 mg a day, from food first, or the goal your provider sets for you.",
          "Vitamin D: most adults over 50 need about 800 to 1,000 IU (international units) a day, or the goal your provider sets for you.",
          "Bone density test (a quick, painless scan): usually about every 2 years, or the goal your provider sets for you.",
          "Exercise: walk or do other activity on your feet most days, and do strength and balance exercises 2 to 3 days a week, or the goal your provider sets for you.",
        ],
        medicines: [
          "Bone medicines lower your chance of breaking a bone. Take them exactly as prescribed, including any special directions about food, water or staying upright.",
          "Do not stop your bone medicine or skip a shot without talking to us. With some bone medicines, stopping suddenly can raise your risk of breaking a bone in your spine.",
          "Tell your dentist you take a bone medicine, and keep up with regular dental checkups.",
          "Bring all your medicine bottles and supplements to every visit, and tell us about side effects like heartburn or trouble swallowing.",
        ],
        callUs: [
          "You fall, even if you do not seem hurt.",
          "You have sudden new back pain, or you notice you are getting shorter or more bent over.",
          "You have new pain in your thigh or groin, or jaw pain or a sore in your mouth that does not heal.",
          "You have pain or trouble when swallowing while taking a bone medicine.",
        ],
        call911: [
          "You fall and hit your head, or you cannot get up.",
          "After a fall, you cannot stand or put weight on your leg, or you have severe pain in your hip, back or neck.",
        ],
      },
      es: {
        title: "Vivir con osteoporosis",
        whatItIs: "La osteoporosis quiere decir que sus huesos se han vuelto delgados y débiles. Los huesos débiles se pueden romper con facilidad, incluso con una caída pequeña o un golpe. Por lo general uno no siente que los huesos se debilitan; por eso usamos una prueba de densidad ósea para detectarla.",
        whyItMatters: "Una fractura de cadera, muñeca o columna puede causar dolor, una espalda encorvada y pérdida de independencia. El tratamiento, el ejercicio y evitar caídas pueden fortalecer sus huesos y bajar el riesgo de una fractura.",
        whatYouCanDo: [
          "Consuma suficiente calcio, sobre todo de alimentos como leche, yogur, queso, sardinas o salmón enlatado con sus huesitos y verduras de hoja verde.",
          "Obtenga suficiente vitamina D. Pregúntenos si necesita un suplemento.",
          "Haga ejercicios de pie en los que sostenga su propio peso, como caminar, además de ejercicios de fuerza y equilibrio, como el taichí.",
          "Prepare su casa para evitar caídas: quite los tapetes sueltos, ponga luces de noche e instale barras de apoyo en el baño.",
          "Use zapatos firmes con suela antideslizante, y use su bastón o andadera si tiene uno.",
          "No fume y limite el alcohol. Los dos debilitan los huesos.",
          "Pregúntenos cómo agacharse y levantar cosas de forma segura para proteger su columna.",
        ],
        numbers: [
          "Calcio: la mayoría de los adultos mayores de 50 años necesitan de 1,000 a 1,200 mg al día, de preferencia de los alimentos, o la meta que su proveedor le indique.",
          "Vitamina D: la mayoría de los adultos mayores de 50 años necesitan de 800 a 1,000 UI (unidades internacionales) al día, o la meta que su proveedor le indique.",
          "Prueba de densidad ósea (un estudio rápido y sin dolor): por lo general cada 2 años, o la meta que su proveedor le indique.",
          "Ejercicio: camine o haga otra actividad de pie la mayoría de los días, y haga ejercicios de fuerza y equilibrio de 2 a 3 días por semana, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas para los huesos bajan el riesgo de una fractura. Tómelas tal como se las recetaron y siga las instrucciones especiales sobre la comida, el agua o mantenerse derecho después de tomarlas.",
          "No deje su medicina para los huesos ni falte a una inyección sin hablar con nosotros. Con algunas de estas medicinas, suspenderlas de golpe puede aumentar el riesgo de fracturas en la columna.",
          "Dígale a su dentista que toma una medicina para los huesos, y vaya a sus chequeos dentales con regularidad.",
          "Traiga todos sus frascos de medicinas y suplementos a cada cita, y díganos si tiene efectos secundarios como acidez o dificultad para tragar.",
        ],
        callUs: [
          "Se cae, aunque no parezca que se lastimó.",
          "Tiene un dolor de espalda nuevo que empezó de repente, o nota que está perdiendo estatura o se está encorvando.",
          "Tiene un dolor nuevo en el muslo o la ingle, o dolor en la mandíbula o una llaga en la boca que no sana.",
          "Siente dolor o dificultad al tragar mientras toma una medicina para los huesos.",
        ],
        call911: [
          "Se cae y se golpea la cabeza, o no se puede levantar.",
          "Después de una caída no puede pararse ni apoyar la pierna, o tiene un dolor fuerte en la cadera, la espalda o el cuello.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Osteoporosis has no symptoms until a bone breaks; the whole point of care is preventing fractures.",
        "Calcium mostly from food, vitamin D as advised, and regular weight-bearing, strength and balance exercise.",
        "Take bone medicine exactly as directed, including any special instructions, and do not stop or skip doses without talking to the provider.",
        "Fall prevention at home: clear walkways, good lighting, grab bars, non-slip shoes and using assistive devices.",
        "See the dentist regularly and tell them about any bone medicine.",
        "Keep the bone density test and any injection or infusion appointments on schedule.",
      ],
      ask: [
        "Have you fallen, nearly fallen, or felt dizzy or unsteady since our last call?",
        "How are you taking your bone medicine, and is anything making it hard to take?",
        "What do you usually eat or take each day for calcium and vitamin D?",
        "Is there anything at home that worries you about tripping, like rugs, stairs or poor lighting?",
        "Have you had any new back, hip, thigh or jaw pain?",
      ],
    },
    carePlan: {
      problem: "Osteoporosis, age-related or postmenopausal (specify with or without current pathological fracture)",
      expectedOutcome: "With treatment and fall prevention, bone density is expected to stabilize or improve and fragility-fracture risk to decrease, preserving mobility and independence.",
      goals: [
        "No new fragility fractures over the next 12 months (or as individualized by the provider).",
        "Stable or improved bone mineral density on follow-up DEXA, with no decline greater than the least significant change (or as individualized by the provider).",
        "Daily intake of calcium 1,000–1,200 mg (diet first) and vitamin D 800–1,000 IU (or as individualized by the provider).",
        "At least 80% adherence to prescribed osteoporosis therapy and weight-bearing/balance exercise at least 3 days per week (or as individualized by the provider).",
      ],
      monitoring: [
        "DEXA (hip and spine) every 2 years or as indicated, per provider.",
        "Height annually; vertebral imaging per provider for significant height loss (e.g., 1.5 inches/4 cm historical or 0.8 inch/2 cm measured) or new back pain.",
        "Fall history at each monthly CCM contact; fall-risk screening at least annually and after any fall.",
        "Serum calcium, 25-hydroxyvitamin D and renal function before and during therapy as indicated, per provider.",
        "Periodic reassessment of fracture risk and treatment duration per provider and guideline.",
        "Medication adherence and side effects at each monthly CCM contact.",
      ],
      interventions: [
        "Fracture-risk assessment (e.g., FRAX) and pharmacologic therapy per provider.",
        "Fall-risk assessment and home safety evaluation; referral to physical therapy for strength, balance and posture training.",
        "Nutrition counseling on calcium, vitamin D and protein intake.",
        "Medication review to reduce fall-risk and bone-harming medications where possible, per provider.",
        "Dental health review before and during antiresorptive therapy, per provider.",
        "Smoking-cessation and alcohol-reduction support as needed.",
      ],
      selfManagement: [
        "Take osteoporosis medicine exactly as directed and keep injection or infusion appointments on schedule.",
        "Meet daily calcium and vitamin D goals, food first.",
        "Do weight-bearing, muscle-strengthening and balance exercise most days.",
        "Keep the home free of fall hazards and use assistive devices as recommended.",
        "Avoid smoking and limit alcohol.",
      ],
      symptomManagement: [
        "Sudden back pain or height loss: notify the provider for evaluation of possible vertebral fracture.",
        "Fall: same-day triage; emergency care for head injury, inability to get up or inability to bear weight.",
        "New thigh or groin pain, jaw pain or a non-healing oral lesion on therapy: prompt provider evaluation for atypical femur fracture or osteonecrosis of the jaw.",
        "Upper GI symptoms with oral therapy: notify the provider to review administration or alternatives.",
      ],
      coordination: [
        "Physical therapy for strength, balance and posture training; occupational therapy for home safety.",
        "Endocrinology or a bone specialist for very high fracture risk or complex cases, per provider.",
        "Dentistry for routine care while on antiresorptive therapy.",
        "Community fall-prevention programs (e.g., tai chi, A Matter of Balance) through the Area Agency on Aging.",
      ],
    },
    basis: [
      "Bone Health & Osteoporosis Foundation Clinician's Guide to Prevention and Treatment of Osteoporosis (2022)",
      "CDC STEADI (Stopping Elderly Accidents, Deaths & Injuries) fall-prevention guidance",
    ],
  },

  // ---------------------------------------------------------------- Chronic pain
  {
    key: "chronic_pain",
    education: {
      en: {
        title: "Living with chronic pain",
        whatItIs: "Chronic pain is pain that lasts more than 3 months. It can come from arthritis, an old injury, nerve problems or other health issues. Sometimes the pain keeps going even after the body has healed.",
        whyItMatters: "Long-lasting pain can affect your sleep, mood, activity and relationships. A plan that mixes activity, healthy habits and safe use of medicine can help you do more of what matters to you.",
        whatYouCanDo: [
          "Set small, real goals, like walking to the mailbox or cooking a meal, and build up slowly.",
          "Stay as active as you can. Gentle movement, stretching and physical therapy can ease pain over time.",
          "Pace yourself. Break big jobs into small parts, and rest before the pain gets bad.",
          "Use heat, cold, gentle massage or slow, relaxing breaths to calm pain.",
          "Keep a regular sleep schedule. Good sleep can lower pain.",
          "Stay connected with friends, family and activities you enjoy. Tell us if you feel down or worried; talking with a counselor can help with pain.",
          "Write down your pain level and what you were able to do each day, and bring it to your visits.",
        ],
        numbers: [
          "Pain score: rate your pain from 0 (no pain) to 10 (worst pain). Pain may not go away fully; a common goal is to lower it enough to do what matters to you, or the goal your provider sets for you.",
          "Function: pick 1 or 2 daily activities you want to do more of (for example, walking 10 minutes or doing light chores) and track your progress, or the goal your provider sets for you.",
          "Sleep: aim for 7 to 8 hours of sleep a night, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take pain medicine only as prescribed. Do not take extra doses, and do not stop suddenly without talking to us.",
          "Do not mix pain medicine with alcohol, sleeping pills or anxiety medicines. Ask us before taking any pain reliever you buy at the store.",
          "If you take an opioid (a strong prescription pain medicine), keep it locked up and never share it. If we prescribed naloxone (a nose spray that can reverse an overdose), keep it where your family can find it and show them how to use it.",
          "Bring all your medicine bottles to every visit, and tell us about side effects like constipation, sleepiness or dizziness.",
        ],
        callUs: [
          "Your pain is much worse, or you have a new kind of pain.",
          "Your medicine is not helping, or you run out before your next refill.",
          "You have side effects like bad constipation, feeling very sleepy, dizziness or falls.",
          "You feel sad, hopeless or very worried most days, or you are drinking more alcohol to cope.",
          "You have new numbness, tingling or weakness in your arms or legs.",
        ],
        call911: [
          "Someone is very hard to wake up, has slow or shallow breathing, or has blue or gray lips after taking pain medicine. Give naloxone if you have it, then call 911.",
          "You suddenly cannot control your bladder or bowels, or you have new numbness between your legs or new weakness in both legs.",
          "You have thoughts of hurting yourself or ending your life. Call or text 988 (the Suicide and Crisis Lifeline), or call 911 if you are in danger right now.",
        ],
      },
      es: {
        title: "Vivir con dolor crónico",
        whatItIs: "El dolor crónico es un dolor que dura más de 3 meses. Puede venir de la artritis, una lesión antigua, problemas de los nervios u otros problemas de salud. A veces el dolor sigue aunque el cuerpo ya haya sanado.",
        whyItMatters: "Un dolor que dura mucho tiempo puede afectar el sueño, el ánimo, la actividad y las relaciones con los demás. Un plan que combine actividad, hábitos sanos y el uso seguro de las medicinas puede ayudarle a hacer más de lo que le importa.",
        whatYouCanDo: [
          "Póngase metas pequeñas y realistas, como caminar hasta el buzón o preparar una comida, y vaya aumentando poco a poco.",
          "Manténgase lo más activo que pueda. El movimiento suave, los estiramientos y la fisioterapia pueden aliviar el dolor con el tiempo.",
          "Vaya a su ritmo. Divida las tareas grandes en partes pequeñas y descanse antes de que el dolor empeore.",
          "Use calor, frío, masajes suaves o respiraciones lentas y relajantes para calmar el dolor.",
          "Acuéstese y levántese a la misma hora todos los días. Dormir bien puede bajar el dolor.",
          "Siga en contacto con amigos, familia y actividades que disfruta. Díganos si siente tristeza o preocupación; hablar con un consejero puede ayudar con el dolor.",
          "Anote su nivel de dolor y lo que pudo hacer cada día, y traiga sus notas a las citas.",
        ],
        numbers: [
          "Nivel de dolor: califique su dolor del 0 (nada de dolor) al 10 (el peor dolor). Puede que el dolor no desaparezca del todo; una meta común es bajarlo lo suficiente para hacer lo que le importa, o la meta que su proveedor le indique.",
          "Actividad: escoja 1 o 2 actividades diarias que quiera hacer más (por ejemplo, caminar 10 minutos o hacer quehaceres ligeros) y anote su progreso, o la meta que su proveedor le indique.",
          "Sueño: trate de dormir de 7 a 8 horas cada noche, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome la medicina para el dolor solo como se la recetaron. No tome dosis de más ni la deje de golpe sin hablar con nosotros.",
          "No mezcle la medicina para el dolor con alcohol, pastillas para dormir ni medicinas para los nervios o la ansiedad. Pregúntenos antes de tomar cualquier medicina para el dolor sin receta.",
          "Si toma un opioide (una medicina fuerte para el dolor, con receta), guárdelo bajo llave y nunca lo comparta. Si le recetamos naloxona (un aerosol nasal que puede revertir una sobredosis), téngala donde su familia la encuentre y enséñeles a usarla.",
          "Traiga todos sus frascos de medicinas a cada cita, y díganos si tiene efectos secundarios como estreñimiento, mucho sueño o mareos.",
        ],
        callUs: [
          "El dolor está mucho peor, o tiene un tipo de dolor nuevo.",
          "Su medicina no le está ayudando, o se le acaba antes de su próximo resurtido.",
          "Tiene efectos secundarios como estreñimiento fuerte, mucho sueño, mareos o caídas.",
          "Siente tristeza, desesperanza o mucha preocupación la mayoría de los días, o está tomando más alcohol para sobrellevarlo.",
          "Tiene adormecimiento, hormigueo o debilidad nuevos en los brazos o las piernas.",
        ],
        call911: [
          "Una persona está muy difícil de despertar, respira lento o muy poco, o tiene los labios morados o grises después de tomar medicina para el dolor. Dele naloxona si la tiene y llame al 911.",
          "De repente no puede controlar la orina o las evacuaciones, o siente adormecida la zona entre las piernas o debilidad nueva en las dos piernas.",
          "Tiene pensamientos de hacerse daño o de quitarse la vida. Llame o envíe un mensaje de texto al 988 (Línea de Prevención del Suicidio y Crisis; oprima 2 para español), o llame al 911 si corre peligro en este momento.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "The goal of chronic pain care is better function and quality of life; pain may not go to zero.",
        "Pacing, gentle daily activity and following the physical therapy plan help over time.",
        "Non-drug tools: heat or cold, relaxation and breathing, regular sleep habits, and staying socially connected.",
        "Medication safety: take as prescribed, no alcohol, no extra over-the-counter pain relievers without checking, and keep opioids locked up.",
        "If naloxone was prescribed, confirm the patient and family know where it is and how to use it.",
        "Mood and pain affect each other; counseling or behavioral health support is a normal part of pain care.",
      ],
      ask: [
        "What is one thing you were able to do this month, and what has pain kept you from doing?",
        "How would you rate your pain on most days, and how is it affecting your sleep?",
        "Are you having any trouble with your pain medicines, such as side effects or running short before a refill?",
        "How has your mood been? Have you felt down, anxious or hopeless?",
        "Have you fallen, or felt unsteady or drowsy during the day?",
      ],
    },
    carePlan: {
      problem: "Chronic pain (specify type, site and etiology, e.g., chronic low back pain due to lumbar spondylosis)",
      expectedOutcome: "Chronic pain is often persistent; the expected outcome is improved function, sleep and quality of life with safe, multimodal treatment and minimal medication-related harm.",
      goals: [
        "Clinically meaningful improvement in pain and function, e.g., at least 30% improvement on the PEG scale (Pain, Enjoyment of life, General activity) within 3 months (or as individualized by the provider).",
        "Achieve 1–2 patient-chosen functional goals (e.g., walk 20 minutes daily, return to a hobby) within 3 months (or as individualized by the provider).",
        "For long-term opioid therapy: controlled-substance agreement on file, naloxone prescribed with patient/caregiver training, and no unplanned dose escalation over 12 months (or as individualized by the provider).",
        "For patients screening positive for depression, PHQ-9 below 10 or improved by at least 50% within 6 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Pain and function (e.g., PEG scale) at each monthly CCM contact and office visit.",
        "For chronic opioid therapy: PDMP check before each prescription and at least every 3 months; benefits and harms reviewed at least every 3 months; urine drug testing considered at least annually, per CDC 2022 guidance.",
        "Controlled-substance agreement reviewed and renewed at least annually for patients on chronic opioid therapy.",
        "Depression (PHQ-2/PHQ-9), anxiety and substance-use screening at least annually and when symptoms change.",
        "Sedation, constipation, falls and sleep quality at each monthly CCM contact.",
      ],
      interventions: [
        "Multimodal pain plan per provider, prioritizing non-drug therapies (exercise therapy, physical therapy, cognitive behavioral therapy, mindfulness) and nonopioid options.",
        "Referral to physical therapy and/or behavioral health (pain-focused CBT) as appropriate.",
        "For patients on opioids: risk assessment, naloxone education, and safe storage and disposal education, per provider.",
        "Fall-risk assessment and review of sedating medications.",
        "Referral to pain management or specialty care for complex or refractory pain, per provider.",
      ],
      selfManagement: [
        "Follow a daily activity and pacing plan and the home exercise program.",
        "Use non-drug strategies (heat or cold, relaxation, sleep routine) daily.",
        "Take pain medicines only as prescribed; avoid alcohol and other sedatives; store controlled medicines locked.",
        "Keep a pain and function diary and bring it to visits.",
        "Participate in counseling or support groups as referred.",
      ],
      symptomManagement: [
        "Pain flare: follow the flare plan (activity modification, heat or cold, relaxation, as-needed therapy per provider); contact the care team if pain is not improving or is new or different.",
        "Oversedation or slowed breathing on opioids: give naloxone if available and call 911; provider reviews the regimen afterward.",
        "Red flags (new neurologic deficit, bowel or bladder dysfunction, fever with back pain, unexplained weight loss): urgent evaluation.",
        "Worsening depression or anxiety, or suicidal thoughts: same-day behavioral health assessment; 988 for crisis.",
      ],
      coordination: [
        "Pain management specialist and physical therapy.",
        "Behavioral health (pain-focused CBT, depression and anxiety care) and substance use treatment services when indicated.",
        "Pharmacy for medication review and safe medication disposal programs.",
        "Community resources (senior centers, exercise programs, Area Agency on Aging) to support activity and social connection.",
      ],
    },
    basis: [
      "CDC Clinical Practice Guideline for Prescribing Opioids for Pain (2022)",
      "HHS Pain Management Best Practices Inter-Agency Task Force Report (2019)",
    ],
  },

  // ---------------------------------------------------------------- Dementia / Alzheimer's
  {
    key: "dementia",
    education: {
      en: {
        title: "Living with memory loss (dementia): a guide for you and your family",
        whatItIs: "Dementia is a group of brain diseases that slowly make it harder to remember, think, make decisions and handle daily tasks. Alzheimer's disease is the most common kind. Dementia is not a normal part of getting older.",
        whyItMatters: "Dementia usually gets worse over time, but good care can help you stay safe, comfortable and as independent as possible. Planning early lets you make your own choices, and support makes caregiving easier for your family.",
        whatYouCanDo: [
          "Keep a daily routine. Use a calendar, notes and a pill organizer to help you remember.",
          "Stay active in body and mind. Walk, listen to music, garden, and spend time with people you enjoy.",
          "Get your hearing and vision checked. Hearing aids and glasses help you stay alert and connected.",
          "Make your home safe: good lighting, no loose rugs, grab bars, and an ID bracelet in case you get lost.",
          "Talk with us about driving, cooking, money and other tasks that may stop being safe.",
          "Plan ahead while you can. Choose someone to make health decisions for you if you cannot, and share your wishes with your family and with us.",
          "If you care for a family member with dementia, take care of yourself too. Ask for help, take breaks, and tell us if you feel worn out, stressed or alone.",
        ],
        numbers: [],
        medicines: [
          "Take your medicines as prescribed. A family member can help fill a weekly pill box and make sure each dose is taken.",
          "Ask us before starting or stopping any medicine, including sleep aids and products you buy at the store. Some can make confusion worse.",
          "Bring all your medicine bottles to every visit, and tell us about side effects like upset stomach, dizziness, or changes in sleep or behavior.",
        ],
        callUs: [
          "Memory, mood or behavior is changing faster than usual over days or weeks.",
          "There is new trouble eating, drinking or swallowing, or weight loss.",
          "There are new problems with sleep, anger, fear, seeing things that are not there, or wandering.",
          "There is a fall, even without an injury, or new trouble walking.",
          "The caregiver feels overwhelmed, exhausted or unable to keep the person safe at home.",
        ],
        call911: [
          "Sudden confusion, being very hard to wake up, or signs of a stroke: face drooping, arm or leg weakness, or trouble speaking.",
          "A fall with a head injury, or the person cannot get up.",
          "Choking, or trouble breathing while eating or drinking or right after.",
          "The person is lost and cannot be found, or someone is in danger.",
        ],
      },
      es: {
        title: "Vivir con pérdida de memoria (demencia): una guía para usted y su familia",
        whatItIs: "La demencia es un grupo de enfermedades del cerebro que poco a poco hacen más difícil recordar, pensar, tomar decisiones y hacer las tareas diarias. La enfermedad de Alzheimer es el tipo más común. La demencia no es parte normal del envejecimiento.",
        whyItMatters: "Por lo general la demencia avanza con el tiempo, pero un buen cuidado le ayuda a vivir con seguridad, comodidad y la mayor independencia posible. Planear con tiempo le permite tomar sus propias decisiones, y el apoyo le facilita a su familia la tarea de cuidarle.",
        whatYouCanDo: [
          "Siga una rutina diaria. Use un calendario, notas y un pastillero para ayudarse a recordar.",
          "Mantenga activos el cuerpo y la mente. Camine, escuche música, cuide sus plantas y pase tiempo con las personas que quiere.",
          "Revísese la vista y el oído. Los lentes y los aparatos para oír le ayudan a estar alerta y en contacto con los demás.",
          "Haga su casa más segura: buena luz, sin tapetes sueltos, barras de apoyo y una pulsera de identificación por si se pierde.",
          "Hable con nosotros sobre manejar, cocinar, el manejo del dinero y otras tareas que puedan dejar de ser seguras.",
          "Planee con tiempo, mientras pueda. Escoja a una persona que tome decisiones de salud por usted si usted no puede, y comparta sus deseos con su familia y con nosotros.",
          "Si usted cuida a un familiar con demencia, cuídese también. Pida ayuda, tome descansos y avísenos si se siente agotado, estresado o solo.",
        ],
        numbers: [],
        medicines: [
          "Tome sus medicinas como se las recetaron. Un familiar puede ayudarle a llenar un pastillero semanal y asegurarse de que tome cada dosis.",
          "Pregúntenos antes de empezar o dejar cualquier medicina, incluso las pastillas para dormir y los productos que se compran sin receta. Algunas pueden empeorar la confusión.",
          "Traiga todos sus frascos de medicinas a cada cita, y díganos si nota efectos secundarios como malestar de estómago, mareos, o cambios en el sueño o el comportamiento.",
        ],
        callUs: [
          "La memoria, el ánimo o el comportamiento cambian más rápido de lo normal en cuestión de días o semanas.",
          "Aparecen problemas nuevos para comer, beber o tragar, o hay pérdida de peso.",
          "Hay problemas nuevos con el sueño, enojo, miedo, ver cosas que no están ahí, o tendencia a salirse y perderse.",
          "Hay una caída, aunque no haya lesión, o nueva dificultad para caminar.",
          "La persona que cuida se siente abrumada, agotada o sin poder mantener a su ser querido seguro en casa.",
        ],
        call911: [
          "Confusión repentina, mucha dificultad para despertar, o señales de un derrame cerebral: la cara caída, debilidad en un brazo o una pierna, o dificultad para hablar.",
          "Una caída con golpe en la cabeza, o la persona no se puede levantar.",
          "Atragantamiento, o dificultad para respirar al comer o beber o justo después.",
          "La persona se perdió y no la encuentran, o alguien está en peligro.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "With the patient's permission, include the caregiver on calls and confirm who helps with medicines and appointments.",
        "Routines, simple one-step instructions, calendars and pill organizers reduce confusion.",
        "Home safety: remove trip hazards, add lighting, lock up medicines, firearms and chemicals, consider stove safety, and use an ID bracelet if wandering is a risk.",
        "Sudden worsening confusion is not the usual course of dementia; it can signal infection, a medicine problem or a stroke and needs prompt evaluation.",
        "Encourage advance care planning early: naming a health care agent and writing down care wishes.",
        "Caregiver support: respite care, support groups, and the Alzheimer's Association 24/7 Helpline (1-800-272-3900).",
      ],
      ask: [
        "What changes have you or your family noticed in memory, mood, sleep or behavior this month?",
        "Who helps with medicines, and have any doses been missed or taken twice?",
        "Have there been any falls, wandering, getting lost, or safety scares at home or while driving?",
        "For the caregiver: how are you holding up, and what help would make the biggest difference right now?",
        "Have you talked as a family about future care wishes, or named someone to make health decisions?",
      ],
    },
    carePlan: {
      problem: "Dementia / major neurocognitive disorder (specify type, e.g., Alzheimer's disease, vascular, Lewy body or mixed, and severity)",
      expectedOutcome: "Dementia is progressive; goals are function, safety and quality of life for the patient, support for the caregiver, and care consistent with the patient's documented wishes.",
      goals: [
        "Advance directive and health care agent documented in the chart within 6 months (or as individualized by the provider).",
        "No injurious falls, wandering incidents or medication errors over 12 months (or as individualized by the provider).",
        "Primary caregiver identified, educated and screened for strain at least every 6 months, with support resources offered (or as individualized by the provider).",
        "Distressing behavioral and psychological symptoms reduced in frequency or severity on caregiver report (e.g., NPI-Q) within 3 months of identification, using non-drug approaches first (or as individualized by the provider).",
      ],
      monitoring: [
        "Cognitive screening (e.g., MoCA, Mini-Cog or SLUMS) and staging at least annually and with any significant change.",
        "Functional status (ADLs/IADLs) and safety (driving, cooking, finances, wandering, firearms) at least every 6 months, and as reported at each monthly CCM contact.",
        "Behavioral symptoms, mood (depression screen), sleep and pain at each monthly CCM contact.",
        "Weight, nutrition and swallowing at each office visit.",
        "Fall risk at least annually and after any fall; medication review for anticholinergic and sedating drugs (AGS Beers Criteria) at each visit.",
        "Caregiver strain (e.g., Zarit Burden Interview) at least every 6 months.",
      ],
      interventions: [
        "Advance care planning with the patient and family, including health care agent, goals of care and, when appropriate, a portable medical order form (POLST/MOLST).",
        "Fall-risk assessment and home safety evaluation; occupational therapy referral for home safety and daily-task adaptation.",
        "Medication management: simplify the regimen, caregiver-supervised administration, and deprescribing review per provider.",
        "Caregiver education and support: dementia care training, respite options, support groups, and behavioral health referral for caregiver distress as needed.",
        "Driving and firearm safety assessment and counseling.",
        "Evaluate for delirium and reversible contributors with any acute change in cognition or behavior.",
      ],
      selfManagement: [
        "Keep a consistent daily routine for sleep, meals, activity and medicines.",
        "Use memory aids (calendar, notes, pill organizer) with caregiver support.",
        "Stay physically, mentally and socially active as able.",
        "Caregiver keeps an updated medication list, emergency contacts and an ID bracelet for the patient.",
        "Caregiver schedules regular breaks and uses support resources.",
      ],
      symptomManagement: [
        "Acute change in cognition or alertness: same-day evaluation for delirium (infection, medications, dehydration, stroke); 911 for stroke signs or unresponsiveness.",
        "Agitation, sleep disturbance or hallucinations: look for triggers (pain, constipation, infection, environment), use non-drug strategies first, and notify the provider if persistent or unsafe.",
        "Swallowing difficulty or weight loss: speech-language pathology swallow evaluation and nutrition review per provider.",
        "Wandering: door alarms, ID bracelet and a written safety plan; call 911 if the person is missing.",
      ],
      coordination: [
        "Neurology, geriatrics or a memory clinic for diagnosis, staging and complex symptoms.",
        "Alzheimer's Association (24/7 Helpline 1-800-272-3900) and local caregiver support groups.",
        "Area Agency on Aging for in-home services, adult day programs, respite and meals; behavioral health for patient and caregiver.",
        "Palliative care and hospice when consistent with goals of care.",
      ],
    },
    basis: [
      "Alzheimer's Association Clinical Practice Guideline for the Diagnostic Evaluation, Testing, Counseling, and Disclosure of Suspected Alzheimer's Disease and Related Disorders (2024)",
      "AAN Dementia Management Quality Measures",
      "American Geriatrics Society Beers Criteria (2023)",
    ],
  },

  // ---------------------------------------------------------------- Parkinson's disease
  {
    key: "parkinsons",
    education: {
      en: {
        title: "Living with Parkinson's disease",
        whatItIs: "Parkinson's disease is a brain condition that slowly affects how you move. It can cause shaking, stiff muscles, slow movement and trouble with balance. It can also affect sleep, mood, memory, speech, swallowing and bowel habits.",
        whyItMatters: "Parkinson's slowly gets worse over the years, and it raises the risk of falls. Treatment, exercise and a good care team can help you stay active, safe and independent longer.",
        whatYouCanDo: [
          "Exercise every day. Walking, biking, dancing, tai chi and stretching can help your balance, strength and mood.",
          "Work with physical, occupational and speech therapists. They can help with walking, daily tasks, your voice and swallowing.",
          "Prevent falls: remove loose rugs, use night lights and grab bars, and turn slowly. Get up slowly from a bed or chair to avoid dizziness.",
          "Eat foods with fiber and drink plenty of water, unless we told you to limit fluids, to prevent constipation.",
          "Sit up straight when you eat, take small bites and eat slowly. Tell us if food or pills get stuck.",
          "Plan ahead. Share your wishes for future care with your family and with us, and choose someone to make health decisions if you cannot.",
          "Stay connected. Join a Parkinson's support group or exercise class, and tell us if you feel sad or worried or have trouble thinking.",
        ],
        numbers: [
          "Exercise: aim for at least 150 minutes a week of activity that makes you breathe harder, plus balance and strength exercises 2 to 3 days a week, or the goal your provider sets for you.",
          "Medicine times: take each dose of your Parkinson's medicine at its set time every day, or the goal your provider sets for you.",
          "Falls: write down every fall or near fall. The goal is no falls, or the goal your provider sets for you.",
        ],
        medicines: [
          "Take your Parkinson's medicine on time, every time. Even a late dose can bring back shaking, stiffness or slowness.",
          "Never stop your Parkinson's medicine suddenly. Stopping all at once can cause a dangerous reaction with high fever, very stiff muscles and confusion.",
          "If you go to the hospital, bring your medicine list and schedule, and ask that your doses be given on time. Remind every doctor that you have Parkinson's, because some medicines for nausea or mental health can make it worse.",
          "Bring all your medicine bottles to every visit, and tell us about side effects like dizziness when standing, seeing things that are not there, extra movements you cannot control, or strong urges to gamble, shop or eat.",
        ],
        callUs: [
          "Your symptoms are getting worse, or your medicine wears off before the next dose.",
          "You fall, nearly fall, or feel dizzy or faint when you stand up.",
          "You cough or choke when eating or drinking, or you are losing weight.",
          "You see or hear things that are not there, feel confused, or feel very sad or worried.",
          "You have not had a bowel movement in more than 3 days, or you have trouble passing urine.",
        ],
        call911: [
          "Choking that does not stop, or trouble breathing.",
          "A fall with a head injury, or you cannot get up.",
          "High fever with very stiff muscles and confusion, especially after missing or stopping your medicine.",
          "Sudden confusion, or signs of a stroke such as face drooping, arm weakness or trouble speaking.",
        ],
      },
      es: {
        title: "Vivir con la enfermedad de Parkinson",
        whatItIs: "La enfermedad de Parkinson es un trastorno del cerebro que poco a poco afecta sus movimientos. Puede causar temblor, músculos rígidos, movimientos lentos y problemas de equilibrio. También puede afectar el sueño, el ánimo, la memoria, el habla, la capacidad de tragar y el funcionamiento del intestino.",
        whyItMatters: "El Parkinson avanza poco a poco con los años y aumenta el riesgo de caídas. El tratamiento, el ejercicio y un buen equipo de atención le ayudan a mantenerse activo, seguro e independiente por más tiempo.",
        whatYouCanDo: [
          "Haga ejercicio todos los días. Caminar, andar en bicicleta, bailar, hacer taichí y estirarse ayudan al equilibrio, la fuerza y el ánimo.",
          "Trabaje con fisioterapeutas, terapeutas ocupacionales y terapeutas del habla. Le pueden ayudar a caminar, con las tareas diarias, con la voz y al tragar.",
          "Evite caídas: quite los tapetes sueltos, use luces de noche y barras de apoyo, y gire despacio. Levántese despacio de la cama o de la silla para no marearse.",
          "Coma alimentos con fibra y tome bastante agua, a menos que le hayamos pedido limitar los líquidos, para evitar el estreñimiento.",
          "Siéntese derecho al comer, dé bocados pequeños y coma despacio. Díganos si la comida o las pastillas se le atoran.",
          "Planee con tiempo. Comparta con su familia y con nosotros sus deseos para su cuidado en el futuro, y escoja a alguien que tome decisiones de salud por usted si usted no puede.",
          "No se aísle. Únase a un grupo de apoyo o a una clase de ejercicio para personas con Parkinson, y díganos si siente tristeza, preocupación o problemas para pensar.",
        ],
        numbers: [
          "Ejercicio: trate de hacer al menos 150 minutos por semana de actividad que le haga respirar más fuerte, además de ejercicios de equilibrio y fuerza de 2 a 3 días por semana, o la meta que su proveedor le indique.",
          "Horario de medicinas: tome cada dosis de su medicina para el Parkinson a su hora fija todos los días, o la meta que su proveedor le indique.",
          "Caídas: anote cada caída o casi caída. La meta es no tener caídas, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Tome su medicina para el Parkinson a tiempo, siempre. Aun una dosis tardía puede hacer que vuelvan el temblor, la rigidez o la lentitud.",
          "Nunca deje de golpe su medicina para el Parkinson. Suspenderla de repente puede causar una reacción peligrosa con fiebre alta, músculos muy rígidos y confusión.",
          "Si va al hospital, lleve su lista de medicinas con el horario y pida que le den las dosis a tiempo. Recuérdele a cada médico que tiene Parkinson, porque algunas medicinas para las náuseas o para la salud mental lo pueden empeorar.",
          "Traiga todos sus frascos de medicinas a cada cita, y díganos si tiene efectos secundarios como mareo al ponerse de pie, ver cosas que no están ahí, movimientos que no puede controlar, o ganas muy fuertes de apostar, comprar o comer.",
        ],
        callUs: [
          "Sus síntomas empeoran, o el efecto de la medicina se le pasa antes de la siguiente dosis.",
          "Se cae, casi se cae, o se marea o siente que se va a desmayar al ponerse de pie.",
          "Tose o se atraganta al comer o beber, o está bajando de peso.",
          "Ve u oye cosas que no están ahí, se siente confundido, o siente mucha tristeza o preocupación.",
          "Lleva más de 3 días sin evacuar, o le cuesta orinar.",
        ],
        call911: [
          "Se atraganta y no se le quita, o tiene dificultad para respirar.",
          "Se cae y se golpea la cabeza, o no se puede levantar.",
          "Fiebre alta con músculos muy rígidos y confusión, sobre todo si dejó o se saltó su medicina.",
          "Confusión repentina o señales de un derrame cerebral, como la cara caída, debilidad en un brazo o dificultad para hablar.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Medicine timing matters: doses should be taken on schedule, and Parkinson's medicine should never be stopped suddenly.",
        "Daily exercise (walking, cycling, tai chi, dance) helps mobility, balance and mood.",
        "Fall prevention: rise slowly, keep walkways clear, use assistive devices, and report near falls.",
        "Swallowing safety: sit upright and take small bites; report coughing or choking with meals.",
        "Non-movement symptoms (constipation, sleep, mood, memory, dizziness) are part of Parkinson's and should be reported.",
        "If hospitalized, bring the medication schedule, ask for on-time doses, and tell every clinician about the Parkinson's.",
      ],
      ask: [
        "How well is your medicine working through the day? Do symptoms come back before the next dose?",
        "Have you fallen, nearly fallen, or felt your feet freeze in place while walking?",
        "Any coughing, choking or trouble swallowing food or pills?",
        "How are your mood, sleep, memory and bowels?",
        "For the caregiver: how are you managing, and what help do you need?",
      ],
    },
    carePlan: {
      problem: "Parkinson's disease (specify stage, e.g., Hoehn and Yahr, and presence of motor fluctuations or dyskinesia)",
      expectedOutcome: "Parkinson's disease is progressive; goals are function, safety and quality of life, prevention of falls and complications, and care aligned with the patient's goals.",
      goals: [
        "Exercise at least 150 minutes per week including balance and strength training, as tolerated (or as individualized by the provider).",
        "No injurious falls over 12 months, with fall-risk assessment completed at least annually (or as individualized by the provider).",
        "At least 90% of Parkinson's medication doses taken on time by diary or caregiver report (or as individualized by the provider).",
        "Advance directive and health care agent documented within 6 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Motor symptoms, wearing-off, dyskinesia and freezing at each neurology visit (typically every 3–6 months) and at monthly CCM contacts.",
        "Orthostatic blood pressure at each office visit; falls and near falls at each monthly CCM contact.",
        "Swallowing, weight and nutrition at each office visit; speech-language evaluation when symptoms arise.",
        "Depression and anxiety screening, cognition and sleep at least annually and with changes; hallucinations and impulse-control behaviors at each contact.",
        "Constipation and urinary symptoms at each monthly CCM contact.",
      ],
      interventions: [
        "Referral to physical therapy (gait, balance, fall prevention, Parkinson's-specific programs), occupational therapy and speech-language pathology.",
        "Fall-risk assessment and home safety evaluation.",
        "Medication reconciliation with emphasis on dose timing; flag dopamine-blocking medications for review, per provider and neurology.",
        "Advance care planning discussion, including health care agent and goals of care.",
        "Caregiver education and support; screen for caregiver strain.",
        "Provide a wallet card or written schedule listing Parkinson's medications and dose times for hospital and ER visits.",
      ],
      selfManagement: [
        "Take Parkinson's medications on time using alarms or a dosing schedule; keep a symptom and medication diary.",
        "Exercise daily, including balance and strength work.",
        "Rise slowly, use assistive devices as recommended, and keep walkways clear.",
        "Use fiber, fluids and activity for constipation, and safe swallowing techniques at meals.",
        "Carry a medication list and dose schedule for hospital or ER visits.",
      ],
      symptomManagement: [
        "Wearing-off, freezing or new dyskinesia: document timing and notify neurology for therapy adjustment per specialist.",
        "Orthostatic dizziness or falls: same-day triage, fall assessment, and medication and blood pressure review per provider.",
        "Hallucinations, confusion or impulse-control behaviors: prompt provider or neurology review; urgent evaluation if sudden or unsafe.",
        "Coughing or choking with meals, or weight loss: speech-language swallow evaluation and nutrition review; 911 for choking with airway compromise.",
      ],
      coordination: [
        "Neurology or a movement disorder specialist.",
        "Physical, occupational and speech-language therapy.",
        "Parkinson's Foundation and local Parkinson's support and exercise groups; Area Agency on Aging for in-home and caregiver support.",
        "Behavioral health for mood and anxiety, and palliative care when appropriate.",
      ],
    },
    basis: [
      "AAN Parkinson Disease Quality Measurement Set",
      "Parkinson's Foundation exercise and hospital-safety recommendations",
    ],
  },

  // ---------------------------------------------------------------- Epilepsy / seizure disorder
  {
    key: "epilepsy",
    education: {
      en: {
        title: "Living with epilepsy (seizures)",
        whatItIs: "Epilepsy is a brain condition that causes seizures again and again. A seizure is a sudden burst of electrical activity in the brain. It can cause shaking, staring, confusion, or passing out for a short time.",
        whyItMatters: "Seizures can lead to falls, injuries and car crashes, and in rare cases they can be life-threatening. Taking your medicine every day and avoiding your triggers are the best ways to prevent seizures.",
        whatYouCanDo: [
          "Take your seizure medicine at the same times every day. Use a pill box or phone alarm so you do not miss a dose.",
          "Get enough sleep. Not sleeping enough is a common seizure trigger (something that can set off a seizure).",
          "Limit or avoid alcohol, and do not use street drugs. Both can bring on seizures.",
          "Keep a seizure diary: write down the date, time, how long it lasted, what happened and any possible triggers.",
          "Stay safe: take showers instead of baths, never swim alone, and use the back burners on the stove.",
          "Do not drive until your provider says it is safe and your state's rules allow it.",
          "Teach family and friends seizure first aid: stay with you, turn you on your side, time the seizure, and never put anything in your mouth.",
        ],
        numbers: [
          "Seizure diary: write down every seizure. The goal is no seizures, or the goal your provider sets for you.",
          "Sleep: aim for 7 to 8 hours of sleep each night, or the goal your provider sets for you.",
        ],
        medicines: [
          "Never stop your seizure medicine suddenly, even if you feel fine. Stopping all at once can cause severe seizures that do not stop.",
          "Take your medicine exactly as prescribed. If you miss a dose, call us or your pharmacist to ask what to do.",
          "If you have a rescue medicine for long seizures, make sure your family knows where it is and when to use it.",
          "Bring all your medicine bottles to every visit. Ask us before starting any new medicine or supplement, and tell us about side effects like sleepiness, dizziness, a rash or mood changes.",
        ],
        callUs: [
          "You have a seizure, more seizures than usual, or a new kind of seizure.",
          "You missed doses of your seizure medicine or ran out.",
          "You have side effects like a new rash, unsteady walking, double vision or feeling very sleepy.",
          "You are vomiting and cannot keep your medicine down.",
          "You feel very sad or worried, or notice big changes in your mood.",
        ],
        call911: [
          "A seizure lasts 5 minutes or longer, or seizures come one after another without the person waking up in between.",
          "The person has trouble breathing, does not wake up after the seizure, or is hurt, such as hitting their head.",
          "A seizure happens in water.",
          "You have thoughts of hurting yourself: call or text 988, or call 911 if you are in danger right now.",
        ],
      },
      es: {
        title: "Vivir con epilepsia (convulsiones)",
        whatItIs: "La epilepsia es una enfermedad del cerebro que causa crisis epilépticas una y otra vez. Una crisis (también llamada convulsión o ataque) es una descarga eléctrica repentina en el cerebro. Puede causar sacudidas, mirada fija, confusión o pérdida del conocimiento por un rato.",
        whyItMatters: "Las crisis pueden causar caídas, lesiones y accidentes de tránsito, y en casos raros pueden poner la vida en peligro. Tomar su medicina todos los días y evitar lo que las provoca es la mejor manera de prevenirlas.",
        whatYouCanDo: [
          "Tome su medicina para las crisis a las mismas horas todos los días. Use un pastillero o una alarma en el teléfono para no olvidar ninguna dosis.",
          "Duerma lo suficiente. Dormir poco es uno de los desencadenantes más comunes (algo que puede provocar una crisis).",
          "Limite o evite el alcohol y no use drogas. Ambos pueden provocar crisis.",
          "Lleve un diario de crisis: anote la fecha, la hora, cuánto duró, qué pasó y qué pudo haberla provocado.",
          "Cuídese: báñese en la regadera y no en la tina, nunca nade solo y use las hornillas de atrás de la estufa.",
          "No maneje hasta que su proveedor le diga que es seguro y las leyes de su estado lo permitan.",
          "Enseñe a su familia y amigos qué hacer durante una crisis: quedarse con usted, acostarle de lado, medir cuánto dura y nunca meterle nada en la boca.",
        ],
        numbers: [
          "Diario de crisis: anote cada crisis. La meta es no tener ninguna, o la meta que su proveedor le indique.",
          "Sueño: trate de dormir de 7 a 8 horas cada noche, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Nunca deje de golpe su medicina para las crisis, aunque se sienta bien. Suspenderla de repente puede causar crisis fuertes que no se detienen.",
          "Tome su medicina tal como se la recetaron. Si se le olvida una dosis, llámenos o pregúntele a su farmacéutico qué hacer.",
          "Si tiene una medicina de rescate para crisis largas, asegúrese de que su familia sepa dónde está y cuándo usarla.",
          "Traiga todos sus frascos de medicinas a cada cita. Pregúntenos antes de empezar cualquier medicina o suplemento nuevo, y díganos si tiene efectos secundarios como sueño, mareos, sarpullido o cambios de ánimo.",
        ],
        callUs: [
          "Tiene una crisis, más crisis de lo normal, o un tipo de crisis diferente.",
          "Se le olvidaron dosis de su medicina o se le acabó.",
          "Tiene efectos secundarios como un sarpullido nuevo, inestabilidad al caminar, visión doble o mucho sueño.",
          "Tiene vómitos y no puede retener la medicina.",
          "Siente mucha tristeza o preocupación, o nota cambios fuertes en su estado de ánimo.",
        ],
        call911: [
          "Una crisis dura 5 minutos o más, o vienen una tras otra sin que la persona despierte entre ellas.",
          "La persona tiene dificultad para respirar, no despierta después de la crisis, o se lastimó, por ejemplo, se golpeó la cabeza.",
          "La crisis ocurre en el agua.",
          "Tiene pensamientos de hacerse daño: llame o envíe un mensaje de texto al 988 (oprima 2 para español), o llame al 911 si corre peligro en este momento.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Seizure medicine must never be stopped suddenly; doses should be taken at the same times daily with alarms or pill organizers.",
        "Common triggers: missed doses, poor sleep, alcohol, illness and stress.",
        "Seizure first aid for family: stay calm, time it, turn the person on their side, nothing in the mouth, and call 911 at 5 minutes or for back-to-back seizures.",
        "Keep a seizure diary and bring it to neurology and primary care visits.",
        "Safety: showers instead of baths, no swimming alone, and follow provider and state guidance on driving.",
        "Check with the care team before any new medicine or supplement, and make sure the seizure action plan and any rescue medicine instructions are current.",
      ],
      ask: [
        "Have you had any seizures since we last talked? About how many, and what was happening before them?",
        "Are you able to take your seizure medicine every day on time? What makes it hard?",
        "Have you had any falls, injuries, or side effects like dizziness or sleepiness?",
        "How have your sleep and mood been?",
        "Does your family know what to do during a seizure and when to call 911?",
      ],
    },
    carePlan: {
      problem: "Epilepsy (specify seizure type, e.g., focal or generalized, and whether intractable)",
      expectedOutcome: "With consistent antiseizure therapy and trigger avoidance, the expected outcome is seizure freedom or the lowest achievable seizure frequency with minimal side effects and injury.",
      goals: [
        "Seizure freedom, or at least a 50% reduction in seizure frequency from baseline over 6 months as documented in a seizure diary (or as individualized by the provider).",
        "Antiseizure medication adherence of at least 90% by refill history or patient report (or as individualized by the provider).",
        "Written seizure action plan (including rescue therapy if prescribed) documented and reviewed with the patient and caregiver within 3 months and then annually (or as individualized by the provider).",
        "No seizure-related injuries or emergency visits over 12 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Seizure frequency, type and triggers from the seizure diary at each monthly CCM contact and office visit.",
        "Medication adherence and side effects at each monthly CCM contact; drug levels and labs as indicated per neurology.",
        "Screening for depression, anxiety and suicidality at least annually and with any change in mood.",
        "Bone health (vitamin D, DEXA) as indicated with long-term antiseizure therapy, per provider.",
        "Safety counseling (driving, water, heights, cooking) documented at least annually.",
      ],
      interventions: [
        "Coordinate neurology follow-up; refer to a comprehensive epilepsy center if seizures continue after adequate trials of two appropriate antiseizure medications (drug-resistant epilepsy), per provider.",
        "Monthly medication reconciliation with interaction review before any new medication; therapy per neurology.",
        "Seizure first-aid and safety education for patient and caregivers; provide a written seizure action plan.",
        "Fall and home safety assessment for patients whose seizures cause falls.",
        "Behavioral health referral for mood, anxiety or memory concerns.",
      ],
      selfManagement: [
        "Take antiseizure medicines on schedule and never stop them abruptly.",
        "Keep a seizure diary (date, time, duration, triggers).",
        "Keep regular sleep, limit alcohol, avoid recreational drugs, and manage stress.",
        "Follow safety precautions (showers, no swimming alone, driving restrictions per provider and state law).",
        "Make sure caregivers know seizure first aid and the rescue plan.",
      ],
      symptomManagement: [
        "Breakthrough seizure: record in the diary, review adherence and triggers, and notify neurology or the provider within 1 business day.",
        "Seizure lasting 5 minutes or longer, clusters, or no recovery between seizures: rescue therapy per the action plan if prescribed and call 911.",
        "New rash, unsteady gait, excessive sedation or mood change on therapy: prompt provider evaluation.",
        "Acute illness with vomiting or missed doses: contact the provider for a plan to prevent breakthrough seizures.",
      ],
      coordination: [
        "Neurology or a comprehensive epilepsy center.",
        "Behavioral health for mood and anxiety.",
        "Epilepsy Foundation resources and support groups; Area Agency on Aging and transportation services when driving is restricted.",
        "Pharmacy for interaction checks and refill synchronization.",
      ],
    },
    basis: [
      "AAN Epilepsy Quality Measurement Set",
      "AES Guideline for the Treatment of Convulsive Status Epilepticus in Children and Adults (2016)",
    ],
  },

  // ---------------------------------------------------------------- Multiple sclerosis
  {
    key: "ms",
    education: {
      en: {
        title: "Living with multiple sclerosis (MS)",
        whatItIs: "Multiple sclerosis (MS) is a disease where the immune system, which normally fights germs, attacks the coating that protects the nerves in the brain and spinal cord. This can cause problems with walking, balance, vision, feeling, bladder control, energy and thinking. MS is different for each person.",
        whyItMatters: "MS can have flare-ups (also called relapses) and may slowly get worse over time. Treatment and healthy habits can lower flare-ups, protect your nerves and help you stay active and independent.",
        whatYouCanDo: [
          "Keep your visits with your nerve specialist (neurologist), and get your scans and blood tests on time.",
          "Stay active. Exercise, stretching and physical therapy help with strength, balance and tiredness.",
          "Save your energy. Plan rest breaks, and do your hardest tasks when you have the most energy.",
          "Stay cool. Heat can make MS symptoms worse for a while, so use fans and cool drinks, and avoid very hot baths.",
          "Do not smoke. Smoking can make MS worse. We can help you quit.",
          "Wash your hands often, and keep your vaccines up to date. Ask us before any vaccine, because some are not safe with certain MS medicines.",
          "Prevent falls: keep walkways clear, use grab bars, and use a cane or walker if one is recommended.",
        ],
        numbers: [
          "Exercise: aim for about 150 minutes of activity a week, in short sessions if needed, or the goal your provider sets for you.",
          "Brain MRI (a scan that takes detailed pictures of your brain): often about once a year while you are on MS treatment, or the goal your provider sets for you.",
        ],
        medicines: [
          "MS medicines that prevent flare-ups work best when taken exactly as prescribed. Do not stop them without talking to your neurologist; stopping some suddenly can cause a bad flare-up.",
          "Many MS medicines weaken your body's defense against germs. Call us right away if you have a fever or signs of infection.",
          "Keep up with the blood tests and scans your MS medicine needs to stay safe.",
          "Bring all your medicine bottles to every visit, and tell us about side effects or any trouble paying for or getting your medicine.",
        ],
        callUs: [
          "You have new symptoms, or old symptoms get worse and last more than 24 hours, such as weakness, numbness, blurry vision or trouble walking.",
          "You have a fever of 100.4°F (38°C) or higher, burning when you urinate, a cough, or other signs of infection.",
          "You fall, or your balance is getting worse.",
          "You have trouble controlling your bladder or bowels, or you feel you cannot empty your bladder.",
          "You feel very sad, hopeless or worried, or you have new trouble thinking clearly.",
        ],
        call911: [
          "Sudden loss of vision, sudden weakness on one side of the body, face drooping, or trouble speaking.",
          "Trouble breathing, or choking that does not stop.",
          "A high fever with confusion, or feeling very sick, if you take medicines that weaken your immune system.",
          "Thoughts of hurting yourself: call or text 988, or call 911 if you are in danger right now.",
        ],
      },
      es: {
        title: "Vivir con esclerosis múltiple (EM)",
        whatItIs: "La esclerosis múltiple (EM) es una enfermedad en la que el sistema inmunitario, que normalmente combate los microbios, ataca la capa que protege los nervios del cerebro y la médula espinal. Esto puede causar problemas para caminar, de equilibrio, de la vista, de sensibilidad, para controlar la vejiga, de energía y para pensar. La EM es diferente en cada persona.",
        whyItMatters: "La EM puede tener brotes (también llamados recaídas) y puede empeorar poco a poco con el tiempo. El tratamiento y los hábitos sanos pueden reducir los brotes, proteger sus nervios y ayudarle a mantenerse activo e independiente.",
        whatYouCanDo: [
          "No falte a sus citas con el especialista de los nervios (neurólogo), y hágase a tiempo los estudios de imagen y los análisis de sangre.",
          "Manténgase activo. El ejercicio, los estiramientos y la fisioterapia ayudan con la fuerza, el equilibrio y el cansancio.",
          "Cuide su energía. Planee ratos de descanso y haga las tareas más pesadas cuando tenga más energía.",
          "Manténgase fresco. El calor puede empeorar los síntomas de la EM por un rato; use ventiladores, tome bebidas frías y evite los baños muy calientes.",
          "No fume. Fumar puede empeorar la EM. Le podemos ayudar a dejarlo.",
          "Lávese las manos seguido y mantenga sus vacunas al día. Pregúntenos antes de cualquier vacuna, porque algunas no son seguras con ciertas medicinas para la EM.",
          "Evite caídas: mantenga los pasillos despejados, use barras de apoyo y use bastón o andadera si se lo recomendaron.",
        ],
        numbers: [
          "Ejercicio: trate de hacer unos 150 minutos de actividad por semana, en ratos cortos si es necesario, o la meta que su proveedor le indique.",
          "Resonancia magnética del cerebro (un estudio que toma imágenes detalladas del cerebro): por lo general una vez al año mientras recibe tratamiento para la EM, o la meta que su proveedor le indique.",
        ],
        medicines: [
          "Las medicinas que previenen los brotes de EM funcionan mejor si las toma tal como se las recetaron. No las deje sin hablar con su neurólogo; suspender algunas de golpe puede causar un brote fuerte.",
          "Muchas medicinas para la EM bajan las defensas del cuerpo contra los microbios. Llámenos de inmediato si tiene fiebre o señales de infección.",
          "Hágase a tiempo los análisis de sangre y los estudios que su medicina para la EM requiere para usarla con seguridad.",
          "Traiga todos sus frascos de medicinas a cada cita, y díganos si tiene efectos secundarios o problemas para pagar u obtener su medicina.",
        ],
        callUs: [
          "Tiene síntomas nuevos, o síntomas de antes empeoran y duran más de 24 horas, como debilidad, adormecimiento, visión borrosa o dificultad para caminar.",
          "Tiene fiebre de 100.4 °F (38 °C) o más, ardor al orinar, tos u otras señales de infección.",
          "Se cae, o su equilibrio está empeorando.",
          "Tiene problemas para controlar la orina o las evacuaciones, o siente que no puede vaciar la vejiga.",
          "Siente mucha tristeza, desesperanza o preocupación, o tiene problemas nuevos para pensar con claridad.",
        ],
        call911: [
          "Pérdida repentina de la vista, debilidad repentina de un lado del cuerpo, la cara caída o dificultad para hablar.",
          "Dificultad para respirar, o se atraganta y no se le quita.",
          "Fiebre alta con confusión, o se siente muy enfermo, si toma medicinas que bajan las defensas.",
          "Pensamientos de hacerse daño: llame o envíe un mensaje de texto al 988 (oprima 2 para español), o llame al 911 si corre peligro en este momento.",
        ],
      },
    },
    talkingPoints: {
      teach: [
        "Disease-modifying therapy lowers relapse risk; it should be taken as prescribed and not stopped without talking to neurology.",
        "Infection precautions on immune-suppressing therapy: report fever or infection signs promptly and check with the care team before any vaccine.",
        "How to recognize a relapse (new or worse symptoms lasting more than 24 hours) and report it promptly; infections and heat can temporarily worsen old symptoms.",
        "Energy conservation, staying cool, regular exercise and physical therapy.",
        "Fall prevention and practical bladder and bowel tips.",
        "Quitting smoking and getting support for mood are part of MS care.",
      ],
      ask: [
        "Have you had any new or worse symptoms this month, like vision changes, numbness, weakness or trouble walking?",
        "Are you taking your MS medicine as prescribed and keeping up with labs and scans? Any problems getting it?",
        "Have you had any falls, fevers or infections?",
        "How are your energy, bladder, mood and thinking?",
        "What daily tasks are getting harder, and what help do you have at home?",
      ],
    },
    carePlan: {
      problem: "Multiple sclerosis (specify phenotype: relapsing-remitting, secondary progressive or primary progressive)",
      expectedOutcome: "Multiple sclerosis is chronic and may progress; goals are fewer relapses, slower disability progression, and preserved function, safety and quality of life.",
      goals: [
        "No clinical relapses and no new MRI lesions over 12 months on disease-modifying therapy (or as individualized by the provider).",
        "At least 80% adherence to disease-modifying therapy, with required safety labs and MRIs completed on schedule (or as individualized by the provider).",
        "Physical activity of at least 150 minutes per week as tolerated, with no injurious falls over 12 months (or as individualized by the provider).",
        "Vaccinations up to date per the CDC adult schedule, timed with therapy per neurology, within 6 months (or as individualized by the provider).",
      ],
      monitoring: [
        "Relapse symptoms, disability (e.g., walking ability; EDSS per neurology) and function at each neurology visit (typically every 6–12 months) and at monthly CCM contacts.",
        "Brain MRI per neurology, commonly annually while on disease-modifying therapy.",
        "Disease-modifying therapy safety labs (e.g., CBC, liver enzymes) and infection screening per neurology and the therapy's monitoring requirements.",
        "Depression, fatigue, cognition, and bladder and bowel symptoms at least annually and at monthly CCM contacts.",
        "Fall risk at least annually and after any fall; bone health as indicated with steroid exposure or immobility.",
      ],
      interventions: [
        "Coordinate neurology follow-up, MRI and therapy lab monitoring; close the loop on results.",
        "Referral to physical and occupational therapy for mobility, spasticity, energy conservation and home safety; speech-language therapy for swallowing or speech concerns.",
        "Vaccination review per the CDC adult schedule, coordinating live-vaccine restrictions with neurology.",
        "Screen for depression and refer to behavioral health as needed.",
        "Smoking-cessation support and cardiovascular risk management.",
        "Bladder and bowel symptom management, with urology referral per provider.",
      ],
      selfManagement: [
        "Take disease-modifying therapy as prescribed and keep lab and MRI appointments.",
        "Exercise regularly and use energy-conservation and cooling strategies.",
        "Report new or worsening symptoms lasting more than 24 hours, and any fever or infection.",
        "Avoid smoking and keep healthy eating and sleep habits.",
        "Use mobility aids and home safety measures as recommended.",
      ],
      symptomManagement: [
        "Suspected relapse (new or worse symptoms for more than 24 hours without fever): contact neurology within 1–2 days and check for infection (pseudo-relapse).",
        "Fever or infection on immunosuppressive therapy: same-day evaluation; therapy decisions per neurology.",
        "Fatigue, spasticity, pain or bladder dysfunction: report for symptomatic therapy per provider or neurology, plus PT/OT strategies.",
        "Mood changes: depression screening and behavioral health referral; 988 for crisis.",
      ],
      coordination: [
        "Neurology or an MS center.",
        "Physical, occupational and speech-language therapy; urology as needed.",
        "National Multiple Sclerosis Society resources and local support groups; Area Agency on Aging for in-home support and transportation.",
        "Behavioral health for mood and adjustment.",
      ],
    },
    basis: [
      "AAN Practice Guideline: Disease-Modifying Therapies for Adults with Multiple Sclerosis (2018)",
      "MAGNIMS-CMSC-NAIMS Consensus Recommendations on the Use of MRI in Multiple Sclerosis (2021)",
      "CDC Adult Immunization Schedule",
    ],
  },
];
